<?
echo '<h1>'.$this->title.'</h1>';
echo '<h3>'.$this->subtitle.'</h3>';
?>        
<form enctype="application/x-www-form-urlencoded" action="<?php echo $this->action_url; ?>" method="post">

<?= $this->group($this->groupPersonSubmitter); ?>
<?= $this->group($this->groupPersonAuthor); ?>
<?= $this->element($this->Language_); ?>
<?= $this->group($this->groupTitleMain); ?>
<?= $this->group($this->groupTitleAbstract); ?>
<?= $this->element($this->TitleSub); ?>
<?= $this->element($this->TitleAdditional_); ?>
<?= $this->element($this->TitleParent_); ?>
<?= $this->element($this->PageNumber_); ?>
<?= $this->element($this->PageFirst_); ?>
<?= $this->element($this->PageLast_); ?>
<?= $this->element($this->Volume_); ?>
<?= $this->element($this->Issue_); ?>
<?= $this->element($this->Journal_); ?>
<?= $this->element($this->Institute_); ?>
<?= $this->element($this->Collection_); ?>
<?= $this->element($this->PublishedYear_); ?>
<?= $this->element($this->PublishedDate_); ?>
<?= $this->element($this->PublisherName_); ?>
<?= $this->element($this->PublisherPlace_); ?>
<?= $this->element($this->CompletedYear_); ?>
<?= $this->element($this->CompletedDate_); ?>
<?= $this->element($this->ThesisDateAccepted); ?>
<?= $this->element($this->ThesisPublisher); ?>
<?= $this->element($this->IdentifierOpus3_); ?>
<?= $this->element($this->IdentifierUrn_); ?>
<?= $this->element($this->IdentifierIsbn_); ?>
<?= $this->element($this->IdentifierIssn_); ?>
<?= $this->element($this->IdentifierOpac_); ?>
<?= $this->group($this->groupThesisGrantor); ?>
<?= $this->group($this->groupThesisPublisher); ?>
<?= $this->group($this->groupPersonReferee); ?>
<?= $this->group($this->groupPersonEditor); ?>
<?= $this->group($this->groupPersonAdvisor); ?>
<?= $this->group($this->groupPersonTranslator); ?>
<?= $this->group($this->groupPersonContributor); ?>
<?= $this->group($this->groupCreatingCorporation); ?>
<?= $this->group($this->groupContributingCorporation); ?>
<?= $this->group($this->groupSubjectSwd); ?>
<?= $this->group($this->groupSubjectUncontrolled); ?>
<?= $this->element($this->Note_); ?>
<?= $this->element($this->Licence_); ?>
<?= $this->element($this->ServerDateUnlocking_); ?>

<?= $this->element($this->fullText, null, "Hidden", "fullText"); ?>
<?= $this->element("all", null, "Hidden",  "documentType"); ?>
<?= $this->element($this->documentId, null, "Hidden", "documentId"); ?>
<?= $this->element('button_label_send', null, "Submit",  "send"); ?>

</form>

