<?php
echo '<h1>' . $this->title . '</h1>';
echo '<h2>' . $this->subtitle . '</h2>';

//for printing a generized Zend Form with standard layout:
//echo $this->form;
//element($value, $options = null, $type = null, $name = null)
//group($value, $options = null, $name = null)
?>
<span class="formerror"> <?= $this->errorCaseMessage; ?> </span>

<br />
<form enctype="application/x-www-form-urlencoded" action="<?php echo $this->action_url; ?>" method="post">

    <div class="formhint">
<?= $this->requiredHint; ?>
    </div>

    <?= $this->group($this->groupPersonSubmitter); ?>
    <?= $this->group($this->groupPersonAuthor); ?>
    <?= $this->element($this->Language); ?>
    <?= $this->group($this->groupTitleMain); ?>
    <?= $this->group($this->groupTitleAbstract); ?>
    <?= $this->group($this->groupTitleSub); ?>
    <?= $this->group($this->groupTitleAdditional); ?>
    <?= $this->group($this->groupTitleParent); ?>
    <?= $this->element($this->PageNumber); ?>
    <?= $this->element($this->PageFirst); ?>
    <?= $this->element($this->PageLast); ?>
    <?= $this->element($this->Volume); ?>
    <?= $this->element($this->Issue); ?>
    <?= $this->element($this->Institute); ?>
    <?= $this->element($this->Collection); ?>
    <?= $this->element($this->PublishedYear); ?>
    <?= $this->element($this->PublishedDate); ?>
    <?= $this->element($this->PublisherName); ?>
    <?= $this->element($this->PublisherPlace); ?>
    <?= $this->element($this->CompletedYear); ?>
    <?= $this->element($this->CompletedDate); ?>
    <?= $this->element($this->IdentifierOpus3); ?>
    <?= $this->element($this->IdentifierUrn); ?>
    <?= $this->element($this->IdentifierIsbn); ?>
    <?= $this->element($this->IdentifierIssn); ?>
    <?= $this->element($this->IdentifierOpac); ?>
    <?= $this->element($this->ThesisDateAccepted); ?>
    <?= $this->element($this->ThesisGrantor); ?>
    <?= $this->element($this->ThesisPublisher); ?>
    <?= $this->group($this->groupPersonReferee); ?>
    <?= $this->group($this->groupPersonEditor); ?>
    <?= $this->group($this->groupPersonAdvisor); ?>
    <?= $this->group($this->groupPersonTranslator); ?>
    <?= $this->group($this->groupPersonContributor); ?>
    <?= $this->element($this->CreatingCorporation); ?>
    <?= $this->element($this->ContributingCorporation); ?>
    <?= $this->group($this->groupSubjectSwd); ?>
    <?= $this->group($this->groupSubjectUncontrolled); ?>
    <?= $this->element($this->Note); ?>
    <?= $this->element($this->Licence); ?>
    <?= $this->element($this->ServerDateUnlocking); ?>
    <?= $this->group($this->groupSubjectDdc); ?>

<?= $this->element('button_label_send', null, "Submit", "send"); ?>

</form>

