<?
echo '<h1>'.$this->title.'</h1>';
echo '<h3>'.$this->subtitle.'</h3>';
?>        
    
<form enctype="application/x-www-form-urlencoded" action="/opus4-devel/index.php/publish/index/check" method="post">

<?= $this->group($this->groupPersonSubmitter); ?>
<?= $this->group($this->groupTitleMain); ?>
<?= $this->element($this->TitleSub_); ?>
<?= $this->group($this->groupTitleAbstract); ?>
<?= $this->group($this->groupPersonAuthor); ?>
<?= $this->element($this->CompletedYear_); ?>

<?= $this->group($this->groupPersonAdvisor); ?>
<?= $this->element($this->ThesisGrantor_); ?>
<?= $this->element($this->ThesisPublisher_); ?>

<?= $this->element($this->Institute_); ?>
<?= $this->element($this->Collection_); ?>

<?= $this->element($this->PublisherName_); ?>
<?= $this->element($this->PublisherPlace_); ?>
<?= $this->element($this->PageNumber_); ?>
<?= $this->element($this->PublishedYear_); ?>
<?= $this->element($this->IdentifierIsbn_); ?>

<?= $this->group($this->groupPersonContributor); ?>
<?= $this->group($this->groupContributingCorporation); ?>
<?= $this->group($this->groupSubjectSwd); ?>
<?= $this->group($this->groupSubjectUncontrolled); ?>
<?= $this->element($this->IdentifierUrn_); ?>
<?= $this->element($this->Note_); ?>
<?= $this->element($this->Language_); ?>
<?= $this->element($this->Licence_); ?>
<?= $this->element($this->ServerDateUnlocking_); ?>

<?= $this->element($this->fullText, null, "Hidden", "fullText"); ?>
<?= $this->element("bachelorthesis", null, "Hidden",  "documentType"); ?>
<?= $this->element($this->documentId, null, "Hidden", "documentId"); ?>
<?= $this->element('button_label_send', null, "Submit",  "send"); ?>

</form>

