<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<h2><?= $this->translate($this->title) ?></h2>

<div class="content">
    <h3 class="document-type" ><?= $this->subtitle?></h3>

    <div id="form-table-check">
        <div class="form-hint"><p><?= $this->hint; ?></p></div>
        <table cellspacing='5' cellpadding='10' width="60%" border="0">

            <!-- listing all fieldsets/groups with their form elements -->
            <?php foreach ($this->form->getDisplayGroups() as $group) : ?>
                <?php if (count($group->getElements()) >= 1) { ?>
                    <tr><td class='group' colspan="2"><b><?= $this->translate($group->getName()) ?></b></td></tr>

                <?php } foreach ($group->getElements() as $element) : ?>
                        <?php if ($element->getValue() !== '') : ?>
                            <tr><td class='label'><?= $this->translate($element->getLabel()) ?></td>
                            <?php if ($element->getType() === 'Zend_Form_Element_Select') : ?>
                                <td><?= htmlspecialchars($element->getMultiOption($element->getValue())) ?></td>
                            <?php  else : ?>
                                <?php if ($element->getType() === 'Zend_Form_Element_Checkbox') : ?>
                                    <?php if ($element->getValue()) : ?>
                                        <td><?= $this->translate('yes'); ?></td>
                                    <?php else : ?>
                                        <td><?= $this->translate('no'); ?></td>
                                    <?php endif ?>
                                <?php else : ?>
                                    <td><?= $element->getValue() !== null ? htmlspecialchars($element->getValue(), ENT_DISALLOWED) : '' ?></td>
                                <?php endif ?> <!--checkbox-->
                            <?php endif ?> <!--select-->
                            </tr>
                            <?php $this->form->removeElement($element->getName()); ?>
                        <?php endif; ?> <!--!=""-->
                <?php endforeach;?> <!--$element-->
            <?php endforeach;?>
            <!-- END: groups -->

            <!-- listing all single elements -->
            <tr><td class='group' colspan="2"><b><?= $this->translate('publish_controller_check_otherElements') ?></b></td></tr>
            <?php foreach ($this->form->getElements() as $elem) : ?>
                <?php if ($elem->getValue() !== null && $elem->getValue() !== '') : ?>
                    <tr><td class='label'><?= $this->translate($elem->getLabel()) ?></td>
                        <?php if ($elem->getType() === 'Zend_Form_Element_Select') : ?>
                            <td><?= htmlspecialchars($elem->getMultiOption($elem->getValue())) ?></td>
                        <?php  else : ?>
                            <?php if ($elem->getType() === 'Zend_Form_Element_Checkbox') : ?>
                                <?php if ($elem->getValue()) : ?>
                                    <td><?= $this->translate('yes'); ?></td>
                                <?php else : ?>
                                    <td><?= $this->translate('no'); ?></td>
                                <?php endif ?>
                            <?php else : ?>
                                <td><?= htmlspecialchars($elem->getValue() ?? '', ENT_DISALLOWED) ?></td>
                            <?php endif ?>
                        <?php endif ?>
                    </tr>
                    <?php $this->form->removeElement($elem->getName()); ?>
                <?php endif; ?>
            <?php endforeach;?>
            <!-- END: single -->

        </table>

        <?= $this->fileOverview(); ?>
        <?= $this->bibliographieOverview(); ?>
    </div>

    <form enctype="application/x-www-form-urlencoded" action="<?= $this->action_url; ?>" method="post">
        <div class="button-wrapper">
            <?= $this->element('button_label_abort', "class='form-button abort-button'", "Submit", "abort"); ?>
            <?= $this->element('button_label_back', "class='form-button abort-button'", "Submit", "back"); ?>
            <?= $this->element('button_label_send2', "class='form-button submit-button'", "Submit", "send"); ?>
        </div>
    </form>

</div>
