<?php
echo '<h1>'. $this->title . '</h1>';
echo '<h3>'. $this->subtitle . '</h3>';

echo "<table cellspacing='10' cellpadding='20'>";
$defaultNS = new Zend_Session_Namespace('Publish');

$elements = $defaultNS->elements;
$i = 1;

foreach ($elements as $element){
    
        if ($element != "") {
            if (fmod($i, 2) == 0 ) {
                
                echo "<tr><td align='right'><b>" . $element['label']. "</b></td><td>". $element['value'] ."</td></tr>\n";
                $i = $i + 1;
            }
            else {
                
                echo "<tr style='background-color:#efefef;'><td align='right'><b>" . $element['label']. "</b></td><td>". $element['value'] ."</td></tr>\n";
                $i = $i + 1;
            }
        }
    
}

echo $this->form;

?>


