<?php
echo '<h1>'. $this->title . '</h1>';
echo '<h3>'. $this->subtitle . '</h3>';

echo "<table cellspacing='10' cellpadding='20'>";

$elements = $this->form->getElements();
$i = 1;

foreach ($elements as $element){
    if ($element->getType() != "Zend_Form_Element_Submit" && $element->getType() != "Zend_Form_Element_Hidden") {
        if ($element != "") {
            if (fmod($i, 2) == 0 ) {
                
                echo "<tr><td align='right'><b>" . $element->getLabel(). "</b></td><td>". $element->getValue() ."</td></tr>\n";
                $i = $i + 1;
            }
            else {
                
                echo "<tr style='background-color:#efefef;'><td align='right'><b>" . $element->getLabel(). "</b></td><td>". $element->getValue() ."</td></tr>\n";
                $i = $i + 1;
            }
        }
    }
}

echo "</table><br/><br/><br/>";
echo '<h3>'. $this->header . '</h3>';
echo $this->form;

?>


