<?php
echo '<h1>' . $this->title . '</h1>';
echo '<h2>' . $this->subtitle . '</h2>';

//for printing a generized Zend Form with standard layout:
//echo $this->form;

//element($value, $options = null, $type = null, $name = null)
//group($value, $options = null, $name = null)
?>
<span class="formerror"><?= $this->errorCaseMessage; ?></span>

<br />
<form enctype="application/x-www-form-urlencoded" action="<?php echo $this->action_url; ?>" method="post">

    <div class="formhint">
        <?= $this->requiredHint; ?>
    </div>
	
	<?= $this->group($this->groupPersonSubmitter); ?>
	<?= $this->group($this->groupTitleMain); ?>
	<?= $this->group($this->groupTitleSub); ?>
	<?= $this->group($this->groupTitleAbstract); ?>
	<?= $this->group($this->groupPersonAuthor); ?>
	<?= $this->element($this->CompletedDate_); ?>
	<?= $this->element($this->PageNumber_); ?>
	<?= $this->element($this->PageFirst_); ?>
	<?= $this->element($this->PageLast_); ?>
	<?= $this->element($this->PublisherName_); ?>
	<?= $this->element($this->PublisherPlace_); ?>
	<?= $this->element($this->PublishedDate_); ?>
	<?= $this->group($this->groupTitleParent); ?>
	<?= $this->group($this->groupPersonEditor); ?>
	<?= $this->group($this->groupPersonTranslator); ?>
	<?= $this->group($this->groupPersonContributor); ?>
	<?= $this->group($this->groupCreatingCorporation); ?>
	<?= $this->group($this->groupContributingCorporation); ?>
	<?= $this->group($this->groupSubjectDdc); ?>
	<?= $this->group($this->groupSubjectSwd); ?>
	<?= $this->group($this->groupSubjectUncontrolled); ?>
	<?= $this->element($this->Institute_); ?>
	<?= $this->element($this->IdentifierUrn_); ?>
	<?= $this->element($this->IdentifierIsbn_); ?>
	<?= $this->element($this->IdentifierIssn_); ?>
	<?= $this->element($this->Note_); ?>
	<?= $this->element($this->Language_); ?>
	<?= $this->element($this->Licence_); ?>

	<?= $this->element('button_label_send', null, "Submit",  "send"); ?>

</form>

