<?php
echo '<h1>' . $this->title . '</h1>';
echo '<h2>' . $this->subtitle . '</h2>';

//for printing a generized Zend Form with standard layout:
//echo $this->form;

//element($value, $options = null, $type = null, $name = null)
//group($value, $options = null, $name = null)
?>
<span class="formerror"><?= $this->errorCaseMessage; ?></span>

<br />
<form enctype="application/x-www-form-urlencoded" action="<?php echo $this->action_url; ?>" method="post">

    <div class="formhint">
        <?= $this->requiredHint; ?>
    </div>
	
	<?= $this->group($this->groupPersonSubmitter); ?>
	<?= $this->group($this->groupTitleMain); ?>
	<?= $this->group($this->groupTitleSub); ?>
	<?= $this->group($this->groupTitleAbstract); ?>
	<?= $this->group($this->groupPersonAuthor); ?>
	<?= $this->element($this->CompletedDate); ?>

	<?= $this->group($this->groupPersonAdvisor); ?>
	<?= $this->element($this->ThesisGrantor); ?>
	<?= $this->element($this->ThesisPublisher); ?>

	<?= $this->element($this->Institute); ?>
	
	<?= $this->element($this->PublisherName); ?>
	<?= $this->element($this->PublisherPlace); ?>
	<?= $this->element($this->PageNumber); ?>
	<?= $this->element($this->PublishedDate); ?>
	<?= $this->element($this->IdentifierIsbn); ?>

	<?= $this->group($this->groupPersonContributor); ?>
	<?= $this->group($this->groupContributingCorporation); ?>
	<?= $this->group($this->groupSubjectDdc); ?>
	<?= $this->group($this->groupSubjectSwd); ?>
	<?= $this->group($this->groupSubjectUncontrolled); ?>
	<?= $this->element($this->IdentifierUrn); ?>
	<?= $this->element($this->Note); ?>
	<?= $this->element($this->Language); ?>
	<?= $this->element($this->Licence); ?>

        <?= $this->element('button_label_abort', null, "Submit", "abort"); ?>
	<?= $this->element('button_label_send', null, "Submit",  "send"); ?>

</form>

