<?php
echo '<h1>' . $this->title . '</h1>';
echo '<h2>' . $this->subtitle . '</h2>';

//for printing a generized Zend Form with standard layout:
//echo $this->form;

//element($value, $options = null, $type = null, $name = null)
//group($value, $options = null, $name = null)
?>
<span style="color:red; font-weight:big; padding: 10pt;"> <?= $this->errorCaseMessage; ?> </span>

<br />
<form enctype="application/x-www-form-urlencoded" action="<?php echo $this->action_url; ?>" method="post">

    <div width="100%" align="right">
        <?= $this->requiredHint; ?>
    </div>

    <?= $this->group($this->groupPersonAuthor); ?>
    <?= $this->group($this->groupInstitute); ?>
    <?= $this->element($this->Language_); ?>
    <?= $this->group($this->groupTitleMain, "size='60'"); ?>
    <?= $this->group($this->groupTitleAbstract, "cols='60' rows='9'"); ?>
    <?= $this->group($this->groupProject); ?>
    <?= $this->group($this->groupSubjectMSC); ?>
    <?= $this->group($this->groupSubjectUncontrolled); ?>
    <?= $this->element($this->Note_, "cols='60' rows='9'"); ?>
        
    <?= $this->element('button_label_send', null, "Submit",  "send"); ?>

</form>

