<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Susanne Gottwald <gottwald@zib.de>
 * @author      Doreen Thiede <thiede@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<h2><?= $this->title ?></h2>
<div class="content">
<h3 class="document-type" tile="Dokumententyp"><?= $this->subtitle?></h3>

<?php if (isset($this->errorCaseMessage)) : ?>
    <div class="form-hint form-errors"><p><?= $this->errorCaseMessage; ?></p></div>
<?php endif; ?>

<form enctype="application/x-www-form-urlencoded" action="<?= $this->action_url; ?>" method="post">
<div class="form-items-wrapper">

    <div class="form-hint"><p><?= $this->requiredHint; ?></p></div>

    <?= $this->group($this->groupPersonAuthor); ?>
    <?= $this->element($this->Language); ?>
    <?= $this->group($this->groupTitleMain, "size='60'"); ?>
    <?= $this->group($this->groupTitleAbstract, "cols='60' rows='9'"); ?>

    <?= $this->group($this->groupInstitute); ?>
    <?= $this->group($this->groupProject); ?>
    <?= $this->group($this->groupSubjectMSC); ?>
    <?= $this->group($this->groupSubjectUncontrolled); ?>
    <?= $this->group($this->groupSeries); ?>

    <?= $this->fileOverview(); ?>

    <div class="button-wrapper">
        <?= $this->element('button_label_abort', "class='form-button abort-button'", "Submit", "abort"); ?>
        <?= $this->element('button_label_send', "class='form-button submit-button'", "Submit", "send"); ?>
    </div>

</div>
</form>

<?php if ($this->endTemplate($this->form) !== "") : ?>
    <div class="form-hint form-errors"><?= $this->endTemplate($this->form); ?></div>
<?php endif; ?>

</div>
