<?
echo '<h1>'.$this->title.'</h1>';
echo '<h3>'.$this->subtitle.'</h3>';

?>


<form enctype="application/x-www-form-urlencoded" action="<?php echo $this->action_url; ?>" method="post">

<?= $this->field("Element", null, $this->PersonSubmitterFirstName_); ?>
<?= $this->field("Element", null, $this->PersonSubmitterLastName_); ?>
<?= $this->field("Group", null, $this->groupPersonAuthor); ?>
<?= $this->field("Group", null, $this->groupTitleMain); ?>
<?= $this->field("Element", null, $this->Language_); ?>
<?= $this->field("Element", null, $this->PublishedYear_); ?>
<?= $this->field("Group", null, $this->groupSubjectSwd); ?>
<?= $this->field("Element", null, $this->IdentifierOpus3_); ?>
<?= $this->field("Group", null, $this->groupTitleAbstract); ?>
<?= $this->field("Element", null, $this->Licence_); ?>
<?= $this->field("Group", null, $this->groupPersonAdvisor); ?>
<?= $this->field("Group", null, $this->groupPersonContributor); ?>
<?= $this->field("Group", null, $this->groupCreatingCorporation); ?>
<?= $this->field("Group", null, $this->groupContributingCorporation); ?>
<?= $this->field("Element", null, $this->PageNumber_); ?>
<?= $this->field("Element", null, $this->IdentifierUrn_); ?>
<?= $this->field("Element", null, $this->IdentifierOpac_); ?>
<?= $this->field("Element", null, $this->Note_); ?>
    
<?= $this->field("Hidden", "fullText", $this->fullText); ?>
<?= $this->field("Hidden", "documentType", "studienarbeit"); ?>
<?= $this->field("Hidden", "documentId", $this->documentId); ?>
<?= $this->field("Submit", "send", "Formular abschicken"); ?>

</form>

