Information zum OPUS4-Dokumentenserver!

Ein neues Dokument wurde auf Ihrem OPUS4-Dokumentenserver hochgeladen.

<?php if (!empty($authors)) : ?>
Autor(en):
<?php foreach ($authors as $author) : ?>
<?php echo $author . "\n" ?>
<?php endforeach ?>
<?php else : ?>
Autor(en): n/a
<?php endif ?>

<?php if ($title != '') : ?>
Titel: <?php echo $title . "\n" ?>
<?php else : ?>
Titel: n/a
<?php endif ?>

Dokument-ID: <?= $docId . "\n" ?>


Änderungen an dem hochgeladenen Dokument sowie das Freischalten sind über den Admin-Bereich möglich:

<?= $url . "\n" ?>


Mit freundlichen Grüßen

Der OPUS-Mailadmin
