<?php
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    TODO
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div id="adminMenuContainer">
    <dl>
        <?PHP foreach ($this->info->getInfo() as $infoKey => $infoValue) : ?>
            <dt id="<?= $infoKey ?>"><?= $this->translate($infoKey) ?></dt>
            <dd><?= $infoValue ?></dd>
        <?PHP endforeach ?>
    </dl>

    <fieldset>
        <legend><?= $this->translate('admin_info_section_upload') ?></legend>

        <table class="systeminfo">
            <tr>
                <th class="label"><?= $this->translate('admin_info_column_setting') ?></th>
                <th class="value"><?= $this->translate('admin_info_column_value') ?></th>
                <th class="location"><?= $this->translate('admin_info_column_location') ?></th>
                <th class="description"><?= $this->translate('admin_info_column_description') ?></th>
            </tr>
            <tr>
                <td class="label">publish.maxfilesize</td>
                <td class="value"><?= htmlspecialchars($this->maxfilesize) ?></td>
                <td class="location">config.ini</td>
                <td class="description"><?= $this->translate('admin_info_maxfilesize_description') ?></td>
            </tr>
            <tr>
                <td class="label">upload_max_filesize</td>
                <td class="value"><?= htmlspecialchars($this->uploadMaxFilesize) ?></td>
                <td class="location">php.ini</td>
                <td class="description"><?= $this->translate('admin_info_uploadmaxfilesize_description') ?></td>
            </tr>
            <tr>
                <td class="label">post_max_size</td>
                <td class="value"><?= htmlspecialchars($this->postMaxSize) ?></td>
                <td class="location">php.ini</td>
                <td class="description"><?= $this->translate('admin_info_postmaxsize_description') ?></td>
            </tr>
        </table>

    </fieldset>

    <fieldset>
        <legend><?= $this->translate('admin_info_index_async_description') ?></legend>
        <? if ($this->asyncjobs): ?>

            <table class="worker-jobs">
                <tr>
                    <th><?= $this->translate('admin_info_index_failedjobs') ?></th>
                </tr>
                <? if ($this->failedJobCount && count($this->failedJobCount) > 0): ?>

                    <? foreach ($this->failedJobCount as $label => $count) : ?>
                        <tr>
                            <td class="label"><?= $this->translate('admin_info_index_joblabel') ?></td>
                            <td class="value"><?= $this->translate('admin_info_index_jobcount') ?></td>
                        </tr>
                        <tr>
                            <td class="label">
                                <a href="<?= $this->url(array('action' => 'job-detail', 'label' => $label, 'state' => Opus_Job::STATE_FAILED)) ?>" title="<?=$this->translate('admin_info_index_job_detail_hint')?>"><?= $this->translate('admin_info_job_label-'.$label) ?></a>
                            </td>
                            <td class="value"><?= $count ?></td>
                        </tr>
                    <? endforeach ?>
                <? else: ?>
                    <tr>
                        <td><?= $this->translate('admin_info_index_nofailedjobs') ?></td>
                    </tr>
                <? endif ?>
            </table>

            <table class="worker-jobs">
                <tr>
                    <th><?= $this->translate('admin_info_index_unprocessedjobs') ?></th>
                </tr>
                <? if ($this->unprocessedJobCount && count($this->unprocessedJobCount) > 0): ?>

                    <? foreach ($this->unprocessedJobCount as $label => $count) : ?>
                        <tr>
                            <td class="label"><?= $this->translate('admin_info_index_joblabel') ?></td>
                            <td class="value"><?= $this->translate('admin_info_index_jobcount') ?></td>
                        </tr>
                        <tr>
                            <td class="label">
                                <a href="<?= $this->url(array('action' => 'job-detail', 'label' => $label, 'state' => Opus_Job::STATE_UNDEFINED)) ?>" title="<?=$this->translate('admin_info_index_job_detail_hint')?>"><?= $this->translate('admin_info_job_label-'.$label) ?></a>

                            </td>
                            <td class="value"><?= $count ?></td>
                        </tr>
                    <? endforeach ?>
                <? else: ?>
                    <tr>
                        <td><?= $this->translate('admin_info_index_nounprocessedjobs') ?></td>
                    </tr>
                <? endif ?>
            </table>

        <? else: ?>
            <div><?= $this->translate('admin_info_index_async_disabled') ?></div>
        <? endif ?>

    </fieldset>

</div>