<?php
/**
 * View to browse lists to select filter criteria by click
 *
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Search
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @author      Thoralf Klein <thoralf.klein@zib.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
    echo '<h2>' . $this->title . '</h2>';
    // Show list view of the selected list

    echo '<ul>';
    if ($this->list === "collection")
	{
		#print_r($this->browsinglist->describe());
       
      # Check if LinkDocsPathToRoot is set to "count" or "both" for this
      # CollectionRole.  Only in these two cases, the document count is
      # calculated over all SubCollections and we can use it to skip
      # empty collections!  Disable with "$hideEmptyCollections = false;"

      $thisCollectionRole = new Opus_CollectionRole($this->collection);
      $browseListCountStyle = $thisCollectionRole->getLinkDocsPathToRoot();
      $trustDocumentCount = (($browseListCountStyle === 'count') || ($browseListCountStyle === 'both'));
      $hideEmptyCollections = true;

	    if (in_array('Collections', $this->browsinglist->describe())) {
	        $subcollections = $this->browsinglist->getCollection();
	    } else {
	    	$subcollections = $this->browsinglist->getSubCollection();
	    }

        foreach ($subcollections as $coll)    {
            // Hidden collections shouldn't be browsable
            if(true === $coll->getVisibility()) {

                // $documentCount = Opus_Collection_Information::countAllCollectionDocuments($this->collection, $coll->getId());

		$node = $coll->getNode();
                $documentCountSubtree = $node->getNumSubtreeEntries();
                $documentCountCurrent = $node->getNumEntries();

                if ($hideEmptyCollections && $browseListCountStyle !== 'none' && $documentCountCurrent === 0 && $documentCountSubtree == 0) {
                    echo '<li>' . $coll->getDisplayName() . '</li>';
                }
                else {
                // for Collections $this->browsinglist must be the ListIterator of all ChildNodes, not the current node itself...
                echo '<li>';
                echo '<a href="' .
                $this->url(
                     array(
                         'module'        => 'search',
                         'controller'    => 'browsing',
                         'action'        => 'browseList',
                         'list'          => 'collection',
                         'collection'    => $this->collection,
                         'node'          => $coll->getId()
                     ),
                     null,
                     true
                 ) .
                 '">';
                    echo $coll->getDisplayName();
                    if ($browseListCountStyle === 'count') {
                        echo '</a> (' . $documentCountCurrent . ') (' . $this->translate('browsing_total_number') . ' ' . $documentCountSubtree . ')';
                    }
                    else if ($browseListCountStyle === 'none') {
                    	echo '</a>';
                    }
                    else if ($browseListCountStyle === 'both') {
                    	echo '</a> (' . $documentCountSubtree . ')';
                    }
                    else {
                    	echo '</a> (' . $documentCountCurrent . ')';
                    }
                    echo '</li>';
                }
            }
        }
	}
    if ($this->list === 'persons')
    {
	   foreach ($this->browsinglist as $obj) {
            $pers = $obj->get();
            #$titleCount = BrowsingFilter::hasTitles($pers['id'], $this->role);
            $role = $this->role;
            if ($role !== 'author') $role = 'persons';
            #if ($titleCount > 0) {
                echo '<li>';
             echo '<a href="' .
                 $this->url(
                     array(
                         'module'        => 'search',
                         'controller'    => 'search',
                         'action'        => 'metadatasearch',
                         'noform'        => 'true',
                         $role     => $pers['lastName'] . ', ' . $pers['firstName']
                     ),
                     null,
                      true
                 ) .
                 '">';
                 echo $pers['lastName'] . ', ' . $pers['firstName'];
                 echo '</a>';
                 #echo ' (' . $titleCount. ')';
                 echo '</li>';
            #}
        }
	}
    if ($this->list === 'doctypes')
    {
        foreach ($this->browsinglist as $obj) {
         echo '<li>';
         echo '<a href="' .
         $this->url(
             array(
                 'module'        => 'search',
                 'controller'    => 'search',
                 'action'        => 'metadatasearch',
                 'noform'        => 'true',
                 'doctype'       => $obj
             ),
             null,
             true
         ) .
        '">';
        echo $this->translate($obj);
        echo '</a>';
         echo ' <a href="' .
         $this->url(
             array(
                 'module'        => 'search',
                 'controller'    => 'opensearch',
                 'action'        => 'query',
                 'q'             => 'doctype:' . $obj
             ),
             null,
             true
         ) .
        '">';
        echo '<img src="/layouts/default/img/rss.gif" width="36" height="14" border="0" align="bottom" alt="RSS-Feed Icon" title="RSS-Feed abonnieren" />';
        echo '</a>';
        echo '</li>';
        }
    }
    echo '</ul>';


    // Show documents in this Collection hierarchy
    if ($this->list === 'collection')
	{
        if ($this->numberOfDocuments > 0) {
            echo $this->paginationControl($this->documents_paginator, NULL, 'collectionEntries_ItemCount_pagination.phtml');
            echo $this->paginationControl($this->documents_paginator, 'Sliding', 'searchList_pagination.phtml');
            
            $pagerInfo = $this->documents_paginator->getPages();
            echo '<ol class="search" start="' . $pagerInfo->firstItemNumber . '">';
            $searchListItemCount = 0;    
            for ($runningIndex = 0; $runningIndex < count($this->docId); $runningIndex++) {
                $searchListItemCount++;
                $searchListOdd = ($searchListItemCount%2 === 1);
                echo $searchListOdd ? '<li class="odd">' : '<li class="even">';
                $authorcount = count($this->author[$runningIndex]);
                for ($counter = 0; $counter < $authorcount; $counter++) {
                ?>
                    <span class="author"><a href="<?=$this->url_author[$runningIndex][$counter]?>"><?=$this->author[$runningIndex][$counter]?></a></span>
                <?php
                    if ($counter === $authorcount-1) echo ": ";
                    else echo "; ";
                }
                ?>
                <span class="title"><a href="<?=$this->url_frontdoor[$runningIndex]?>"><?=$this->doctitle[$runningIndex]?></a></span>
                </li>
                <div class="queryhit">
                <?php
                if (false === empty($this->relevance[$runningIndex])) {
                ?>
                    <?=$this->translate('search_titles_relevance')?>: <?=$this->relevance[$runningIndex]?><br/>
                <?php } ?>
                <?=$this->abstractValue[$runningIndex]?>
                </div>
            <?php
            }
            ?>
            </ol>
            <?= $this->paginationControl($this->documents_paginator, 'Sliding', 'searchList_pagination.phtml') ?>
        <?php 
        } 
	}
	?>