<?php
/**
 * View to browse title information on filtered title lists
 * 
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Search
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
	switch ($this->filter)
	{
		case 'author':
			echo "<h2>".$this->translate('search_titles_authors')." ".$this->author["firstName"]." ".$this->author["lastName"]."</h2>";
			break;
		case 'doctype':
			echo "<h2>".$this->translate('search_titles_doctypes')." ".$this->doctype["name"]."</h2>";
			break;
		default:
			echo "<h2>".$this->translate('search_titles_all')."</h2>";
	}
	echo "<ul>";
	$n = 0;
	while ($this->hitlist->valid() === true)
	{
		$hit = $this->hitlist->current();
		$document = $hit->getSearchHit();
		$data = $document->getDocument();
		$authoriterator = new Opus_Search_Iterator_PersonsListIterator($data["author"]);
		//print_r($document); # just to debug
		echo "<li>";
		#$doctype = $data["documentType"]->get();
		while ($authoriterator->valid() === true)
		{
			$obj = $authoriterator->current();
			$pers = $obj->get();
			echo "<a href=".$this->url(array("controller"=>"browsing", "action"=>"browseTitles", "filter" => "author", "author"=>$pers["id"])).">";
			echo $pers["lastName"].", ".$pers["firstName"];
			echo "</a>";
			if ($authoriterator->hasNext() === true) echo "; ";
			else echo ": ";
			$authoriterator->next();
		}
		echo "<a href=\"".$this->url($data["frontdoorUrl"])."\">";
		print($data["title"]);
		echo "</a>";
		#echo " (".$doctype["name"].")";
		echo "</li>";
		$this->hitlist->next();
	}
	echo "</ul>";
	?>