<?php
/**
 * Index View for BrowsingController including links to several browsing lists and search functions
 *
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Search
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
	<h2><?= $this->translate('search_index_browsing') ?></h2>
	<a href="<?= $this->url(array('module' => 'search', 'controller' => 'browsing', 'action' => 'browseTitles'), null, true) ?>"><?= $this->translate('search_index_alltitlesbrowsing') ?></a><br/>
	<?php
	   $roles = array('author', 'editor', 'advisor','contributor','referee','other','translator');
	   foreach ($roles as $role) {
	       $translatelabel = 'search_index_' . $role . 'browsing';
	       echo '<a href="' . $this->url(array('module' => 'search', 'controller' => 'browsing', 'action' => 'browseList', 'list' => 'persons', 'role' => $role), null, true) . '">' . $this->translate($translatelabel) . '</a><br/>';
	   }
	?>
	<a href="<?= $this->url(array('module' => 'search', 'controller' => 'browsing', 'action' => 'browseList', 'list' => 'doctypes'), null, true) ?>"><?= $this->translate('search_index_doctypebrowsing') ?></a><br/>
	<?php
	// Browsable roles of persons:
    // 'advisor','contributor','referee','other','translator'
	// get the list of hierarchical lists from the Collections-Classes
	#print_r($this->browsinglist);
	if (count($this->browsinglist) > 0) {
	   foreach ($this->browsinglist as $obj)
	   {
		  echo '<a href=' . $this->url(array('module' => 'search', 'controller' => 'browsing', 'action' => 'browseList', 'list' => 'collection', 'collection' => $obj->getId()), null, true) . '>';
		  echo $obj->getName();
		  echo "</a><br/>";
	   }
	}
	/* static list of hierarchical lists
	 * <a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "institutions")) ?>">Browsing nach Institutionen</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "schriftenreihe")) ?>">Browsing nach Schriftenreihen</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "collections")) ?>">Browsing nach Collections</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "ddc")) ?>">Browsing nach DDC-Sachgruppen</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "ccs")) ?>">Browsing nach CCS-Klassifikation</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "jel")) ?>">Browsing nach JEL-Klassifikation</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "msc")) ?>">Browsing nach MSC-Klassifikation</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "pacs")) ?>">Browsing nach PACS-Klassifikation</a><br/>
	<a href="<?= $this->url(array("controller"=>"browsing", "action"=>"browseList", "list" => "bkl")) ?>">Browsing nach BKL-Klassifikation</a><br/>
	**/