<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2013, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<div id="adminMenuContainer">

    <fieldset>
        <legend><?= $this->translate('admin_job_job_detail_description') ?>: <?= $this->translate('admin_job_label_' . $this->label) ?></legend>

        <table class="worker-jobs">
            <tr>
                <td><?=$this->translate('admin_job_id')?></td>
                <td><?=$this->translate('admin_job_sha1_id')?></td>
                <td><?=$this->translate('admin_job_state')?></td>
                <td><?=$this->translate('admin_job_data')?></td>
                <td><?=$this->translate('admin_job_errors')?></td>
            </tr>

            <?PHP if ($this->jobs && count($this->jobs) > 0) : ?>

                <?PHP foreach ($this->jobs as $job) : ?>
                    <tr>
                        <td><?= $job->getId() ?></td>
                        <td><?= $job->getSha1Id()?></td>
                        <td><?= $this->translate('admin_job_state_' . ($job->getState() ? : 'unprocessed')) ?></td>
                        <td>
                            <?PHP foreach ((array) $job->getData() as $key => $value) : ?>
                                <div><?= $key ?>: <?= $value ?></div>
                            <?PHP endforeach ?>

                        <td>
                            <?PHP
                            $error = $job->getErrors();
                            if (! empty($error)) :
                                $errorObject = json_decode($error);
                                ?>
                                <div><?= $this->translate('admin_job_exception_classname') ?>: <?= $errorObject->exception ?></div>
                                <div><?= $this->translate('admin_job_exception_message') ?>: <?= $errorObject->message ?></div>
                            <?PHP endif ?>
                        </td>
                    </tr>
                <?PHP endforeach ?>
            <?PHP else : ?>
                <tr>
                    <td><?= $this->translate('admin_job_index_nofailedjobs') ?></td>
                </tr>
            <?PHP endif ?>
        </table>

    </fieldset>

</div>