<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

use Opus\Common\Job;

?>

<div id="adminMenuContainer">
    <dl>
    <fieldset>
        <legend><?= $this->translate('admin_job_index_async_description') ?></legend>
        <?PHP if ($this->asyncjobs) : ?>

            <table class="worker-jobs">
                <tr>
                    <th><?= $this->translate('admin_job_index_failedjobs') ?></th>
                </tr>
                <?PHP if ($this->failedJobCount && count($this->failedJobCount) > 0) : ?>

                    <?PHP foreach ($this->failedJobCount as $label => $count) : ?>
                        <tr>
                            <td class="label"><?= $this->translate('admin_job_index_joblabel') ?></td>
                            <td class="value"><?= $this->translate('admin_job_index_jobcount') ?></td>
                        </tr>
                        <tr>
                            <td class="label">
                                <a href="<?= $this->url(['action' => 'detail', 'label' => $label, 'state' => Job::STATE_FAILED]) ?>" title="<?=$this->translate('admin_job_index_job_detail_hint')?>"><?= $this->translate('admin_job_label_' . $label) ?></a>
                            </td>
                            <td class="value"><?= $count ?></td>
                        </tr>
                    <?PHP endforeach ?>
                <?PHP else : ?>
                    <tr>
                        <td><?= $this->translate('admin_job_index_nofailedjobs') ?></td>
                    </tr>
                <?PHP endif ?>
            </table>

            <table class="worker-jobs">
                <tr>
                    <th><?= $this->translate('admin_job_index_unprocessedjobs') ?></th>
                </tr>
                <?PHP if ($this->unprocessedJobCount && count($this->unprocessedJobCount) > 0) : ?>

                    <?PHP foreach ($this->unprocessedJobCount as $label => $count) : ?>
                        <tr>
                            <td class="label"><?= $this->translate('admin_job_index_joblabel') ?></td>
                            <td class="value"><?= $this->translate('admin_job_index_jobcount') ?></td>
                        </tr>
                        <tr>
                            <td class="label">
                                <a href="<?= $this->url(['action' => 'detail', 'label' => $label, 'state' => Job::STATE_UNDEFINED]) ?>" title="<?=$this->translate('admin_job_index_job_detail_hint')?>"><?= $this->translate('admin_job_label_' . $label) ?></a>

                            </td>
                            <td class="value"><?= $count ?></td>
                        </tr>
                    <?PHP endforeach ?>
                <?PHP else : ?>
                    <tr>
                        <td><?= $this->translate('admin_job_index_nounprocessedjobs') ?></td>
                    </tr>
                <?PHP endif ?>
            </table>

        <?PHP else : ?>
            <div><?= $this->translate('admin_job_index_async_disabled') ?></div>
        <?PHP endif ?>

    </fieldset>

</div>