<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Henning Gerhardt (henning.gerhardt@slub-dresden.de)
 * @copyright   Copyright (c) 2009, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div class="adminContainer">

    <div class="breadcrumbsContainer">
        <?= $this->navigation()->breadcrumbs() ?>
    </div>

    <div>
        <ul>
            <li>
                <?PHP if($this->showFilemanager === true) : ?>
                    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'filemanager', 'action' => 'index', 'docId' => $this->docId), null, true); ?>"><?= $this->translate('admin_filemanager_index'); ?></a>
                <?PHP else : ?>
                    <?= $this->translate('no_file_according_to_dtd') ?>
                <?PHP endif; ?>
            </li>
            <li><a href="#collections"><?= $this->translate('admin_documents_label_collections') ?></a></li>
        </ul>
        <ul>
            <?php if ($this->actions === 'publish') : ?>
            <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'delete', 'docId' => $this->docId), null, true); ?>"><?= $this->translate('admin_doc_delete'); ?></a></li>
            <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'publish', 'docId' => $this->docId), null, true); ?>"><?= $this->translate('admin_documents_publish'); ?></a></li>
            <?php elseif ($this->actions === 'unpublish') : ?>
            <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'delete', 'docId' => $this->docId), null, true); ?>"><?= $this->translate('admin_doc_delete'); ?></a></li>
            <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'unpublish', 'docId' => $this->docId), null, true); ?>"><?= $this->translate('admin_documents_unpublish'); ?></a></li>
            <?php elseif ($this->actions === 'undelete') : ?>
            <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'publish', 'docId' => $this->docId), null, true); ?>"><?= $this->translate('admin_doc_undelete'); ?></a></li>
            <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'permanentdelete', 'docId' => $this->docId), null, true); ?>"><?= $this->translate('admin_doc_delete_permanent'); ?></a></li>
            <?php endif; ?>
        </ul>
    </div>

    <?= $this->form; ?>

    <fieldset>
        
        <legend><a name="collections"><?= $this->translate('admin_documents_label_collections') ?></a></legend>

    <div>
        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'document' => $this->docId), null, true); ?>"><?= $this->translate('admin_documents_collectionassign'); ?></a><br/>
    </div>

    <?PHP if (0 < count($this->assignedCollections)) : ?>
        <?= $this->translate('admin_documents_collectionsassigned') ?>
    <?PHP else : ?>
        <?= $this->translate('admin_documents_nocollectionsassigned') ?>
    <?PHP endif; ?>

    <ul>
        <?PHP foreach ($this->assignedCollections as $collection) : ?>
        <li>
            <?= $collection['roleName']?>: <?= $collection['collectionName'] ?>
            <form method="post" action="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'unlinkcollection', 'role' => $collection['roleId'], 'collection' => $collection['collectionId'])) ?>">
                <input type="submit" value="<?= $this->translate('admin_documents_unlinkcollection') ?>" />
            </form>
        </li>
        <?PHP endforeach; ?>
    </ul>
        
    </fieldset>
</div>