<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2017, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

/**
 * TODO this is just a prototype, an experiment - code should be made into view helper or something like it
 * TODO hide/show facet
 * TODO highlight selected value
 * TODO translation for all facets
 */

?>

<?PHP $values = $this->personRoles ?>

<div class="facet">
    <h4 class="facet-title"><?= $this->translate('Role') ?></h4>
    <div>
        <ul class="facet-values">
            <?PHP foreach ($values as $value => $link) : ?>
                <?PHP if ($this->role !== $value) : ?>
                    <li><a href="<?= $link ?>"><?= $this->translate('Opus_Person_Role_Value_' . ucfirst($value)) ?></a></li>
                <?PHP else : ?>
                    <li class="active"><?= $this->translate('Opus_Person_Role_Value_' . ucfirst($this->role)) ?></li>
                <?PHP endif ?>
            <?PHP endforeach ?>
        </ul>
    </div>
    <div class="facet-expand-toggle"></div>
</div>
