<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Henning Gerhardt (henning.gerhardt@slub-dresden.de)
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2009, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<h1><?php echo $this->translate('admin_documents_index'); ?></h1>

<?php
        $url_call_id = array(
            'module' => 'admin',
            'controller' => 'documents',
            'action' => 'edit'
        );
        $url_call_id = $this->url($url_call_id, 'default', true);
?>
<p>
<form action="<?php echo $url_call_id ?>" method="post" class="crud">
     <input type="text" name="id" />
     <input type="submit" value="<?php echo $this->translate('docs_call_id'); ?>" />
</form>
</p><br/><br/>
<?php
foreach ($this->registers as $register) {
	?>
	<a href="<?=$register[0] ?>"><?php echo $this->translate($register[1]); ?></a> |
	<?php
}

// Sorting the titles
        $url_sort_by_id = array(
            'module' => 'admin',
            'controller' => 'documents',
            'action' => 'index',
            'sort_order' => 'id'
        );
        $url_sort_by_title = array(
            'module' => 'admin',
            'controller' => 'documents',
            'action' => 'index',
            'sort_order' => 'title'
        );
        $url_sort_by_doctype = array(
            'module' => 'admin',
            'controller' => 'documents',
            'action' => 'index',
            'sort_order' => 'docType'
        );
        $url_sort_by_author = array(
            'module' => 'admin',
            'controller' => 'documents',
            'action' => 'index',
            'sort_order' => 'author'
        );
        $url_sort_by_id = $this->url($url_sort_by_id, 'default', false);
        $url_sort_by_title = $this->url($url_sort_by_title, 'default', false);
        $url_sort_by_doctype = $this->url($url_sort_by_doctype, 'default', false);
        $url_sort_by_author = $this->url($url_sort_by_author, 'default', false);
?>
<br/>
<?php echo $this->translate('docs_sortorder'); ?> <a href="<?php echo $url_sort_by_id ?>"><?php echo $this->translate('docs_by_id'); ?></a> <a href="<?php echo $url_sort_by_title ?>"><?php echo $this->translate('docs_by_title'); ?></a> <a href="<?php echo $url_sort_by_author ?>"><?php echo $this->translate('docs_by_author'); ?></a> <a href="<?php echo $url_sort_by_doctype ?>"><?php echo $this->translate('docs_by_doctype'); ?></a>
<br/>
<?php
$documentList = $this->documentList;
if (false === empty($documentList)) { ?>
<p>
<ol>
    <?php foreach ($documentList as $docId => $title) {
        if (true === empty($title)) {
            $title = array(0 => 'Opus document with id: ' . $docId);
        }
        $url_frontdoor = array(
            'module' => 'frontdoor',
            'controller' => 'index',
            'action' => 'index',
            'docId' => $docId
        );
        $url_edit = array(
            'module' => 'admin',
            'controller' => 'documents',
            'action' => 'edit',
            'id' => $docId
        );
        $url_delete = array (
            'module' => 'admin',
            'controller' => 'documents',
            'action' => 'delete',
        );
        $url_edit = $this->url($url_edit, 'default', true);
        $url_delete = $this->url($url_delete, 'default', true);
        $url_frontdoor = $this->url($url_frontdoor, 'default', true);
    ?>
        <li>
        <?php echo '<a href="' . $url_frontdoor . '" target="_blank">' . current($title) . '</a> (ID ' . $docId . ')' ?>
        <form action="<?php echo $url_delete ?>" method="post" class="crud">
            <a href="<?php echo $url_edit ?>"><?php echo $this->translate('docs_edit'); ?></a>
            <input type="hidden" name="id" value="<?php echo $docId ?>" />
            <input type="submit" value="<?php echo $this->translate('docs_delete'); ?>" />
        </form>
        </li>
        <?php
    } ?>
</ol>
</p>
<?php } else { ?>
    <p><?php echo $this->translate('docs_nodocs'); ?></p>
<?php } ?>
