<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Henning Gerhardt (henning.gerhardt@slub-dresden.de)
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2009-2013, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div class="documentOptions">
    <?PHP if (!empty($this->collection)) : ?>
        <?=$this->translate('admin_documents_label_collection')?>: <b><?=htmlspecialchars($this->collectionName)?></b>
    <?PHP elseif (!empty($this->series)) : ?>
        <?= $this->translate('Opus_Series') ?>: <b><?=htmlspecialchars($this->series->getTitle())?></b>
    <?PHP else : ?>
    <div class="docstateMenu">
        <dl class="dropdown">
            <dt><a><?= $this->translate('admin_documents_show_docs') ?></a></dt>
            <dd>
                <ul>
                    <li class="active"><?= $this->translate('admin_documents_state_' . $this->state) ?></li>    
                    <?PHP foreach ($this->registers as $state => $link) : ?>
                        <?PHP if ($this->state !== $state) : ?>
                            <li><a href="<?= $link ?>"><?= $this->translate('admin_documents_state_' . $state) ?></a></li>
                        <?PHP endif; ?>
                    <?PHP endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>

    <div class="docstateMenu">
        <dl class="dropdown">
            <dt><a><?= $this->translate('docs_sortorder') ?></a></dt>
            <dd>
                <ul>
                    <li class="active"><?= $this->translate('admin_documents_sortby_' . $this->sort_order) ?></li>    
                    <?PHP foreach ($this->sortingLinks as $key => $link) : ?>
                    <?PHP if ($this->sort_order !== $key) : ?>
                        <li><a href="<?= $link ?>"><?= $this->translate('admin_documents_sortby_' . $key) ?></a></li>
                    <?PHP endif; ?>
                    <?PHP endforeach; ?>
                </ul>
            </dd>
        </dl>
        <dl class="dropdown">
            <dt><a><?= $this->translate('docs_sortorder') ?></a></dt>
            <dd>
                <ul>
                    <li class="active"><?= $this->translate('admin_documents_sort_' . $this->sortDirection) ?></a></li>
                    <?PHP foreach ($this->directionLinks as $key => $link) : ?>
                        <?PHP if ($key !== $this->sortDirection) : ?>
                    <li><a href="<?= $link ?>"><?= $this->translate('admin_documents_sort_' . $key) ?></a></li>
                        <?PHP endif; ?>
                    <?PHP endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>

    <div class="crud-wrapper">
        <form action="<?= $this->url_call_id ?>" method="post" class="crud">
            <div>
                <input type="text" name="id" size="5" placeholder="<?= $this->translate('docs_call_id_placeholder') ?>"/>
                <i class="placeholder"><?= $this->translate('docs_call_id_label') ?></i>
                <input type="submit" value="<?= $this->translate('docs_call_id') ?>" />
            </div>
        </form>
    </div>
    <?PHP endif; ?>
</div>

<div class ="paginationInfo">
    <?= $this->paginationControl($this->paginator, NULL, 'itemCount_pagination.phtml') ?>
</div>

<div class="itemCountLinks">
    <p><?= $this->translate('admin_documents_maxhitsperpage') ?></p>
    <ul>
<?PHP foreach ($this->itemCountLinks as $link) : ?>
<?PHP if ($link['label'] != $this->maxHitsPerPage && ($link['label'] !== 'all' || $this->maxHitsPerPage != 0)) : ?>
        <li><a href="<?= $link['url'] ?>"><?PHP if ($link['label'] === 'all') : ?>
<?= $this->translate('admin_documents_maxhitsperpage_all') ?><?PHP else : ?><?= $link['label'] ?>
<?PHP endif; ?></a><?PHP else : ?>
<?PHP if ($link['label'] === 'all') : ?><?= $this->translate('admin_documents_maxhitsperpage_all') ?>
<?PHP else : ?>
        <li class="current"><?= $link['label'] ?>
<?PHP endif; ?>
<?PHP endif; ?></li>
<?PHP endforeach; ?>
    </ul>
</div>
<?= $this->paginationControl($this->paginator, 'Sliding', 'results_pagination.phtml') ?>

<table class="documents">
    <?PHP $index = 0; foreach ($this->paginator as $docId) : ?>
    <?PHP $document = new Util_DocumentAdapter($this, $docId); ?>
    <tr class="<?= ($index++ % 2) ? 'even' : 'odd' ?>">
        <td class="id"><?= $docId ?></td>
        <td class="info">
            <?PHP $authorsCount = count($document->getAuthors()) - 1; ?>
            <?PHP foreach($document->getAuthors() as $count => $author) : ?>
            <span class="author">
                <?PHP if ($this->linkToAuthorSearch) : ?>
                    <a href="<?= $author['url'] ?>"><?= $author['name'] ?></a>
                <?PHP else : ?>
                    <?= $author['name'] ?>
                <?PHP endif; ?>
            </span>
                <?= ($count < $authorsCount) ? '; ' : ': '?>
            <?PHP endforeach; ?>
            <span class="title"><a href="<?=$this->documentUrl()->adminShow($docId) ?>"
                title="<?= $this->translate('admin_documents_tooltip_show') ?>"
                                   ><?= htmlspecialchars($document->getDocTitle()) ?></a></span>
            (<span class="pubDate"><?= $document->getYear() ?></span>)
        </td>
        <?PHP if (!empty($this->series)) : ?>
        <td>
            <span><?= $this->seriesNumber($document->getDocument(), $this->series) ?></span>
        </td>
        <?PHP endif; ?>
        <td class="doctype">
            <span class="doctype"><?=htmlspecialchars($this->translate($document->getDocType())) ?></span>
        </td>
        <td class="files">
            <span class="files">
                <a href="<?=$this->documentUrl()->adminFilemanager($docId)?>"
                   title="<?=$this->translate("admin_documents_link_filemanager")?>"><?=$document->getFileCount() ?></a>
            </span>
        </td>
        <td class="bibliography">
            <?PHP if ($document->isBelongsToBibliography()) : ?>
            <span class="bibliography" title="<?= htmlspecialchars($this->translate('admin_documents_tooltip_belongsToBibliography_true')) ?>">
                <?= htmlspecialchars($this->translate('Bibliography_Value_True')) ?>
            </span>
            <?PHP else : ?>
            <span class="bibliography" title="<?= htmlspecialchars($this->translate('admin_documents_tooltip_belongsToBibliography_false')) ?>">
                <?= htmlspecialchars($this->translate('Bibliography_Value_False')) ?>
            </span>
            <?PHP endif; ?>
        </td>
        <?PHP if (!empty($this->collection)) : ?>
        <td class="">
            <span class=""><?= $document->getDocState() ?></span>
        </td>
        <?PHP endif; ?>
        <td class="edit">
            <a href="<?= $this->documentUrl()->adminEdit($docId) ?>"><?= $this->translate('admin_button_edit') ?></a>
        </td>
    </tr>
    <?PHP endforeach; ?>
</table>

<?= $this->paginationControl($this->paginator, 'Sliding', 'results_pagination.phtml') ?>