<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Henning Gerhardt (henning.gerhardt@slub-dresden.de)
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2009, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div class="adminContainer">

    <div class="breadcrumbsContainer">
        <?= $this->navigation()->breadcrumbs() ?>
    </div>

    <div style="text-align: center; margin: 0.1em 0em">
        <form action="<?= $this->url_call_id ?>" method="post" class="crud">
             <?= $this->translate('docs_call_id_label') ?>
             <input type="text" name="id" size="5" />
             <input type="submit" value="<?= $this->translate('docs_call_id') ?>" />
        </form>
    </div>

    <div class="documentOptions">
        <div class="docstateMenu">
            <span><?= $this->translate('admin_documents_show_docs') ?></span>
            <?php foreach ($this->registers as $state => $link) : ?>
            <span class="<?= ($this->state === $state) ? 'active' : '' ?>">
                <a href="<?= $link ?>"><?= $this->translate('admin_documents_state_' . $state) ?></a>
            </span>
            <?php endforeach; ?>
        </div>

        <div class="docstateMenu">
            <span><?= $this->translate('docs_sortorder') ?></span>
            <?PHP foreach ($this->sortingLinks as $key => $link) : ?>
            <span class="<?= ($this->sort_order === $key) ? 'active' : '' ?>">
                <a href="<?= $link ?>"><?= $this->translate('admin_documents_sortby_' . $key) ?></a>
            </span>
            <?PHP endforeach; ?>
            <span>-</span>
            <?PHP foreach ($this->directionLinks as $key => $link) : ?>
            <span class="<?= ($key === $this->sortDirection) ? 'active' : '' ?>">
                <a href="<?= $link ?>"><?= $this->translate('admin_documents_sort_' . $key) ?></a>
            </span>
            <?PHP endforeach; ?>
        </div>
    </div>

    <?= $this->paginationControl($this->paginator, NULL, 'itemCount_pagination.phtml') ?>
    
    <?= $this->paginationControl($this->paginator, 'Sliding', 'results_pagination.phtml') ?>

    <table class="documents">
        <?PHP $index = 0; foreach ($this->paginator as $docId) : ?>
        <?PHP $document = new Review_Model_DocumentAdapter($this, $docId); ?>
        <tr class="<?= ($index++ % 2) ? 'even' : 'odd' ?>">
            <td class="id"><?= $docId ?></td>
            <td class="info">
                <?PHP $authorsCount = count($document->getAuthors()) - 1; ?>
                <?PHP foreach($document->getAuthors() as $count => $author) : ?>
                    <span class="author"><a href=""><?= $author ?></a></span>
                    <?= ($count < $authorsCount) ? '; ' : ': '?>
                <?PHP endforeach; ?>
                <span class="title"><a href="<?=$document->getUrlFrontdoor() ?>"><?= $document->getDocTitle() ?></a></span>
                (<span class="doctype"><?= $document->getDocType() ?></span>,
                <span class="pubDate"><?= $document->getPublishedDate() ?></span>)
            </td>
            <td class="actions">
                <form action="<?= $document->getUrlDelete() ?>" method="post" class="crud">
                    <input type='button' onClick="javascript:location.href='<?= $document->getUrlEdit() ?>'" value='<?= $this->translate('docs_edit') ?>' class="crud">
                    <input type="hidden" name="id" value="<?= $document->getDocId() ?>" />
                    <input type="submit" value="<?= $this->translate(($document->isDeleted()) ? 'docs_permadelete' : 'docs_delete') ?>" />
                </form>
            </td>
        </tr>
        <?PHP endforeach; ?>
    </table>

    <?= $this->paginationControl($this->paginator, 'Sliding', 'results_pagination.phtml') ?>

</div>

