<?php
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
<div class="adminContainer">

    <div class="breadcrumbsContainer">
        <?= $this->navigation()->breadcrumbs() ?> (<?= $this->objectId ?>)
    </div>

    <?PHP $doc = new Review_Model_DocumentAdapter($this, $this->objectId); ?>

    <div id="showdocmenu" style="padding: 0.5em 1em">
        <a href="<?= $this->docHelper->getUrlFrontdoor() ?>"><?= $this->translate('admin_documents_open_frontdoor') ?></a>
        <a href="<?= $this->docHelper->getUrlEdit() ?>"><?= $this->translate('docs_edit') ?></a>
        <?PHP if ($this->docHelper->hasFiles()) : ?>
        <a href="<?= $this->docHelper->getUrlFileManager() ?>"><?= $this->translate('admin_filemanager_index') ?></a>
        <?PHP endif; ?>
        <?php if ($this->docHelper->getDocState() === 'unpublished') : ?>
        <a href="<?= $this->docHelper->getUrlDelete() ?>"><?= $this->translate('admin_doc_delete'); ?></a>
        <a href="<?= $this->docHelper->getUrlPublish() ?>"><?= $this->translate('admin_documents_publish'); ?></a>
        <?php elseif ($this->docHelper->getDocState() === 'published') : ?>
        <a href="<?= $this->docHelper->getUrlDelete() ?>"><?= $this->translate('admin_doc_delete'); ?></a>
        <a href="<?= $this->docHelper->getUrlUnpublish() ?>"><?= $this->translate('admin_documents_unpublish'); ?></a>
        <?php elseif ($this->docHelper->getDocState() === 'deleted') : ?>
        <a href="<?= $this->docHelper->getUrlPublish() ?>"><?= $this->translate('admin_doc_undelete'); ?></a>
        <a href="<?= $this->docHelper->getUrlPermanentDelete() ?>"><?= $this->translate('admin_doc_delete_permanent'); ?></a>
        <?php endif; ?>
    </div>

    <div>
        <span class="label"><?= $this->translate('DocumentId') ?></span>
        <span class="value"><?= $this->docHelper->getDocId() ?></span>
    </div>

    <?= $this->showModel($this->entry) ?>

</div>
