<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Julian Heise <heise@zib.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id: $
 */

// TODO move some of the processing into model or controller
?>

<h1><?= $this->translate('access_select_module') ?></h1>
<p><?= $this->translate('access_current_roleid') . ' ' . $this->roleId ?></p>

<div class="form-wrapper">
    <form action="<?= $this->url(array('module'=>'admin', 'controller'=>'access', 'action'=>'store'), null ,true) ?>" method="post">

        <div class="form-item">
            <span class="form-submit-wrapper">
                <input type="submit" name="save_button" class="form-submit" value="<?= $this->translate('access_button_save') ?>"/>
            </span>
            <span class="form-submit-wrapper">
                <input type="submit" name="cancel_button" class="form-submit" value="<?= $this->translate('access_button_cancel') ?>"/>
            </span>
        </div>

        <br/>
        
        <?php foreach($this->allModules as $module=>$controllers) : ?>
        <h2><?= $module ?></h2>
        <ul class="controller-list">
            <?php foreach($controllers as $controller) : ?>
            <li>
                <input name="<?= 'set_'.$module.':'.$controller ?>" type="checkbox" value="set"
                <?PHP if (isset($this->guestModules) && array_key_exists($module, $this->guestModules) != null) {
                    $inGuest = in_array($controller, $this->guestModules[$module]) || in_array('*', $this->guestModules[$module]);
                } // TODO move to controller
                else {
                    $inGuest = false;
                } ?>
                <?PHP if (array_key_exists($module, $this->modules) != null) {
                    $inRole = in_array($controller, $this->modules[$module]) || in_array('*', $this->modules[$module]);
                }
                else {
                    $inRole = false;
                } ?>
                <?php if ($inRole || $inGuest) : ?>
                    checked="checked"
                <?php endif ?>
                <?PHP if ($inGuest) : ?>
                    disabled="true"
                <?PHP endif; ?>
                 /><?= $controller ?>
                <?PHP if ($inGuest) : ?>
                <span style="font-style: italic; color: gray; padding-left: 0.5em"><?= $this->translate('admin_access_checked_in_guest'); ?></span>
                <?PHP endif; ?>
                <input type="hidden" name="<?= 'list_'.$module.':'.$controller ?>" value="list" />
            </li>
            <?php endforeach ?>
        </ul>
        <?php endforeach ?>

        <div class="form-item">
            <span class="form-submit-wrapper">
                <input type="submit" name="save_button" class="form-submit" value="<?= $this->translate('access_button_save') ?>"/>
            </span>        
            <span class="form-submit-wrapper">
                <input type="submit" name="cancel_button" class="form-submit" value="<?= $this->translate('access_button_cancel') ?>"/>
            </span>
        </div>
        
        <input type="hidden" name="roleid" value="<?= $this->roleId ?>" />
    </form>
</div>