<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<h1><?= $this->translate('access_select_role') ?></h1>

<p><?= $this->translate('access_current_docid') . ' ' . $this->docId ?></p>

<h2><?= $this->translate('access_available_roles') ?></h2>

<form method="POST" action="<?= $this->url(['module' => 'admin', 'controller' => 'access', 'action' => 'store'], null, true) ?>">
    <ul>
    <?php foreach ($this->roles as $role) : ?>
        <li><input type="checkbox" name="<?= $role->getName()?>"
        <?php if (in_array($role->getId(), $this->checkedRoles)) : ?>
            checked="checked"
        <?php endif ?>
        /><?= $role->getName(); ?><br/></li>
    <?php endforeach ?>
    </ul>

    <input type="hidden" name="docid" value="<?=$this->docId?>" />

    <div class="form-item">
        <span class="form-submit-wrapper">
            <input type="submit" name="save_button" class="form-submit" value="<?= $this->translate('access_button_save') ?>"/>
        </span>
        <span class="form-submit-wrapper">
            <input type="submit" name="cancel_button" class="form-submit" value="<?= $this->translate('access_button_cancel') ?>"/>
        </span>
    </div>
</form>
