<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Julian Heise <heise@zib.de>
 * @copyright   Copyright (c) 2008-2011, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */

// TODO move some of the processing into model or controller
// TODO do this as a Zend_Form
?>

<h1><?= $this->translate('access_select_module', $this->roleName) ?></h1>
<p><?= $this->translate('access_current_role_name', $this->roleName) ?></p>

<h2><?= $this->translate('access_module_changes_affect_accounts') ?></h2>
<div>
    <?php foreach ($this->loginNames AS $login) : ?>
        <?= htmlspecialchars($login) ?>
    <?php endforeach; ?>
</div>
<br/>

<div class="form-wrapper">
    <form action="<?= $this->url(array('module'=>'admin', 'controller'=>'access', 'action'=>'store'), null ,true) ?>" method="post">

        <?PHP // Liste mit allen Modulen ?>
        <h2><?= $this->translate('access_module_changes') ?></h2>

        <ul class="permissions-list">
        <?php foreach($this->allModules as $module) : ?>
            <li>
            <input type="hidden" name="<?= 'list_'.$module ?>" value="list" />
            <input name="<?= 'set_'.$module ?>" type="checkbox" value="set"
                <?= in_array($module, $this->modules) ? ' checked="checked" ' : '' ?>
                <?= in_array($module, array('default')) ? ' disabled="disabled" ' : '' ?>
            /> <?= $this->translate('acl_resource_module_generic', array($module)); ?>
            <?PHP if (isset($this->guestModules) && in_array($module, $this->guestModules)) : ?>
                <span style="font-style: italic; color: gray; padding-left: 0.5em"><?= $this->translate('admin_access_checked_in_guest'); ?></span>
            <?PHP endif; ?>
          </li>
        <?php endforeach ?>
        </ul>

        <?PHP // Liste mit allen Ressourcen ?>
        <h2><?= $this->translate('access_resource_changes') ?></h2>

        <ul class="permissions-list">
        <?php foreach($this->allResources as $resource) : ?>
            <li>
            <input type="hidden" name="<?= 'list_'.$resource ?>" value="list" />
            <input name="<?= 'set_'.$resource ?>" type="checkbox" value="set"
                <?= in_array($resource, $this->modules) ? ' checked="checked" ' : '' ?>
                <?= in_array($resource, array('default')) ? ' disabled="disabled" ' : '' ?>
            /> <?= $this->translate('acl_' . $resource); ?>
            <?PHP if (isset($this->guestModules) && in_array($resource, $this->guestModules)) : ?>
                <span style="font-style: italic; color: gray; padding-left: 0.5em"><?= $this->translate('admin_access_checked_in_guest'); ?></span>
            <?PHP endif; ?>
          </li>
        <?php endforeach ?>
        </ul>

        <?PHP // Liste mit allen Workflow Übergängen ?>
        <h2><?= $this->translate('access_workflow_changes') ?></h2>

        <ul class="permissions-list">
        <?php foreach($this->allWorkflow as $resource) : ?>
            <li>
            <input type="hidden" name="<?= 'list_'.$resource ?>" value="list" />
            <input name="<?= 'set_'.$resource ?>" type="checkbox" value="set"
                <?= in_array($resource, $this->modules) ? ' checked="checked" ' : '' ?>
                <?= in_array($resource, array('default')) ? ' disabled="disabled" ' : '' ?>
            />
            <?PHP $states = explode('_', $resource, 3); ?>
            <?PHP $state = $this->translate('Opus_Document_ServerState_Value_' . ucfirst($states[1]) ); ?>
            <?PHP $targetState = $this->translate('Opus_Document_ServerState_Value_' . ucfirst($states[2])); ?>
            <?= $this->translate('acl_resource_workflow_generic', array($state, $targetState)); ?>
            <?PHP if (isset($this->guestModules) && in_array($resource, $this->guestModules)) : ?>
                <span style="font-style: italic; color: gray; padding-left: 0.5em"><?= $this->translate('admin_access_checked_in_guest'); ?></span>
            <?PHP endif; ?>
          </li>
        <?php endforeach ?>
        </ul>

        <div class="form-item">
            <span class="form-submit-wrapper">
                <input type="submit" name="save_button" class="form-submit" value="<?= $this->translate('access_button_save') ?>" style="width: 100%"/>
            </span>
            <span class="form-submit-wrapper">
                <input type="submit" name="cancel_button" class="form-submit" value="<?= $this->translate('access_button_cancel') ?>" style="width: 100%"/>
            </span>
        </div>

        <input type="hidden" name="roleid" value="<?= $this->roleId ?>" />
    </form>
</div>