FROM mysql:5.6

RUN echo 'CREATE DATABASE IF NOT EXISTS opusdb DEFAULT CHARACTER SET = UTF8 DEFAULT COLLATE = UTF8_GENERAL_CI;' \
RUN echo 'GRANT ALL PRIVILEGES ON opusdb.* TO 'opus4admin'@'localhost' IDENTIFIED BY 'root';' \
RUN echo 'GRANT SELECT,INSERT,UPDATE,DELETE ON opusdb.* TO 'opus4'@'localhost' IDENTIFIED BY 'root';' \
RUN echo 'FLUSH PRIVILEGES;'

EXPOSE 3306