<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<?= $this->partial('docinfo.phtml', ['document' => $this->documentAdapter]) ?>

<div id="filebrowser">
    <div id="headline">
        <?= $this->translate('admin_filebrowser_headline') ?>
        <span><?= $this->document->getId() ?></span>
    </div>

    <div id="filelisting">
        <?php if (count($this->files) > 0) : ?>
            <form action="<?= $this->url(['module' => 'admin', 'controller' => 'filebrowser', 'action' => 'import'], null, true); ?>" method="POST">
                <div>
                    <table>
                        <tr>
                            <th></th>
                            <th><?= $this->translate('admin_filebrowser_filename') ?></th>
                            <th><?= $this->translate('admin_filebrowser_filesize') ?></th>
                        </tr>
                        <?php foreach ($this->files as $index => $file) : ?>
                            <?php $cssClass = $index % 2 ? 'even' : 'odd' ?>
                            <tr class="<?= $cssClass ?>">
                                <td><input type="checkbox" name="file[<?= $index ?>]" value="<?= $file['name'] ?>"/>
                                </td>
                                <td><?= htmlspecialchars($file['name']) ?></td>
                                <td><?= $file['size'] ?> MB</td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <input type="hidden" name="id" value="<?= $this->document->getId() ?>"/>
                <input type="submit" id="save" value="<?= $this->translate('admin_filebrowser_submit') ?>"/>
                <input type="submit" id="Cancel" name="Cancel"
                       value="<?= $this->translate('admin_filebrowser_cancel') ?>"/>
            </form>
        <?php else : ?>
            <form action="<?= $this->url(['module' => 'admin', 'controller' => 'filebrowser', 'action' => 'import'], null, true); ?>" method="POST">
            <?= $this->translate('admin_filebrowser_noFilesToSelect') ?>
                <div>
                    <input type="hidden" name="id" value="<?= $this->document->getId() ?>"/>
                    <input type="submit" name="Cancel" id="Cancel"
                           value="<?= $this->translate('admin_filebrowser_cancel') ?>"/>
                </div>
            </form>
        <?php endif ?>
    </div>
</div>