<?php
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @package     Application - Module Review
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div class="adminContainer">

    <h2><?= $this->translate('review_accept_title')?>
        <span class="info">(<?= $this->documentCount ?> <?= $this->translate('review_accept_document_count') ?>)</span>
    </h2>

    <form action="<?= $this->actionUrl ?>" method="post" style="margin: 1em 2em">

        <div>
            <?PHP if (isset($this->error)) : ?>
            <div class="error"><?= $this->error ?></div>
            <?PHP endif; ?>
        </div>

        <div class="instruction">
        <?= $this->translate('review_referee_instruction') ?>
        </div>

        <table style="margin-left: 2em;">
            <tr>
                <td align="right"><?= $this->translate('review_person_firstname') ?>*:</td>
                <td><input type="text" name="firstname" value="<?= htmlspecialchars($this->firstName) ?>"/></td>
            </tr>
            <tr>
                <td align="right"><?= $this->translate('review_person_lastname') ?>*:</td>
                <td><input type="text" name="lastname" value="<?= htmlspecialchars($this->lastName) ?>"/></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" name="buttonBack" value="<?= $this->translate('review_button_back') ?>" />
                    <input type="submit" name="buttonAccept" value="<?= $this->translate('review_button_accept') ?>" />
                </td>
            </tr>
        </table>

        <h3><?= $this->translate('review_selected_documents_list') ?></h3>

        <ol style="margin-left: 2em">
        <?PHP foreach( $this->selected as $index => $docId ) : ?>
            <?PHP $document = new Review_Model_DocumentAdapter($this, $docId); ?>
            <li>
                <div class="title" style="font-weight: bold"><?= $document->getDocTitle() ?></div>
                <div class="authors">
                    <?PHP $authorsCount = count($document->getAuthors()) - 1; ?>
                    <?PHP foreach($document->getAuthors() as $count => $author) : ?>
                        <?= $author ?>
                        <?= ($count < $authorsCount) ? ';' : ''?>
                    <?PHP endforeach; ?>
                </div>
                <input type="hidden" name="selected[]" value="<?= $document->getDocId() ?>" />
            </li>
        <?PHP endforeach; ?>
        </ol>

    </form>

</div>
