<?PHP

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<h2><?= $this->translate($this->title) ?>
    <span class="info">(<?= $this->documentCount ?> <?= $this->translate('review_selected_document_count') ?>)</span>
</h2>

<form action="<?= $this->actionUrl ?>" method="post" style="margin: 1em 2em">

    <div>
        <?PHP if (isset($this->error)) : ?>
        <div class="error"><?= $this->error ?></div>
        <?PHP endif; ?>
    </div>

    <div class="instruction">
        <?= $this->translate($this->instruction) ?>
    </div>

    <table style="margin-left: 2em;">
        <tr>
            <td>&nbsp;</td>
            <td>
                <input type="submit" name="sureyes" value="<?= $this->translate('answer_yes') ?>" />
                <input type="submit" name="sureno" value="<?= $this->translate('answer_no') ?>" />
            </td>
        </tr>
    </table>

    <h3><?= $this->translate('review_selected_documents_list') ?></h3>

    <table style="margin-left: 2em">
    <?PHP foreach ($this->selected as $index => $docId) : ?>
        <tr>
        <?PHP $document = new Application_Util_DocumentAdapter($this, $docId); ?>
        <td style="vertical-align: top; padding-right: 1em"><?= $docId ?></td>
        <td>
            <div class="title" style="font-weight: bold"><?= htmlspecialchars($document->getDocTitle()) ?></div>
            <div class="authors">
                <?PHP $authorsCount = count($document->getAuthors()) - 1; ?>
                <?PHP foreach ($document->getAuthors() as $count => $author) : ?>
                    <?= $author['name'] ?>
                    <?= $count < $authorsCount ? ';' : ''?>
                <?PHP endforeach; ?>
            </div>
            <input type="hidden" name="selected[]" value="<?= $document->getDocId() ?>" />
        </td>
        </tr>
    <?PHP endforeach; ?>
    </table>

</form>
