<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

use Opus\Common\Security\Realm;

?>

<?PHP $suffix = ' <span class="info">(' . $this->documentCount . ' '
        . $this->translate('review_docs_found_short') . ')</span>' ?>

<?PHP if (true === Realm::getInstance()->check('administrate')) : ?>
    <?= $this->navigation()->breadcrumbs()->setSuffix($suffix)->setSuffixSeparatorDisabled(true) ?>
<?PHP else : ?>
    <?= $this->navigation()->breadcrumbs()->setReplacement($this->translate('review_index_title') . $suffix) ?>
<?PHP endif; ?>

<div class="wrapper">

<?PHP if (isset($this->error)) : ?>
<div class="error">
    <?= htmlspecialchars($this->error) ?>
</div>
<?PHP endif; ?>

<form action="<?= $this->actionUrl ?>" method="post">

<div style="text-align: center">
    <?= $this->translate('review_sort_label') ?>:
    <select name="sort_order">
        <?PHP foreach ($this->sortOptions as $value => $label) : ?>
        <option value="<?= $value ?>" <?= $value === $this->sort_order ? 'selected' : '' ?>><?= $label ?></option>
        <?PHP endforeach; ?>
    </select>

    <input type="hidden" name="sort_reverse" value="<?= htmlspecialchars($this->sort_reverse) ?>" />
    <input type="submit" name="buttonUp" value="<?= $this->translate('review_sort_up') ?>" />
    <input type="submit" name="buttonDown" value="<?= $this->translate('review_sort_down') ?>" />
</div>

<?PHP echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>

<table class="documents">
<?PHP $index = 0; foreach ($this->paginator as $docId) : ?>
    <?PHP $document = new Application_Util_DocumentAdapter($this, $docId); ?>
    <tr class="<?= $index++ % 2 ? 'even' : 'odd' ?>">
        <td><input type="checkbox" name="selected[]" value="<?= $document->getDocId()?>"
                <?= ! $this->selectNone && ($this->selectAll || in_array($document->getDocId(), $this->selected)) ? 'checked' : '' ?> /></td>
        <td class="id"><?= $document->getDocId() ?></td>
        <td>
            <div class="title">
                <a href="<?= $this->documentUrl()->frontdoor($docId) ?>" target="_blank" class="new-window"><?= htmlspecialchars($document->getDocTitle()) ?></a>
                (<span class="pubDate"><?= $document->getYear() ?></span>)
            </div>
            <div class="authors">
            <?PHP $authorsCount = count($document->getAuthors()) - 1; ?>
            <?PHP foreach ($document->getAuthors() as $count => $author) : ?>
                <?= $author['name'] ?>
                <?= $count < $authorsCount ? ';' : ''?>
            <?PHP endforeach; ?>
            </div>

            <?php if (count($document->getSubmitter()) > 0 || count($document->getReviewer()) > 0) : ?>
            <div class="accounts">

                <?php if (count($document->getSubmitter()) > 0) : ?>
                <i>submitter: </i>
                    <?php foreach ($document->getSubmitter() as $accountId => $username) : ?>
                        <?php $accountText = htmlspecialchars("$username") ?>
                    <a title="submitter <?= $accountText ?>" href="<?= $this->url(['module' => 'admin', 'controller' => 'account', 'action' => 'show', 'id' => $accountId]) ?>"><?= $accountText ?></a>
                    <?php endforeach; ?>
                    <?php if (count($document->getReviewer()) > 0) :
                        ?>;<?php
                    endif; ?>
                <?php endif; ?>


                <?php if (count($document->getReviewer()) > 0) : ?>

                <i>reviewer: </i>
                    <?php foreach ($document->getReviewer() as $accountId => $username) : ?>
                        <?php $accountText = htmlspecialchars("$username") ?>
                    <a title="reviewer <?= $accountText ?>" href="<?= $this->url(['module' => 'admin', 'controller' => 'account', 'action' => 'show', 'id' => $accountId]) ?>"><?= $accountText ?></a>
                    <?php endforeach; ?>
                <?php endif; ?>

            </div>
            <?php endif; ?>
        </td>
        <td>
            <span class="doctype"><?= $document->getDocType() ?></span>
        </td>
    </tr>
<?PHP endforeach; ?>
</table>

<?PHP echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>

    <div>
        <input type="submit" name="buttonSelectAll" value="<?= $this->translate('review_select_all') ?>" />
        <input type="submit" name="buttonSelectNone" value="<?= $this->translate('review_select_none') ?>" />
    </div>

    <div style="text-align: right">
        <input type="submit" name="buttonSubmit" value="<?= $this->translate('review_accept_selected') ?>" style="margin-right: 1em"/>
        <input type="submit" name="buttonReject" value="<?= $this->translate('review_reject_selected') ?>" />
    </div>

    </form>

</div>

