<?php
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @package     Application - Module Review
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<h1><?= $this->translate('review_index_title')?> 
    <span class="info">(<?= $this->documentCount ?>
        <?= $this->translate('review_docs_found_short') ?>)</span></h1>

<div class="reviewContainer">

    <?PHP if (isset($this->error)) : ?>
    <div class="error">
        <?= htmlspecialchars($this->error) ?>
    </div>

    <?PHP endif; ?>

    <form action="<?= $this->actionUrl ?>" method="post">

    <div style="text-align: center">
        <?= $this->translate('review_sort_label') ?>:
        <select name="sort_order">
            <?PHP foreach ($this->sortOptions as $value => $label) : ?>
            <option value="<?= $value ?>" <?= ($value == $this->sort_order) ? 'selected' : '' ?>><?= $label ?></option>
            <?PHP endforeach; ?>
        </select>

        <input type="submit" name="buttonUp" value="<?= $this->translate('review_sort_up') ?>" />
        <input type="submit" name="buttonDown" value="<?= $this->translate('review_sort_down') ?>" />
    </div>


<?PHP echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>

<table class="result">
<?PHP $index = 0; foreach ($this->paginator as $docId) : ?>
    <?PHP $document = new Review_Model_DocumentAdapter($this, $docId); ?>
    <tr class="<?= ($index++ % 2) ? 'even' : 'odd' ?>">
        <td><input type="checkbox" name="selected[]" value="<?= $document->getDocId()?>"
                <?= ((in_array($document->getDocId(), $this->selected) || $this->selectAll) && !$this->selectNone)  ? 'checked' : '' ?> /></td>
        <td class="index"><?= $document->getDocId() ?>.</td>
        <td>
            <div class="title">
                <a href="<?= $document->getUrlFrontdoor() ?>" target="_blank">
                    <?= $document->getDocTitle() ?>
                </a>
                (<span class="doctype"><?= $document->getDocType() ?></span>,
                <span class="pubDate"><?= $document->getPublishedDate() ?></span>)
            </div>
            <div class="authors">
            <?PHP $authorsCount = count($document->getAuthors()) - 1; ?>
            <?PHP foreach($document->getAuthors() as $count => $author) : ?>
                <?= $author ?>
                <?= ($count < $authorsCount) ? ';' : ''?>
            <?PHP endforeach; ?>
            </div>
        </td>
    </tr>
<?PHP endforeach; ?>
</table>

<?PHP echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>

    <div>
        <input type="submit" name="buttonSelectAll" value="<?= $this->translate('review_select_all') ?>" />
        <input type="submit" name="buttonSelectNone" value="<?= $this->translate('review_select_none') ?>" />
    </div>

    <div style="text-align: right">
        <input type="submit" name="buttonSubmit" value="<?= $this->translate('review_clear_selected') ?>" />
    </div>

    </form>

</div>

