<?php
?>
<h1><?= $this-> translate('frontdoor_pagetitle') ?></h1><hr />
<h2><?= $this-> translate('frontdoor_hashtitle') ?></h2>
<p><b><?= $this->title;?></b></p>
<p><?= $this-> translate('frontdoor_filenumber')?>: <?= $this->filenumber?></p><br />
<? if ($this->first_hash !== NULL)
   {?>

     <p><b>Typ: </b> <?= $this->hash0_type?></p>
     <p><b>Wert: </b> <?= $this->hash0?></p><br />
     <p><b>Typ: </b> <?= $this->hash1_type?></p>
     <p><b>Wert: </b> <?= $this->hash1?></p><br />


 <?}
   else
   {?>
      <p><?$this-> translate('frontdoor_hash_existence');?></p><?
   }?>






