<?php
?>
<h1><?= $this-> translate('frontdoor_pagetitle') ?></h1><hr />
<h2><?= $this-> translate('frontdoor_hashtitle') ?></h2><?

if ($this->author !== null)
{?>
   <p><b><a href="<?= $this->value = $this->url(array(
                                'module' => 'search',
                                'controller' => 'search',
                                'action' => 'metadatasearch',
                                'author' => $this->author,
                            ), null, true);
                        ?>">
     <?= $this->author?></a>:&nbsp;<?= $this->title;?></b></p><?
}
else
{?>
   <p><b>&nbsp;<?= $this->title;?></b></p><?
}?>
<p><?= $this-> translate('frontdoor_filenumber')?>:&nbsp;<?= $this->fileNumber?></p><hr /><?
if ($this->fileNumber !== 0)
{
  if ($this->first_hash !== NULL)
  {
      for ($i = 0; $i < $this->fileNumber; $i++)
         if (array_key_exists ($i, $this->hashLabel) === true)
         {
            $file = $this->hashLabel[$i];
            $hashes = $this->document->getFile($i)->getHashValue();
            $f = $this->document->getFile($i);
            $hashNumber = count($hashes);
            for ($j = 0; $j < $hashNumber; $j++)
            {
               if (array_key_exists ('hashType_' .$i. '_' .$j, $this->hashValueType) === true)
               {
                  $hashtype = $this->hashValueType['hashType_' .$i. '_' .$j];
                  $this->signtype = $signtype = substr($hashtype, 0,3);
                  if ($signtype == 'gpg')
                  {?>
                     <p><b><?= $this->translate('SignatureValue');?> (<?= $this->file = $file?>)</b></p>
                     <p><?= $this->signtype?>:</p><?
                  }
                  else
                  {
                     $value = $this->hashValueType['hashValue_' .$i. '_' .$j];?>
                     <p><b><?= $this->translate ('HashValue')?>&nbsp;(<?= $this->file = $file?>)</b></p>
                     <p><?= $this->translate ('HashValue')?>&nbsp;
                     <?= $this->hashtype = $hashtype?>&nbsp;
                     <?= $this->translate('frontdoor_fixpoint')?>:&nbsp;
                     <?= $this->value = $value?></p>
                     <p><?= $this->translate ('HashValue')?>&nbsp;
                     <?= $this->hashtype = $hashtype?>&nbsp;
                     <?= $this->translate('frontdoor_current')?>:&nbsp;
                     <?php if ($f->canVerify() === true) { ?>
                         <?= $f->getRealHash($hashtype)?></p><?
                     }
                     else { ?>
                     	<?= $this->translate('frontdoor_file_too_big')?>
                     <?php }
                  }
               }
               else
               {?>
                  <p><b><?= $this->translate('frontdoor_no_hash')?></b></p>
             <?}
            }?> <hr /><?
       }
  }
  else
  {?>
      <p><?= $this->translate('frontdoor_no_hash');?></p><?
  }
}
else
{?>
    <p><?= $this->translate('frontdoor_no_file');?></p><?
}?>
<p><a href="<?= $this->value =
   $this->url(array(
   'module' => 'frontdoor',
   'controller' => 'index',
   'docId' => $this->docId,
   ), null, true);?>"><?= $this->translate('frontdoor_back')?></a>
