<?PHP
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2012, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<?PHP
    $document = $this->element->getDocument();
?>

<?PHP if (!is_null($document)) : ?>
<div id="actionboxContainer">
  <div class="wrapper">
      <div class="col col-1">
        <dl id="Document-ServerState">
          <dt id="Document-ServerState"><?= htmlspecialchars($this->translate('ServerState')) ?></dt>
          <dd id="Document-ServerState"><?= htmlspecialchars($this->translate('Opus_Document_ServerState_Value_' . ucfirst($document->getServerState()))) ?></dd>
        </dl>
      </div>
      <div class="col col-2">
        <dl id="Document-ServerDatePublished" class="col">
          <dt><?= $this->translate('ServerDatePublished') ?></dt>
          <dd id="Document-ServerDatePublished"><?= $this->formatValue()->formatDate($document->getServerDatePublished()) ?></dd>
        </dl>
        <dl id="Document-ServerDateModified" class="col">
          <dt><?= $this->translate('ServerDateModified') ?></dt>
          <dd id="Document-ServerDateModified"><?= $this->formatValue()->formatDate($document->getServerDateModified()) ?></dd>
        </dl>
        <dl id="Document-Goto" class="col dropdown">
          <dt><a>Gehe zu Abschnitt</a></dt>
          <dd>
            <ul>
              <li><a href="#fieldset-General">Allgemeines</a></li>
              <li><a href="#fieldset-Persons">Personen</a></li>
              <li><a href="#fieldset-Titles">Titles</a></li>
              <li><a href="#fieldset-Series">Schriftenreihe</a></li>
              <li><a href="#fieldset-Enrichments">Erweiterung</a></li>
              <li><a href="#fieldset-Collections">Collection</a></li>
              <li><a href="#fieldset-Identifiers">Identifier</a></li>
              <li><a href="#fieldset-Licences">Lizenzen</a></li>
              <li><a href="#fieldset-Patents">Patentinformationen</a></li>
              <li><a href="#fieldset-Notes">Bemerkung</a></li>
            </ul>
          </dd>
        </dl>
      </div>
      <div class="col col-3">
        <ul class="Document-Action">
          <li class="save-element">
            <input type="submit" name="Document[save]" class="Document-save" value="Speichern" />
          </li>
          <!--
        <li class="saveAndContinue-element">
          <input type="submit" name="Document[saveAndContinue]" class="Document-saveAndContinue" value="saveAndContinue" />
        </li>
        -->
          <li class="cancel-element"> oder
            <input type="submit" name="Document[cancel]" class="Document-cancel" value="Abbrechen" />
          </li>
        </ul>
      </div>
  </div>
</div>
<?PHP else : ?>
<?PHP Zend_Registry::get('Zend_Log')->err('Use of partial \'docstatus.phtml\' without document = null.'); ?>
<? endif; ?>

