<?PHP
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2012, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */

/**
 * This script is used to render the ActionBox with important functions for administrators.
 *
 * The box is used in the Frontdoor and in the Administration when looking at a document.
 * When editing a document the box is used as a static header with some key information and
 * buttons for saving or cancelling the editing.
 *
 * If Javascript is enabled the box will remain at the top of the window even when scrolling
 * further down the page to make the functions always easily available to an administrator.
 */
?>

<?PHP
    $document = $this->element->getDocument();
    $currentState = $document->getServerState();
    $stateLinks = $this->element->getStateLinks();
    $actionLinks = $this->element->getViewActionLinks();
?>

<?PHP if (!is_null($document)) : ?>
<div id="actionboxContainer">
  <div class="wrapper">
      <div class="col col-1">
        <?PHP if (!$this->element->isViewModeEnabled() || count($stateLinks) == 0) : ?>
        <dl id="Document-ServerState">
          <dt id="Document-ServerState-label"><?= htmlspecialchars($this->translate('ServerState-short')) . ':'?></dt>
          <dd id="Document-ServerState-value"><?= htmlspecialchars($this->translate('Opus_Document_ServerState_Value_'
                  . ucfirst($currentState))) ?></dd>
        </dl>
        <?PHP else : ?>
          <dl id="Document-ServerState" class="dropdown">
              <dt><a><?= htmlspecialchars($this->translate('ServerState-short')) . ':'?></a></dt>
              <dd>
                <ul>
                    <li class="active"><?= htmlspecialchars($this->translate('Opus_Document_ServerState_Value_'
                            . ucfirst($currentState))) ?></li>
                    <?PHP foreach ($stateLinks as $targetState => $params) : ?>
                    <li><a id="State-Link-<?= $targetState ?>" href="<?= $this->url($params) ?>"
                            ><?= htmlspecialchars($this->translate('admin_workflow_' . $targetState)) ?></a></li>
                    <?PHP endforeach; ?>
                </ul>
              </dd>
          </dl>
        <?PHP endif; ?>
      </div>
      <div class="col col-2">
        <dl id="Document-ServerDatePublished" class="col">
          <dt><?= $this->translate('ServerDatePublished-short') . ':'?></dt>
          <dd id="Document-ServerDatePublished-value"
              ><?= $this->formatDate()->formatOpusDate($document->getServerDatePublished(), false) ?></dd>
        </dl>
        <dl id="Document-ServerDateModified" class="col">
          <dt><?= $this->translate('ServerDateModified-short') . ':'?></dt>
          <dd id="Document-ServerDateModified-value"
              ><?= $this->formatDate()->formatOpusDate($document->getServerDateModified(), true) ?></dd>
        </dl>
        <?PHP if ($this->element->isNavigationEnabled()) : ?>
        <dl id="Document-Goto" class="col dropdown">
          <dt><a><?= $this->translate('admin-actionbox-goto-section') ?></a></dt>
          <dd>
            <?= $this->linkList($this->element->getJumpLinks()) ?>
          </dd>
        </dl>
        <?PHP endif; ?>
      </div>
      <div class="col col-3">
        <ul class="form-action">
          <?PHP if (!$this->element->isViewModeEnabled()) : ?>
          <li class="save-element"><?= $this->element->getElement(Admin_Form_ActionBox::ELEMENT_SAVE) ?></li>
          <li class="cancel-element"><?= $this->element->getElement(Admin_Form_ActionBox::ELEMENT_CANCEL) ?></li>
          <?PHP else : ?>
          <?PHP foreach ($actionLinks as $action => $params) : ?>
          <li class="<?= $action ?>"><a href="<?= $this->url($params, null, true) ?>"
              ><?= htmlspecialchars($this->translate('admin_document_' .$action)) ?></a></li>
          <?PHP endforeach; ?>
          <?PHP endif; ?>
        </ul>
      </div>
  </div>
  <?PHP $message = $this->element->getMessage() ?>
  <?PHP if (!is_null($message)) : ?>
  <div class="messagesContainer">
    <div class="messages"><?= $this->escape($message) ?></div>
  </div>
  <?PHP endif; ?>
</div>
<?PHP else : ?>
<?PHP Zend_Registry::get('Zend_Log')->err('Use of partial \'actionbox.phtml\' without document.'); ?>
<?PHP endif; ?>

