<?PHP

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 *
 * TODO $this->navigation()->menu()->htmlify($page)
 */

?>

<?PHP $parent = $this->adminMenu()->getParent(); ?>

<?PHP if ($parent !== null) : ?>
<ul class="menu">
    <?PHP foreach ($parent->getPages() as $page) : ?>
        <?PHP if ($page->group !== 'hidden') : ?>
            <?PHP if ($this->adminMenu()->isRenderActive($page)) : ?>
                <li class="<?= $page->group ?> <?= $page->colclass ?>"
                    ><a href="<?= $page->getHref() ?>"><strong><?= $this->translate($page->label) ?></strong><br/>
                <?PHP if ($this->adminMenu()->isRenderDescription($page)) : ?>
                    <?= $this->translate($page->description) ?>
                <?PHP endif; ?></a></li>
            <?PHP else : ?>
                <li class="<?= $page->group ?> <?= $page->colclass ?> inactive"
                    ><strong><?= $this->translate($page->label) ?></strong></li>
            <?PHP endif; ?>
        <?PHP endif; ?>
    <?PHP endforeach; ?>
</ul>
<?PHP endif; ?>
