<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2009, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>
<p><?php echo $this->translate('admin_oailink_general');?></p>

<div class="code">
<b><?php echo $this->baseLink ?></b>
</div>

<p><?php echo $this->translate('admin_oailink_examples'); ?></p>
<ul>
    <li><a href="<?php echo $this->baseLink . '?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:' . $this->repIdentifier . ':78'?>"><?php echo $this->translate('admin_oailink_example_getrecord') . ' (oai_dc)';?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=GetRecord&metadataPrefix=oai_pp&identifier=oai:' . $this->repIdentifier . ':78'?>"><?php echo $this->translate('admin_oailink_example_getrecord') . ' (oai_pp)';?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=GetRecord&metadataPrefix=epicur&identifier=oai:' . $this->repIdentifier . ':78'?>"><?php echo $this->translate('admin_oailink_example_getrecord') . ' (EPICUR)';?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=GetRecord&metadataPrefix=XMetaDissPlus&identifier=oai:' . $this->repIdentifier . ':41'?>"><?php echo $this->translate('admin_oailink_example_getrecord') . ' (XMetaDissPlus)';?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=GetRecord&metadataPrefix=marc21&identifier=oai:' . $this->repIdentifier . ':41'?>"><?php echo $this->translate('admin_oailink_example_getrecord') . ' (MARC21)';?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=Identify'?>"><?php echo $this->translate('admin_oailink_example_identify');?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=ListIdentifiers&metadataPrefix=oai_dc'?>"><?php echo $this->translate('admin_oailink_example_listidentifiers');?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=ListMetadataFormats'?>"><?php echo $this->translate('admin_oailink_example_listmetadataformats');?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=ListRecords&metadataPrefix=oai_dc&from=2006-01-01'?>"><?php echo $this->translate('admin_oailink_example_listrecords_from');?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=ListRecords&metadataPrefix=oai_dc&set=ddc:62'?>"><?php echo $this->translate('admin_oailink_example_listrecords_set');?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=ListSets'?>"><?php echo $this->translate('admin_oailink_example_listsets');?></a></li>
    <li><a href="<?php echo $this->baseLink . '?verb=ListRecords&metadataPrefix=oai_dc&set=openaire'?>"><?php echo $this->translate('admin_oailink_example_open_aire');?></a></li>
</ul>