Dear Referee,
you are asked by {$submitterString} to approve the preprint


Title:
{$titleString}

Abstract:
{$abstractString}

on the Matheon preprint server at http://vs24.kobv.de/opus4-matheon/.


In order to start the release process, please FIRST log in with your default
webbrowser on the website:
    http://vs24.kobv.de/opus4-matheon/auth/login/

You find an overview of the preprints which you are asked to release:
    http://vs24.kobv.de/opus4-matheon/review

You can check the document information and the preprint files:
    http://vs24.kobv.de/opus4-matheon/frontdoor/index/index/docId/{$docId}

In addition you can also directly read the preprint:
{$filesString}

and accepting:
    http://vs24.kobv.de/opus4-matheon/review/index/reject?accept[]={$docId}

or reject it:
    http://vs24.kobv.de/opus4-matheon/review/index/reject?selected[]={$docId}


Thank you for your efforts!

The Preprint webmaster.


Note: This is an autogenerated mail. Please do not reply.
For response and suggestions use webmaster@matheon.de