#!/bin/bash

# Abhängigkeiten für Validierung der Frontdoor
wget 'http://www.w3.org/MarkUp/DTD/xhtml-datatypes-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-metaAttributes-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-inlstyle-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-rdfa-model-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-framework-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-text-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-hypertext-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-list-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-edit-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-bdo-1.mod'
wget 'http://www.w3.org/TR/ruby/xhtml-ruby-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-pres-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-link-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-meta-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-base-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-script-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-style-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-image-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-csismap-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-ssismap-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-param-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-object-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-table-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-form-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-target-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-legacy-1.mod'
wget 'http://www.w3.org/MarkUp/DTD/xhtml-struct-1.mod'
