<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Solrsearch
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<?php if (!empty($this->parents)) : ?>
<div id="breadcrumb">
    <ul>        
        <?php foreach ($this->parents as $id => $parent) : ?>
            <?php
                $displayNameShortened = '';
                if ($id === 0) {
                    $displayNameShortened = $this->collectionRoleTitle;
                }
                else {
                    $displayNameShortened = $parent->getDisplayName();
                }
                if (strlen($displayNameShortened) > 50) {
                    $displayNameShortened = substr($displayNameShortened, 0, 50) . '...';
                }
                $displayNameShortened = htmlspecialchars($displayNameShortened);
            ?>
            <?php if ($id === 0) : ?>
                <li><a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $parent->getId()), null, true) ?>"><?= $displayNameShortened ?></a></li>
            <?php else : ?>
                <?php if ($parent->getVisible() === '1') : ?>
                    <li><a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $parent->getId()), null, true) ?>"><?= $displayNameShortened ?></a></li>
                <?php else : ?>
                    <li class="empty-collection"><?= $displayNameShortened ?></li>
                <?php endif ?>                
            <?php endif ?>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>

<h2><?= htmlspecialchars($this->title) ?></h2>

<div class="content">
    <ul class="nav browsing">
    <?php foreach ($this->children as $child) : ?>
        <?php $documentCount = $child->getNumSubtreeEntries(); ?>
            <?php if ($documentCount === 0) : ?>
                <li class="empty-collection"><?= htmlspecialchars($child->getDisplayName()) ?></li>
            <?php else: ?>
                <li>
                    <a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $child->getId()), null, true) ?>"><?= htmlspecialchars($child->getDisplayName()) ?></a>
                    (<?= $documentCount ?>)
                </li>
            <?php endif ?>
    <?php endforeach ?>
    </ul>
</div>