<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

use Opus\Common\Config;

?>

<?php if (! empty($this->parents)) : ?>
<div id="breadcrumb">
    <ul>
        <?php foreach ($this->parents as $id => $parent) : ?>
            <?php
                $displayNameShortened = '';
            if ($id === 0) {
                $displayNameShortened = $this->collectionRoleTitle;
            } else {
                $displayNameShortened = $parent->getDisplayNameForBrowsingContext($this->collectionRole);
            }
            if (strlen($displayNameShortened) > 50) {
                $displayNameShortened = substr($displayNameShortened, 0, 50) . '...';
            }
                $displayNameShortened = htmlspecialchars($displayNameShortened);
            ?>
            <?php if ($id === 0) : ?>
                <li><a href="<?= $this->url(['module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $parent->getId()], null, true) ?>"><?= $displayNameShortened ?></a></li>
            <?php else : ?>
                <?php if ($parent->getVisible()) : ?>
                    <li><a href="<?= $this->url(['module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $parent->getId()], null, true)?>"><?= $displayNameShortened ?></a></li>
                <?php else : ?>
                    <li class="empty-collection"><?= $displayNameShortened ?></li>
                <?php endif ?>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>

<h2><?= htmlspecialchars($this->title) ?></h2>

<?php
    $config                        = Config::get();
    $this->disableEmptyCollections = isset($config->browsing->disableEmptyCollections) &&
        filter_var($config->browsing->disableEmptyCollections, FILTER_VALIDATE_BOOLEAN);
    $collRoleName                  = htmlspecialchars($this->collectionRole->getName(), ENT_QUOTES);
?>

<div class="content">
    <ul class="nav browsing col-list role-<?= $collRoleName ?>">
    <?php foreach ($this->children as $child) : ?>
        <?php $documentCount = $child->getNumSubtreeEntries(); ?>
            <?php if ($documentCount === 0 && $this->disableEmptyCollections) : ?>
                <li class="empty-collection"><?=
                    htmlspecialchars($child->getDisplayNameForBrowsingContext($this->collectionRole)) ?>
            <?php else : ?>
                <li>
                    <a href="<?= $this->url(['module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $child->getId()], null, true) ?>"><?= htmlspecialchars($child->getDisplayNameForBrowsingContext($this->collectionRole)) ?></a>
                    (<?= $documentCount ?>)
            <?php endif ?>
                <a href="<?= $this->url(['module' => 'rss', 'controller' => 'index', 'action' => 'index', 'searchtype' => 'collection', 'id' => $child->getId()], null, true) ?>" class="rss" type="application/rss+xml">
                    <img src="<?= $this->layoutPath() ?>/img/feed_small.png" width="12" height="12"
                         alt="<?= $this->translate('rss_icon') ?>" title="<?= $this->translate('rss_title') ?>" />
                </a>
                </li>
    <?php endforeach ?>
    </ul>
</div>
