<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

/**
 * TODO What is "firstPage"?
 * TODO use view helpers to render components of interface (remove link, extender, etc.)
 */

?>

<?php
    $removeFilterQueryParams = $this->removeFilterQueryBase; // TODO refactor (explain it)
?>

<div id="facets" class="results_facets">
    <h3><?= $this->translate('facets_menu_title') ?></h3>
    <?php foreach ($this->facets as $key => $facet) : ?>
        <div id="<?= $key ?>_facet" class="facet">
            <?PHP
                $facetUrl                     = $this->firstPage; // TODO why do we use firstPage here and not something like baseUrl?
                $facetUrl["facetNumber_$key"] = 'all';
            ?>
            <h4><?= $this->translate($facet->getHeading()) ?> </h4>
            <ul>
                <?php foreach ($facet->getValues() as $facetItem) :
                    $fqUrl              = $this->firstPage;
                    $fqUrl[$key . 'fq'] = $facetItem->getText();
                    $facetValue         = htmlspecialchars($facet->getLabel($facetItem->getText()));
                    ?>
                    <?php if ($facet->isSelected()) : ?>
                        <?php if ($facet->getSelected() === strval($facetItem->getText())) :
                            // remove fq param from URL
                            unset($removeFilterQueryParams[$key . 'fq']);
                            $removeFqUrl = $this->url($removeFilterQueryParams, null, true);
                            ?>
                            <li class="activeFacet"><?= $facetValue ?>&nbsp;(<?= $facetItem->getCount() ?>)
                            <span class="removeFacetLink"
                                ><a href="<?= $removeFqUrl ?>" rel="nofollow"
                                >(<?= $this->translate('facets_remove') ?>)</a></span>
                            </li>
                        <?php endif ?>
                    <?php else : ?>
                        <li><a href="<?= $this->url($fqUrl) ?>" rel="nofollow"
                            ><?= $facetValue ?></a>&nbsp;(<?= $facetItem->getCount() ?>)</li>
                    <?php endif; ?>
                <?php endforeach ?>
            </ul>
            <?PHP if ($facet->isShowFacetExtender()) : ?>
                <?PHP if (! $facet->isOpen()) : ?>
                    <div class="facetValueExtender"><a href="<?= $this->url($facetUrl) . '#' . $key . '_facet' ?>"
                            title="<?= $this->translate('facets_more_title') ?>">
                            <?= $this->translate('facets_more_results') ?></a></div>
                <?PHP else : ?>
                    <?PHP $facetUrl['facetNumber_' . $key] = null; ?>
                    <div class="facetValueExtender"><a href="<?= $this->url($facetUrl) . '#' . $key . '_facet' ?>"
                            title="<?= $this->translate('facets_less_title') ?>">
                            <?= $this->translate('facets_less_results') ?></a></div>
                <?PHP endif ?>
            <?PHP endif ?>
        </div>
    <?php endforeach ?>
</div>
