<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Solrsearch
 * @author      Julian Heise <heise@zib.de>
 * @copyright   Copyright (c) 2008-2011, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div id="facets" class="results_facets">
    <h3><?= $this->translate('facets_menu_title') ?></h3>
    <?php foreach($this->facets as $key => $facet) : ?>
        <div id="<?= $key ?>_facet" class="facet">
            <h4><?= $this->translate($key."_facet_heading") ?></h4>
            <ul>
                <?php foreach($facet as $facetItem) :
                    $fqUrl = $this->firstPage;
                    $fqUrl[$key.'fq'] = $facetItem->getText();
                    $fqLinkRel = count($this->selectedFacets) > 0 ? 'rel="noindex, nofollow"' : '';

                    $facetvalue_name = $facetItem->getText();
                    if ($key === 'has_fulltext' || $key === 'belongs_to_bibliography') {
                        $facetvalue_name = $this->translate('facetvalue_' . $key . '_' . $facetvalue_name);
                    }
                ?>
                    <?php if (array_key_exists($key, $this->selectedFacets)) : ?>
                        <?php if ($this->selectedFacets[$key] == $facetItem->getText()) :
                            // remove fq param from URL
                            $remove_fq_params = $this->removeFilterQueryBase;
                            unset($remove_fq_params[$key . 'fq']);
                            $remove_fqUrl = $this->url($remove_fq_params, null, true);
                        ?>
                            <li class="activeFacet"><?= $this->translate(htmlspecialchars($facetvalue_name)) ?> (<?= $facetItem->getCount() ?>)
                            <span class="removeFacetLink"><a href="<?= $remove_fqUrl ?>" <?= $fqLinkRel ?>>(<?= $this->translate('facets_remove') ?>)</a></span>
                            </li>
                        <?php endif ?>
                    <?php else: ?>
                        <li><a href="<?= $this->url($fqUrl) ?>" <?= $fqLinkRel ?>><?= $this->translate(htmlspecialchars($facetvalue_name)) ?></a> (<?= $facetItem->getCount() ?>)</li>
                    <? endif ?>
                <?php endforeach ?>
            </ul>
        </div>
    <?php endforeach ?>
</div>