<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Solrsearch
 * @author      Julian Heise <heise@zib.de>
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2017, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */
?>

<div class="results_pagination">

    <ul class="paginationControl">
        <li>
            <?PHP if ($this->start > 0) : ?>
            <a class="pagination-first" href="<?= $this->url($this->firstPage); ?>"
                title="<?= $this->translate('pagination_first_page') ?>">
            </a>
            <?PHP else : ?>
            <div class="pagination-first"></div>
            <?PHP endif ?>
        </li>

        <li>
            <?PHP if ($this->start > 0) : ?>
            <a class="pagination-prev" href="<?= $this->url($this->prevPage); ?>"
                title="<?= $this->translate('pagination_previous_page') ?>"></a>
                <?PHP else : ?>
                <div class="pagination-prev"></div>
            <?php endif ?>
        </li>

        <li>
            <strong><?= (int)($this->start)+1 ?></strong> <?= $this->translate('pagination_to') ?>
            <strong><?php if(((int)($this->start) + (int)($this->rows)) > $this->numOfHits) echo $this->numOfHits; else echo (int)($this->start) + (int)($this->rows); ?></strong>
        </li>

        <li>
            <?php if($this->start < ((int)($this->numOfHits) - (int)($this->rows))) : ?>
            <a class="pagination-next" href="<?= $this->url($this->nextPage); ?>"
                title="<?= $this->translate('pagination_next_page') ?>"></a>
                <?PHP else : ?>
                <div class="pagination-next"></div>
            <?PHP endif ?>
        </li>

        <li>
            <?php if($this->start < ((int)($this->numOfHits) - (int)($this->rows))) : ?>
            <a class="pagination-last" href="<?= $this->url($this->lastPage); ?>"
                title="<?= $this->translate('pagination_last_page') ?>"></a>
                <?PHP else : ?>
                <div class="pagination-last"></div>
            <?php endif ?>
        </li>
    </ul>
</div>
