<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<?php
if ($this->jQueryEnabled()) {
    $script = "$(function() { $('input[name=query]').focus(); });";
    $this->inlineScript()->appendScript($script);
    echo $this->inlineScript();
}
?>

<div class="form-wrapper">
    <form id="form-search" action="<?= $this->url(['module' => 'solrsearch', 'controller' => 'dispatch', 'action' => 'index'], null, true); ?>" method="post">
        <div id="fieldset-search" class="fieldset-wrapper">
            <fieldset>
                <div id="edit-search-wrapper" class="form-item">
                    <input type="text" size="30" name="query" id="edit-search" class="form-text" value="<?= $this->q !== null ? htmlspecialchars($this->q) : '' ?>" />
                </div>
                <div id="edit-submit-search-wrapper" class="form-item">
                    <span class="form-submit-wrapper"><input type="submit" id="edit-submit-search" class="form-submit" value="<?= $this->translate('solrsearch_searchaction'); ?>" /></span>
                </div>
            </fieldset>
            <p class="footer-link">
                <a class="link" href="<?= $this->url(['module' => 'solrsearch', 'controller' => 'index', 'action' => 'advanced'], null, true); ?>"><?= $this->translate('solrsearch_title_advanced'); ?></a>
                <?php
                    $searchAllDocsText = $this->translate('solrsearch_title_alldocs');
                if (isset($this->totalNumOfDocs)) {
                    $searchAllDocsText .= '&nbsp;(<span id="solrsearch-totalnumofdocs">' . $this->totalNumOfDocs . '</span>)';
                }
                ?>
                <a id="link-solrsearch-all-documents" class="link" href="<?= $this->url(['module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'all'], null, true); ?>"><?= $searchAllDocsText; ?></a>
                <a class="link" href="<?= $this->url(['module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'latest'], null, true); ?>"><?= $this->translate('solrsearch_title_latest'); ?></a>
                <a href="<?= $this->url(['module' => 'rss', 'controller' => 'index', 'action' => 'index'], null, true) ?>" class="rss" type="application/rss+xml">
                    <img src="<?= $this->layoutPath() ?>/img/feed_small.png" width="12" height="12" alt="<?= $this->translate('rss_icon') ?>" title="<?= $this->translate('rss_title') ?>" />
                </a>
            </p>

            <input type="hidden" name="searchtype" id="searchtype" value="simple" />
            <input type="hidden" name="start" id="start" value="0" />
            <input type="hidden" name="sortfield" id="sortfield" value="score" />
            <input type="hidden" name="sordorder" id="sortorder" value="desc" />
        </div>
    </form>
</div>
