<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<?PHP if ($this->enrichments !== null && ! empty($this->enrichments)) : ?>
<table id="<?= $this->managed ? 'enrichmentkeyTableManaged' : 'enrichmentkeyTableUnmanaged' ?>">
    <thead>
    <tr>
        <th>Name</th>
        <?PHP if ($this->managed) : ?>
            <th>Typ</th>
        <?PHP endif ?>
        <th colspan="4"></th>
    </tr>
    </thead>
    <tbody>
    <?PHP foreach ($this->enrichments as $enrichment) : ?>
        <tr class="<?= $this->element->getRowCssClass($enrichment)?>"
            title="<?= htmlspecialchars($this->translate($this->element->getRowTooltip($enrichment))) ?>">
            <td>
                <?PHP if ($enrichment->getId() === null) : ?>
                    <?= htmlspecialchars($enrichment->getDisplayName()) ?>
                <?PHP else : ?>
                    <span class="strong">
                    <?= htmlspecialchars($enrichment->getDisplayName()) ?>
                </span>
                    <?PHP if ($this->element->isProtected($enrichment)) : ?>
                        <i class="fa fa-lock"
                           title="<?= htmlspecialchars($this->translate('admin_enrichmentkey_protected_tooltip')); ?>"
                           aria-hidden="true"></i>
                    <?PHP endif ?>
                <?PHP endif ?>
            </td>
            <?PHP if ($this->managed) : ?>
                <td>
                    <?= htmlspecialchars($enrichment->getType()) ?>
                    <?PHP $optionsPrintable = $enrichment->getOptionsPrintable();
                    if ($optionsPrintable !== null) : ?>
                        <i title="<?= htmlspecialchars($optionsPrintable) ?>" class="fa fa-info-circle" aria-hidden="true"></i>
                    <?PHP endif ?>
                </td>
            <?PHP endif ?>
            <td class="edit">
                <?PHP if ($enrichment->getId() === null) : ?>
                    <a href="<?= $this->url(['action' => 'new', 'id' => $enrichment->getName()]) ?>"
                    ><?= $this->translate('admin_button_create'); ?></a>
                <?PHP elseif ($this->element->isModifiable($enrichment)) : ?>
                    <a href="<?= $this->url(['action' => 'edit', 'id' => $enrichment->getId()]) ?>"
                    ><?= $this->translate('admin_button_edit'); ?></a>
                <?PHP endif ?>
            </td>
            <td class="remove">
                <?PHP if ($enrichment->getId() === null) : ?>
                    <a href="<?= $this->url(['action' => 'removeFromDocs', 'id' => $enrichment->getName()]) ?>"
                    ><?= $this->translate('admin_button_remove_from_documents'); ?></a>
                <?PHP elseif ($this->element->isModifiable($enrichment) && $this->element->isUsed($enrichment)) : ?>
                    <a href="<?= $this->url(['action' => 'removeFromDocs', 'id' => $enrichment->getId()]) ?>"
                    ><?= $this->translate('admin_button_remove_from_documents'); ?></a>
                <?PHP endif ?>
            </td>
            <td>
                <?PHP if ($this->element->isModifiable($enrichment)) : ?>
                    <a href="<?= $this->url(['module' => 'setup', 'controller' => 'language', 'action' => 'index', 'search' => $enrichment->getName(), 'scope' => 'key']) ?>"><?= $this->translate('admin_button_translations'); ?></a>
                <?PHP endif ?>
            </td>
            <td class="remove">
                <?PHP if ($enrichment->getId() !== null && $this->element->isModifiable($enrichment)) : ?>
                    <a href="<?= $this->url(['action' => 'delete', 'id' => $enrichment->getId()]) ?>"
                    ><?= $this->translate('admin_button_remove'); ?></a>
                <?PHP endif ?>
            </td>
        </tr>
    <?PHP endforeach ?>
    </tbody>
</table>
<?PHP endif ?>
