<?php
/**
 * Index View for BrowsingController including links to several browsing lists and search functions
 *
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Search
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<h2><?= $this->translate('search_index_browsing') ?></h2>

<a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'latest'), null, true) ?>"><?= $this->translate('latest_documents_title') ?></a>&nbsp;
<a href="<?= $this->url(array('module' => 'browse', 'controller' => 'index', 'action' => 'latest', 'output' => 'rss'), null, true) ?>" class="rss"><img src="<?= $this->baseUrl; ?>/layouts/default/img/rss.gif" width="36" height="14" border="0" align="bottom" alt="RSS-Feed Icon" title="RSS-Feed abonnieren" /></a>
<br/>
<a href="<?= $this->url(array('module' => 'browse', 'controller' => 'index', 'action' => 'browseList', 'list' => 'doctypes'), null, true) ?>"><?= $this->translate('search_index_doctype_browsing') ?></a>
<br/>

<?php if (count($this->browsinglist) > 0) : ?>

   <?php foreach ($this->browsinglist as $obj) :
        $translatelabel = 'search_index_custom_browsing_' . $obj->getName();
        $printname = '';
        if ($translatelabel === $this->translate($translatelabel))
            $printname = $obj->getName();
        else
            $printname = $this->translate($translatelabel);
   ?>

    <a href="<?= $this->url(array('module' => 'browse', 'controller' => 'index', 'action' => 'browseList', 'list' => 'collection', 'collection' => $obj->getId()), null, true)?>">
        <?= htmlspecialchars($printname) ?>
    </a>
    <br/>
    <?php endforeach ?>
<?php endif ?>
