<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2020, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<?php $form = $this->element ?>
<?php $translation = $form->getTranslation() ?>

<h1><?= $this->translate($form->getLegend()) ?></h1>

<div class="message">
<?= $form->renderQuestion() ?>
</div>

<div class="key-info">
    <div class="key"><?= $form->getKey() ?></div>
    <div class="source"><?= $translation['module'] ?>
        <?php if (isset($translation['filename'])) : ?>
            (<span class="filename"><?= $translation['filename'] ?></span>)
        <?php endif ?>
    </div>
</div>

<div class="translation">
<?php if ($translation !== null) : ?>
    <?php foreach ($translation['translations'] as $lang => $value) : ?>
        <div>
            <div class="lang"><?= $lang ?></div>
            <div class="values">
                <div class="current" title="<?= $this->translate('setup_translation_tooltip_value_current') ?>">
                    <?= $value ?>
                </div>
            <?php if (isset($translation['translationsTmx'][$lang])) : ?>
                <div class="default" title="<?= $this->translate('setup_translation_tooltip_value_default') ?>">
                    <?= $translation['translationsTmx'][$lang] ?>
                </div>
            <?php endif ?>
            </div>
        </div>
    <?php endforeach ?>
<?php endif ?>
</div>

<div id="form-action">
    <?= $form->getElement(Application_Form_Confirmation::ELEMENT_MODEL_ID) ?>
    <ul class="form-action">
        <li class="save-element"><?= $form->getElement(Application_Form_Confirmation::ELEMENT_YES) ?></li>
        <li class="cancel-element"><?= $form->getElement(Application_Form_Confirmation::ELEMENT_NO) ?></li>
    </ul>
</div>
