<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<?php if (isset($this->messages)) : ?>
    <div class="messages">
        <?php foreach ($this->messages as $message) : ?>
            <div class="<?= $message['level'] ?>"><?= htmlspecialchars($this->translate($message['message'])) ?></div>
        <?php endforeach ?>
    </div>
<?php endif ?>

<div>
    <div><?= $this->form ?></div>
</div>

<?PHP $resultCount = count($this->translations) ?>

<table class="table-translations">
    <thead>
    <tr>
        <th class="key"><?= $this->translate('setup_language_key') ?> <span class="count">(<?= $resultCount ?>)</span><a
                    class="button" href="<?= $this->url(['action' => 'add']) ?>"><i class="fas fa-plus-circle"></i><?= $this->translate('default_add') ?></a></th>
        <th class="translation" colspan="3"><div class="translations">
            <div class="label"><?= $this->translate('setup_language_variant') ?></div>
            <div class="actions">
                <a class="button" href="<?= $this->url(['action' => 'export']) ?>"><i class="fas fa-file-export"></i><?= $this->translate('setup_translation_button_export') ?></a>
                <a class="button" href="<?= $this->url(['action' => 'import']) ?>"><i class="fas fa-file-import"></i><?= $this->translate('setup_translation_button_import') ?></a>
                <a class="button" href="<?= $this->url(['action' => 'deleteall']) ?>"><?= $this->translate('setup_translation_button_delete_all') ?></a>
                <a class="button" href="<?= $this->url(['action' => 'settings']) ?>"><i class="fas fa-cog"></i><?= $this->translate('setup_translation_button_settings') ?></a>
            </div>
            </div>
        </th>
    </tr>
    </thead>
    <?PHP
    $highlightTranslation = strcasecmp($this->searchScope ?? '', 'key') !== 0;
    $highlightKey         = strcasecmp($this->searchScope ?? '', 'text') !== 0;
    foreach ($this->translations as $row) :
        $key       = array_shift($row);
        $langCount = count($row['translations']);
        ?>
        <tbody class="<?= isset($row['translationsTmx']) ? 'edited' : (! isset($row['filename']) ? 'added' : '') ?>">
        <tr>
            <td rowspan="<?= $langCount ?>" class="key"
                ><?PHP if ($highlightKey) :
                    ?><?= $this->highlight($key, $this->searchTerm, '<span class="hilite">', '</span>')
?><?PHP
                 else :
                        ?><?= $key ?><?PHP
                 endif ?>
                <?php if (isset($row['module'])) : ?>
                <div class="module"><?= $row['module'] ?>
                    <?PHP if (isset($row['filename'])) : ?>
                    (<span class="filename"><?= $row['filename'] ?></span>)
                    <?PHP endif ?>
                </div>
                <?php endif ?>
            </td>
            <?PHP $index = 0 ?>
            <?PHP foreach ($row['translations'] as $language => $translation) : ?>
                <?PHP if ($index > 0) : ?>
        </tr>
        <tr class="lang-<?= $language?>">
                <?PHP endif ?>
            <td class="lang"><?= $language ?></td>
            <td class="value"><?PHP if ($highlightTranslation) :
                ?><?= $this->highlight(htmlspecialchars($translation), $this->searchTerm, '<span class="hilite">', '</span>')
?><?PHP
                              else :
                                    ?><?= htmlspecialchars($translation) ?><?PHP
                              endif ?></td>
                <?PHP if ($index === 0) : ?>
            <td rowspan="<?= $langCount ?>" class="actions">
                <div><a href="<?= $this->url(['action' => 'edit', 'key' => $key, 'search' => $this->searchTerm, 'sort' => $this->currentSortKey]) ?>"
                ><?= $this->translate('setup_language_edit') ?></a></div>
                    <?PHP if (isset($row['translationsTmx'])) : ?>
                <a href="<?= $this->url(['action' => 'delete', 'key' => $key, 'search' => $this->searchTerm, 'sort' => $this->currentSortKey]) ?>"
                ><?= $this->translate('setup_language_reset') ?></a>
                    <?PHP elseif (! isset($row['filename'])) : ?>
                <a href="<?= $this->url(['action' => 'delete', 'key' => $key, 'search' => $this->searchTerm, 'sort' => $this->currentSortKey]) ?>"
                ><?= $this->translate('setup_language_remove') ?></a>
                    <?PHP endif ?>
            </td>
                <?PHP endif ?>
                <?PHP $index++ ?>
            <?PHP endforeach ?>
        </tr>
        </tbody>
    <?PHP endforeach ?>
</table>
<?PHP if ($resultCount === 0) : ?>
    <div class="notranslationsfound">
        <?= $this->translate('setup_translation_non_found') ?>
    </div>
<?php endif ?>
