<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Setup
 * @author      Edouard Simon <edouard.simon@zib.de>
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2019, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */
?>

<?= $this->form ?>

<table class="table-translations">
    <thead>
    <tr>
        <?PHP foreach ($this->sortKeys as $sortKey) : ?>
            <th class="<?= $sortKey == $this->currentSortKey ? 'hilite' : '' ?>"><?= $this->translate('setup_language_' . $sortKey) ?></th>
        <?PHP endforeach ?>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <?PHP
//        $keyPos = array_flip($this->sortKeys);
    foreach ($this->translations as $row) :
        $writeable = ($row['directory'] == 'language_custom');
        $file = $row['module'] . DIRECTORY_SEPARATOR . $row['directory'] . DIRECTORY_SEPARATOR . $row['filename'];
        $key = array_shift($row);
        $langCount = count($row['translations']);
        ?>
        <tbody>
        <tr>
            <td rowspan="<?= $langCount ?>" class="key"><?= empty($this->searchTerm) ? $key : str_replace($this->searchTerm, '<span class="hilite">' . $this->searchTerm . '</span>', $key) ?></td>
            <td rowspan="<?= $langCount ?>" class="module"><?= $row['module'] ?><br /><span class="filename"><?= $row['filename'] ?></span></td>
            <?PHP $index = 0 ?>
            <?PHP foreach ($row['translations'] as $language => $translation) : ?>
                <?PHP if ($index > 0) : ?>
        </tr>
        <tr class="lang-<?= $language?>">
                <?PHP endif ?>
            <td class="lang"><?= $language ?></td>
            <td class="value"><?= empty($this->searchTerm) ? $translation : str_replace($this->searchTerm, '<span class="hilite">' . $this->searchTerm . '</span>', $translation) ?></td>
                <?PHP if ($index == 0) : ?>
            <td rowspan="<?= $langCount ?>">
                    <?PHP // TODO add module to parameters ?>
                <a href="<?= $this->url(['action' => 'edit', 'key' => $key, 'search' => $this->searchTerm, 'sort' => $this->currentSortKey]) ?>"
                ><?=$this->translate('setup_language_edit') ?></a>
            </td>
                <?PHP endif ?>
                <?PHP $index++ ?>
            <?PHP endforeach ?>
        </tr>
        </tbody>
    <?PHP endforeach ?>

</table>