<?php
/**
 * Indexview for actions with public keys and signature verification
 *
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2009, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */

// FIXME This page should not be displayed if no document has been selected
?>

<div class="adminContainer">

    <div class="breadcrumbsContainer">
        <?= $this->navigation()->breadcrumbs() ?>
    </div>

<a href="<?= $this->editUrl ?>"><?= $this->translate('admin_documents_edit'); ?></a>

<div style="padding: 1em; margin-left: 2em">
    <span class="label"><?= $this->translate('TitleMain') ?></span>
    <span class="value"><?= $this->document->getDocTitle() ?></span>
</div>

<div id="upload-form">
<?= $this->uploadform ?>
</div>

<?= $this->actionresult ?>

<div id="file-list">
<?PHP foreach ($this->fileHelpers as $file) : ?>
    <?PHP
        $fileName = $file->getFileName();
        $show_gpg = true;
    ?>
    <fieldset class="file">
    <legend class="filename"><?= $fileName ?></legend>

    <div class="file-actions">
        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'filemanager', 'action' => 'delete', 'fileId' => $file->getId()), null, false) ?>"
           ><?= $this->translate('admin_filemanager_delete') ?></a>
    </div>

    <?PHP foreach ($file->getHashes() as $hash) : ?>
        <?PHP $hashType = $hash->getHashType(); ?>
        <?PHP if (!empty($hashType)) : ?>
            <?PHP $signtype = $hash->getSignatureType(); ?>
            <?PHP if ($signtype == 'gpg') : ?>
                <?PHP if ($show_gpg === true) : ?>
                    <?PHP $show_gpg = false; // Show GPG-Signatures only once ?>
                    <p><b><?= $this->translate('SignatureValue'); ?> (<?= $fileName ?>)</b></p>
                    <p><?= $signtype ?>:
                    <?PHP
                        // Controller stores signature verification results in $this->verifyResult[$fileName]
                        $verification = $this->verifyResult[$fileName];
                    ?>
                    <?PHP if (count($verification) === 0) : ?>
                        <?= $this->translate('pkm_no_signature') ?>
                    <?php endif; ?>
                    <?PHP $sigindex = 0; ?>
                    <?PHP foreach($verification as $verifiedArray) : ?>
                        <?PHP foreach($verifiedArray as $index => $verificationResult) : ?>
                            <?PHP if ($index === 'result') : ?>
                                <?PHP foreach ($verificationResult as $verified) : ?>
                                    <?PHP if (false === is_object($verified)) : ?>
                                        <?= $verified ?><br/>
                                    <?PHP elseif ($verified->isValid() === true) : ?>
                                        <?= $this->translate('pkm_sigcheck_valid', $verified->getUserId()->getName()); ?>
                                    <?PHP else : ?>
                                        <?= $this->translate('pkm_sigcheck_invalid', $verified->getUserId()->getName()); ?>
                                    <?PHP endif; ?>
                                    <?PHP if (true === is_object($verified)) : // Show key used for signature ?>
                                        <a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'showkey', 'fingerprint' => $verified->getKeyFingerprint()), null, true) ?>"><?= $this->translate('pkm_show_signature_key') ?></a><br/>
                                    <?PHP endif; ?>
                                <?PHP endforeach; ?>
                            <?PHP else : ?>
                                <? $signaturelist->signatures[$sigindex] = $verificationResult; ?>
                                <a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'showsignature', 'signature' => $sigindex), null, true) ?>"><?= $this->translate('pkm_show_signature') ?></a><br/>
                                <? $sigindex++; ?>
                            <?PHP endif; ?>
                        <?PHP endforeach; ?>
                    <?PHP endforeach; ?>
                    </p>
                <?PHP endif; ?>
            <?PHP else : ?>
                <div><?= $this->translate('HashValue')?> - <?= $hash->getHashType() ?></div>
                <div>
                    <span class="label"><?= $this->translate('frontdoor_fixpoint')?>:</span>
                    <span class="value"><?= $hash->getSoll()?></span>
                </div>
                <div>
                    <span class="label"><?= $this->translate('frontdoor_current')?>:</span>
                    <span class="value" style="white-space: normal">
                    <?PHP if ($hash->getIst() != 0) : ?>
                        <?= $hash->getIst() ?>
                    <?PHP else : ?>
                        <?= $this->translate('frontdoor_file_too_big')?>
                    <?PHP endif; ?>
                    </span>
                </div>
            <?PHP endif; ?>
        <?PHP else : ?>
            <div><b><?= $this->translate('frontdoor_no_hash')?></b></div>
        <?PHP endif; ?>
    <?PHP endforeach; ?>
    <?PHP foreach ($file->getForms() as $fileForm) : ?>
        <?= $fileForm ?>
    <?PHP endforeach; ?>
    </fieldset>
<?PHP endforeach; ?>
</div>

</div>
