<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
<h1>Opus Application - <?=$this->translate('admin_title_collections') ?></h1>

<p>
<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'assign', 'document'=>$this->assign), null,
    true)?>">Collections</a>
&gt;&nbsp;<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'assign',
    'role'=>$this->role_id, 'copy'=>$this->copy, 'document'=>$this->assign), null, true)?>"><?=$this->role_name?></a>
<? foreach($this->breadcrumb as $path => $name) : ?>
&gt;&nbsp;<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
    'role'=>$this->role_id, 'path'=>$path, 'copy'=>$this->copy, 'assign'=>$this->assign), null, true)?>"><?=$name?></a>
<? endforeach; ?>
</p>

<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'documents', 'action'=>'edit',
'id'=>$this->assign), null, true)?>"><?=$this->translate('admin_collections_collection_assign_abort')?></a>

<table>
    <? foreach($this->subcollections as $path => $name) : ?>
    <tr>
        <? if (false === is_null($this->role_id)): ?>
        <td width="400">
            <a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'assign',
                'role'=>$this->role_id, 'path'=>$path, 'document'=>$this->assign), null, true)?>"><?=$name?></a>
        </td>
        <td>
            <form method="post" action="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'assign',
            'role' => $this->role_id, 'path' => $path, 'document'=>$this->assign), null, true)?>">
                <input type="submit" value="<?=$this->translate('admin_collections_collection_assign_here')?>" />
            </form>
        </td>
        <? else: ?>
        <td width="400">
            <a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'assign',
                'role'=>$this->role_id, 'role'=>$path, 'document'=>$this->assign), null, true)?>"><?=$name?></a>
        </td>
        <? endif ?>
    </tr>
    <? endforeach; ?>
</table>
