<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Ralf Claussnitzer (ralf.claussnitzer@slub-dresden.de)
 * @author      Felix Ostrowski (ostrowski@hbz-nrw.de)
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id: common.phtml 2807 2009-05-14 19:51:53Z ostrowski $
 */

/*
 * Configure headMeta helper with content type, language and encoding.
 */
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
    ->appendHttpEquiv('Content-Language', 'de-DE');

$this->headTitle('OPUS 4')
    ->headTitle($this->title)
    ->setSeparator(' | ');

$fc = Zend_Controller_Front::getInstance();
$basePath = $fc->getRequest()->getBasePath();
$this->headLink()
    ->appendStylesheet($basePath . '/layouts/opus34/css/opus.css');
?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?= $this->headMeta() ?>
    <?= $this->headTitle() ?>
    <?= $this->headLink() ?>
</head>
<body>
    <div id="container">
        <img src="<?= $basePath?>/layouts/opus34/img/OPUSlogo_200.gif" border ="0" width="200" />
        <div id="navigation1">
             <?= $this->menu('home') ?>
             <?= $this->languageSelector() ?>
        </div>
        <div id="navigation2">
            <?= $this->menu('primary') ?>
        </div>
        <div id="content">
            <?= $this->layout()->content ?>
        </div>
        <?php if (Zend_Registry::get('Zend_Translate')->isTranslated(Zend_Controller_Front::getInstance()->getRequest()->getPathInfo())) { ?>
        <div class="right">
            <?= Zend_Registry::get('Zend_Translate')->_(Zend_Controller_Front::getInstance()->getRequest()->getPathInfo())?>
        </div>
        <?php } ?>
        <div id="foot">
            Letzte &Auml;nderung: 08.03.10    (Mail to <a href="mailto:ub@uni-beispiel.de">OPUS 4</a>) |
            BSZ-BW Konstanz
        </div>
    </div>

        <?php
        /*
         * without profiling information

            $dbprofiler = Zend_Registry::get('db_adapter')->getProfiler();
            $config = Zend_Registry::get('Zend_Config');
            $profiler_show_queries = (bool) $config->db->params->showqueries;
            $profiler_max_queries = (int) $config->db->params->maxqueries;
            if ($dbprofiler->getEnabled() === true) :
        ?>
        <div class="debug dbprofiler" style="clear:both">
            <hr/>
            <h2>Profiling information</h2>
            <b>Total number of queries: </b><?= $dbprofiler->getTotalNumQueries() ?><br />
            <b>Total query time (s): </b><?= $dbprofiler->getTotalElapsedSecs() ?><br />
            <b>Current memory consumption: </b><?= memory_get_usage(true) ?><br />
            <b>Peak memory consumption: </b><?= memory_get_peak_usage(true) ?><br />
            <?php if ($profiler_show_queries === true and $profiler_query_profiles = $dbprofiler->getQueryProfiles()) : ?>
            <b>Queries:</b><br />
            <ul>
                <?php
                    for ($i=1; ($i < $profiler_max_queries) and ($i < count($profiler_query_profiles)); $i++) :
                ?>
                <li><pre><?= $profiler_query_profiles[$i]->getQuery() ?></pre></li>
            <?php endfor ?>
            <?php if ($i < count($profiler_query_profiles)) { echo "<li>...</li>"; } ?>
            </ul>
            <?php endif ?>
        </div>
        <?php endif ?>
       */
        ?>

</body>
</html>
