<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_PublicationList
 * @author      Gunar Maiwald <maiwald@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<?php $cellCounter=0 ?>
<?php if(!is_null($publication->getTitleParent())) : ?>
        <i><?= htmlspecialchars($publication->getTitleParent()) ?></i>
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!is_null($publication->getTitleSub())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        <?= htmlspecialchars($publication->getTitleSub()) ?>
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!count($publication->getEditors()) == 0) : ?>
        <?php $editorCounter=0 ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        <?php foreach($publication->getEditors() as $editor) :?>
                <?php $editorCounter++ ?>
                <?= htmlspecialchars($editor) ?>
                <?php if($editorCounter < count($publication->getEditors())) : ?>,<?php endif ?>
        <?php endforeach ?> (Ed.)
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!is_null($publication->getVolume())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        Vol. <?= htmlspecialchars($publication->getVolume()) ?>
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!is_null($publication->getIssue())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        <?= htmlspecialchars($publication->getIssue()) ?>
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!is_null($publication->getPageFirst())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        pp. <?= htmlspecialchars($publication->getPageFirst()) ?>
        <?php if(!is_null($publication->getPageLast())) : ?>
            - <?= htmlspecialchars($publication->getPageLast()) ?>
        <?php endif ?>
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!is_null($publication->getPublisherName())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        <?= htmlspecialchars($publication->getPublisherName()) ?>
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!is_null($publication->getPublisherPlace())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        <?= htmlspecialchars($publication->getPublisherPlace()) ?>
        <?php $cellCounter++ ?>
<?php endif ?>

<?php if(!is_null($publication->getNote())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        <?= htmlspecialchars($publication->getNote()) ?>
        <?php if(!is_null($publication->getCompletedYear())) : ?>
            in <?= htmlspecialchars($publication->getCompletedYear()) ?>
        <?php endif ?>
        <?php $cellCounter++ ?>
<?php endif ?>
            
<?php if(!is_null($publication->getPublishedYear())) : ?>
        <?= $cellCounter === 0 ? '' : ','; ?>
        <?= htmlspecialchars($publication->getPublishedYear()) ?>
        <?php $cellCounter++ ?>
<?php endif ?>
