<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_SolrSearch
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<?php if (!empty($this->parents)) : ?>
<div id="breadcrumb">
    <ul>        
        <?php
            $first = true;
            foreach ($this->parents as $parent) : 
        ?>
            <?php if ($first) :
                $first = false; ?>
                <li><a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $parent->getId()), null, true) ?>"><?= htmlspecialchars($this->collectionRoleTitle) ?></a>
            <?php else : ?>
                <li><a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $parent->getId()), null, true) ?>"><?= htmlspecialchars($parent->getCollection()->getDisplayName()) ?></a>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>

<h2><?= htmlspecialchars($this->title) ?></h2>

<div id="subnodes">
    <ul>
    <?php foreach ($this->subnodes as $subnode) : ?>
        <?php $documentCount = $subnode->getNumSubtreeEntries(); ?>
            <?php if ($documentCount === 0) : ?>
                <li><?= htmlspecialchars($subnode->getCollection()->getDisplayName()) ?></li>
            <?php else: ?>
                <li>
                    <a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $subnode->getId()), null, true) ?>"><?= htmlspecialchars($subnode->getCollection()->getDisplayName()) ?></a>
                    (<?= $documentCount ?>)
                </li>
            <?php endif ?>
    <?php endforeach ?>
    </ul>
</div>