<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_SolrSearch
 * @package     Opus_SolrSearch
 * @author      Julian Heise <heise@zib.de>
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<?php
    $startUpScript = '$(document).ready(function() { init_searchresults(); });';
    $fc = Zend_Controller_Front::getInstance();
    $basePath = $fc->getRequest()->getBasePath();
    $this->headScript()
        ->appendFile($basePath . '/layouts/opus4/js/jquery-1.4.2.min.js')
        ->appendScript($startUpScript);
?>


<div id="search_results" class="search_results">
    <!-- NaviBar -->
    <?php foreach($this->results as $result) :?>
	<a href="#<?= htmlspecialchars($result->getYear()) ?>"><b><?= htmlspecialchars($result->getYear()) ?></b></a> 
    <?php endforeach ?>
    <?php foreach($this->results as $result) :?>
        <div class="result_box"">
	<a name="<?= htmlspecialchars($result->getYear()) ?>"></a>
        <b> <?= htmlspecialchars($result->getYear()) ?> </b>
         <ul>
         <?php foreach($result->getPublicationList() as $publication) :?>
            <li>
                <?php if(!is_null($publication->getAuthors())) :?>
                    <?php foreach($publication->getAuthors() as $author) :?>
                        <?php if(!is_null($author->getUrl())) : ?>
                            <a href="<?= $this->url($author->getUrl(), null, true); ?>">
                            <?= htmlspecialchars($author->getFirstName()) ?>
                            <?= $author->getLastName() ?></a>
                        <?php endif ?>
                        <?php if(is_null($author->getUrl())) : ?>
                            <?= htmlspecialchars($author->getFirstName()) ?> <?= htmlspecialchars($author->getLastName()) ?>
                        <?php endif ?>
                    <?php endforeach ?>
                <?php endif ?>:
                <i><?= htmlspecialchars($publication->getTitle()) ?></i>
                 <?php if(!is_null($publication->getTitleParent())) : ?>
                    in: <?= htmlspecialchars($publication->getTitleParent()) ?>
                <?php endif ?>
                <?php if(strlen($publication->getEditorString())>0 ) : ?>
                    , <?= htmlspecialchars($publication->getEditorString()) ?> (Ed.)
                <?php endif ?>
                <?php if(!is_null($publication->getVolume())) : ?>
                    , Vol. <?= htmlspecialchars($publication->getVolume()) ?>
                <?php endif ?>
                <?php if(!is_null($publication->getIssue())) : ?>
                    , Issue <?= htmlspecialchars($publication->getIssue()) ?>
                <?php endif ?>
                <?php if(!is_null($publication->getPageFirst())) : ?>
                    , pp. <?= htmlspecialchars($publication->getPageFirst()) ?>
                <?php endif ?>
                <?php if(!is_null($publication->getPageLast())) : ?>
                    - <?= htmlspecialchars($publication->getPageLast()) ?>
                <?php endif ?>
                <?php if(!is_null($publication->getCompletedYear())) : ?>
                    , <?= htmlspecialchars($publication->getCompletedYear()) ?>
                <?php endif ?>
                <?php if(!is_null($publication->getBibtexUrl())) : ?>
                    <a href="<?= $this->url($publication->getBibtexUrl(), null, true); ?>">BibTeX</a>
                <?php endif ?>
	      <?php if(!is_null($publication->getRisUrl())) : ?>
                    <a href="<?= $this->url($publication->getRisUrl(), null, true); ?>">RIS</a>
                <?php endif ?>

            </li>
         <?php endforeach ?>
         </ul>
        </div>
     <?php endforeach ?>
</div>

