<?php
/**
 * View for the search result list
 *
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Import
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id: search.phtml 1948 2009-02-17 15:17:01Z claussnitzer $
 */
?>
<h1><?= $this->translate('import_modulename') ?></h1>
<?php
	echo $this->importmeldung;
	printf($this->translate("imported_documents") . "<br/>", $this->numberOfEntries);
?>
<ol>
<?php
	foreach ($this->importiere as $importentrymeldung)
	{
		print ('<li>' . $importentrymeldung->getTitleMain(0)->getValue() . '</li>');
	}
?>
</ol>
<?php
    printf($this->translate("notimported_documents") . "<br/>", $this->numberOfFailures);
?>
<ol>
<?php
	foreach ($this->importfehler as $importentryfehler)
	{
		print ('<li>' . $importentryfehler['message'] . ':' . str_replace('<', '&lt;', $importentryfehler['entry']) . '</li>');
	}
?>
</ol>