<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License 
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51 
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category   Application
 * @package    Module_Home
 * @author     Felix Ostrowski (ostrowski@hbz-nrw.de)
 * @copyright  Copyright (c) 2009, OPUS 4 development team
 * @license    http://www.gnu.org/licenses/gpl.html General Public License
 * @version    $Id$
 */
?>
<? $this->title = $this->translate('home_index_about_pagetitle') ?>
<h1><?= $this->translate('home_index_about_title') ?></h1>
<p class="col3head"><?= $this->translate('home_index_about_general') ?></p> 
<ul class="navigation"> 
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'about', 'content' => 'about_content_whatsthis'), null, true) ?>"><?= $this->translate('home_index_about_whatsthis') ?></a></li> 
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'about', 'content' => 'about_content_policies'), null, true) ?>"><?= $this->translate('home_index_about_policies') ?></a></li> 
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'about', 'content' => 'about_content_documentation'), null, true) ?>"><?= $this->translate('home_index_about_documentation') ?></a></li> 
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'about', 'content' => 'about_content_disclaimer'), null, true) ?>"><?= $this->translate('home_index_about_disclaimer') ?></a></li> 
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'about', 'content' => 'about_content_impress'), null, true) ?>"><?= $this->translate('home_index_about_impress') ?></a></li> 
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'about', 'content' => 'about_content_termsofuse'), null, true) ?>"><?= $this->translate('home_index_about_termsofuse') ?></a></li> 
</ul>
<?php
if ($this->content) {
?>
<div><?php
if (file_exists($this->getScriptPath('') . $this->translate($this->content)) === true) {
    readfile($this->getScriptPath('') . $this->translate($this->content));
}
else {
    echo $this->translate($this->content);
}
?></div>
<?php
}
?>