<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License 
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51 
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category   Application
 * @package    Module_Home
 * @author     Oliver Marahrens (o.marahrens@tu-harburg.de)
 * @author     Sascha Szott <szott@zib.de>
 * @copyright  Copyright (c) 2008-2010, OPUS 4 development team
 * @license    http://www.gnu.org/licenses/gpl.html General Public License
 * @version    $Id$
 */
?>

<? $this->title = $this->translate('help_index_pagetitle') ?>

<h1><?= $this->translate('help_index_title') ?></h1>

<?php if (isset($this->content)) : ?>
    <div>
        <h2><?= $this->translate($this->contenttitle) ?></h2>
        <div>
            <?= $this->content ?>
        </div>
    </div>
<?php else : ?>
    <div>
        <p class="col3head"><?= $this->translate('help_index_general') ?></p>
        <ul>
            <?php foreach (array('whatsthis', 'costs', 'searchtipps') as $content) : ?>
                <li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller' => 'index', 'action' => 'help', 'content' => $content), null, true) ?>"><?= $this->translate('help_title_' . $content) ?></a></li>
            <?php endforeach; ?>
        </ul>

        <p class="col3head"><?= $this->translate('help_index_authorhelp') ?></p>
        <ul>
            <?php foreach (array('diss', 'contact', 'free', 'publneeds', 'right', 'format', 'requirements', 'write', 'publicationprocess', 'preprint', 'workflowlibrary') as $content) : ?>
                <li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller' => 'index', 'action' => 'help', 'content' => $content), null, true) ?>"><?= $this->translate('help_title_' . $content) ?></a></li>
            <?php endforeach; ?>
        </ul>        

        <p class="col3head"><?= $this->translate('help_index_formfields') ?></p>
        <ul>
            <?php foreach (array('metadata', 'form_general', 'field_doctype') as $content) : ?>
                <li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller' => 'index', 'action' => 'help', 'content' => $content), null, true) ?>"><?= $this->translate('help_title_' . $content) ?></a></li>
            <?php endforeach; ?>
        </ul>

        <p class="col3head"><?= $this->translate('help_index_legal_title') ?></p>
        <ul>
            <?php foreach (array('legal_parallel', 'legal_oa', 'legal_license') as $content) : ?>
                <li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller' => 'index', 'action' => 'help', 'content' => $content), null, true) ?>"><?= $this->translate('help_title_' . $content) ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif ?>
