<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright  Copyright (c) 2008, OPUS 4 development team
 * @license    http://www.gnu.org/licenses/gpl.html General Public License
 */

/**
 * TODO pull out translation key generation (move to Home_Model_HelpFiles)
 * TODO refactor $helpFilesAvailable
 * TODO breadcrumbs ? at least the look ?
 */

?>

<?PHP $this->title = 'help_index_pagetitle' ?>

    <h2><?= $this->translate('help_index_title') ?> <?= $this->helpSetupLink() ?></h2>

<?php if (isset($this->content)) : ?>
    <h2><?= $this->translate($this->contenttitle) ?> <?= $this->faqEditLink($this->contentId) ?></h2>
    <div class="content">
        <div id="section-help" class="section help">
        <?= $this->content ?>
        </div>
    </div>
<?php else : ?>
    <div class="content">
        <div id="section-help" class="section help">

        <?php $helpEntries = $this->help->getHelpEntries(); ?>

        <?php foreach ($helpEntries as $section => $entries) : ?>
            <h3><?= $this->translate($section) ?> <?= $this->faqSectionEditLink($section) ?></h3>
            <ul class="nav help">
            <?php foreach ($entries as $entry) : ?>
                <li>
                <?php if (! $this->help->getSeparateViewEnabled()) : ?>
                    <?php if ($this->help->isContentAvailable($entry)) : ?>
                    <a href="#<?= $entry; ?>"><?= $this->translate('help_title_' . $entry) ?></a>
                    <?php else : ?>
                        <?= $this->translate('help_title_' . $entry) ?> <?= $this->faqEditLink($entry) ?>
                    <?php endif ?>
                <?php else : ?>
                    <?php if ($this->help->isContentAvailable($entry)) : ?>
                    <a href="<?= $this->url(['module' => 'home', 'controller' => 'index', 'action' => 'help', 'content' => $entry], null, true) ?>">
                        <?= $this->translate('help_title_' . $entry) ?>
                    </a>
                    <?php else : ?>
                        <?= $this->translate('help_title_' . $entry) ?> <?= $this->faqEditLink($entry) ?>
                    <?php endif ?>
                <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endforeach; ?>
        </div>

        <?php if (! $this->help->getSeparateViewEnabled()) : ?>
         <div class="section answers">
            <h2><?= $this->translate('help_index_answerstitle') ?></h2>
            <dl>
            <?php foreach ($helpEntries as $section => $entries) : ?>
                <?php foreach ($entries as $entry) : ?>
                    <dt id="<?= $entry ?>"><?= $this->translate("help_title_$entry") ?> <?= $this->faqEditLink($entry) ?></dt>
                    <dd>
                        <div><?= $this->help->getContent($entry) ?></div>
                        <p class="backlink"><a href="#section-help"><?= $this->translate('help_index_up') ?></a></p>
                    </dd>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </dl>
        </div>
        <?php endif ?>
    </div>
<?php endif ?>
