<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License 
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51 
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category   Application
 * @package    Module_Home
 * @author     Oliver Marahrens (o.marahrens@tu-harburg.de)
 * @copyright  Copyright (c) 2009, OPUS 4 development team
 * @license    http://www.gnu.org/licenses/gpl.html General Public License
 * @version    $Id: help.phtml 2159 2009-03-12 13:36:06Z claussnitzer $
 */
?>
<? $this->title = $this->translate('home_index_about_pagetitle') ?>
<h1><?= $this->translate('home_index_help_title') ?></h1>
<p class="col3head"><?= $this->translate('help_index_general') ?></p>
<ul>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'about_content_whatsthis', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('home_index_about_whatsthis') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_costs', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_costs') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_searchtipps', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_searchtipps') ?></a></li>
</ul>

<p class="col3head"><?= $this->translate('help_index_authorhelp') ?></p>
<ul>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_diss', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_diss') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'contact'), null, true) ?>"><?= $this->translate('help_index_contact') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_free', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_free') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_publneeds', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_publneeds') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_right', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_right') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_format', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_format') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_requirements', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_requirements') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_write', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_write') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_publicationprocess', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_publicationprocess') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_preprint', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_preprint') ?></a></li>
<li><a href="<?= $this->url(array('module' => $this->startmodule, 'controller'=>'index', 'action'=>'help', 'content' => 'help_content_workflowlibrary', 'position' => '#helpcontent'), null, true) ?>"><?= $this->translate('help_index_workflowlibrary') ?></a></li>
</ul>

<p class="col3head">Formularfelder</p>
<ul>
<li><a href="#3.1">Was sind Metadaten?</a></li>
<li><a href="#3.2">Allgemeine Hilfe zu den Formularen</a></li>
<li><a href="#3.3">Formularelement Verfügbarkeit</a></li>
<li><a href="#3.4">Formularelement Titel (Title)</a></li>
<li><a href="#3.5">Formularelement Verfasser (Creator)</a></li>
<li><a href="#3.6">Formularelement Urheber (Creator)</a></li>
<li><a href="#3.7">Formularelement Sonstige Beteiligte (Other Contributors)</a></li>
<li><a href="#3.8">Formularelement Schlagwörter (Subject)</a></li>
<li><a href="#3.9">Formularelement Freie Schlagwörter</a></li>
<li><a href="#3.10">Formularelement Klassifikation (Subject)</a></li>
<li><a href="#3.11">Formularelement Inhaltliche Beschreibung (Description)</a></li>
<li><a href="#3.12">Formularelement Schriftenreihe</a></li>
<li><a href="#3.13">Formularelement Hochschule bzw. Fakultät (Publisher)</a></li>
<li><a href="#3.14">Formularelement Hauptberichter (Advisor)</a></li>
<li><a href="#3.15">Formularelement Datum (Date)</a></li>
<li><a href="#3.16">Formularelement Dokumentart (Resource Type)</a></li>
<li><a href="#3.17">Formularelement Format (Format)</a></li>
<li><a href="#3.18">Formularelement ISBN</a></li>
<li><a href="#3.19">Formularelement Sprache (Language)</a></li>
<li><a href="#3.20">Formularelement Quelle (Source)</a></li>
<li><a href="#3.21">Formularelement Name der Dokumentdatei (Resource Identifier)</a></li>
<li><a href="#3.22">Formularelement Identifizierung</a></li>
<li><a href="#3.23">Formularelement Anzahl der Dateien, die übermittelt werden sollen</a></li>
<li><a href="#3.24">Formularelement G&uuml;ltigkeitsdauer</a></li>
</ul>

<p class="col3head">Rechtliches</p>
<ul>
<li><a href="#4.1">Was ist, wenn ich meine Publikation bei einem Verlag ver&ouml;ffentlichen lasse oder dies plane?</a></li>
<li><a href="#4.2">Wie gehen Verlage mit einer frei verfügbaren Online-Version der Arbeit um?</a></li>
<li><a href="#4.3">Wie sieht es mit Lizenzen für mein Werk aus?</a></li>
</ul>

<p class="col3head">MD5-Prüfsummen</p>
<ul>
<li><a href="#5.1">Wie berechnet man die Prüfsumme?</a></li>
<li><a href="#5.2">Was ist eine MD5-Prüfsumme?</a></li>
</ul>

<p class="col3head">PGP/GPG</p>
<ul>
<li><a href="#6.1">Was ist PGP/GPG?</a></li>
<li><a href="#6.2">Warum brauche ich einen PGP/GPG-Schlüssel für die Veröffentlichung?</a></li>
<li><a href="#6.3">Formularelement Schlüsselupload</a></li>
<li><a href="#6.4">Wie stelle ich Ihnen meinen Schl&uuml;ssel zur Verf&uuml;gung?</a></li>
<li><a href="#6.5">Was machen Sie mit meinem Schlüssel?</a></li>
<li><a href="#6.6">Wie signiere ich meine Dokumente digital?</a></li>
<li><a href="#6.7">Signaturerstellung mit PGP für Windows</a></li>
<li><a href="#6.8">Signaturerstellung mit GPG für Windows (über WinPT)</a></li>
<li><a href="#6.9">Erstellung einer digitalen Signatur mit GPG über Kommandozeile</a></li>
</ul>


<?php
if ($this->content) {
?>
<a name="helpcontent">&nbsp;</a><div><?php
if (file_exists($this->getScriptPath('') . $this->translate($this->content)) === true) {
    readfile($this->getScriptPath('') . $this->translate($this->content));
}
else {
    echo $this->translate($this->content);
}
?></div>
<?php
}
?>