<?php
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    View Script
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2018, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */
?>

<div>
    <p>
        <?= $this->translate('admin_report_doi_filter') ?>
    </p>
    <ul>
        <?php if (!is_null($this->filter)) : ?>
            <li><a href="<?= $this->url(array('filter' => null)) ?>"><?= $this->translate('admin_report_doi_filter_all') ?></a></li>
        <?php else: ?>
            <li><b><?= $this->translate('admin_report_doi_filter_all') ?></b></li>
        <?php endif; ?>
        <?php if ($this->filter != 'unregistered') : ?>
            <li><a href="<?= $this->url(array('filter' => 'unregistered')) ?>"><?= $this->translate('admin_report_doi_filter_unregistered') ?></a></li>
        <?php else: ?>
            <li><b><?= $this->translate('admin_report_doi_filter_unregistered') ?></b></li>
        <?php endif; ?>
        <?php if ($this->filter != 'registered') : ?>
            <li><a href="<?= $this->url(array('filter' => 'registered')) ?>"><?= $this->translate('admin_report_doi_filter_registered') ?></a></li>
        <?php else: ?>
            <li><b><?= $this->translate('admin_report_doi_filter_registered') ?></b></li>
        <?php endif; ?>
        <?php if ($this->filter != 'verified') : ?>
            <li><a href="<?= $this->url(array('filter' => 'verified')) ?>"><?= $this->translate('admin_report_doi_filter_verified') ?></a></li>
        <?php else: ?>
            <li><b><?= $this->translate('admin_report_doi_filter_verified') ?></b></li>
        <?php endif; ?>
    </ul>
</div>

<?php if (empty($this->docList)): ?>
    <i><?= $this->translate('admin_report_doi_nothing_found') ?></i>
<?php else: ?>
<div class="formElementInline">
<form action="<?= $this->url(array('op' => 'register')) ?>" method="POST">
    <input type="submit" <?= $this->numDoisForBulkRegistration > 0  ? '' : 'disabled' ?> value="<?= $this->translate('admin_report_doi_bulk_registration', $this->numDoisForBulkRegistration) ?>" />
</form>
<form action="<?= $this->url(array('op' => 'verify')) ?>" method="POST">
    <input type="submit" <?= $this->numDoisForBulkVerification > 0 ? '' : 'disabled' ?> value="<?= $this->translate('admin_report_doi_bulk_verification', $this->numDoisForBulkVerification) ?>" />
</form>
</div>
<table>
    <thead>
        <tr>
            <td><?= $this->translate('admin_report_doi_table_head_docId') ?></td>
            <td><?= $this->translate('admin_report_doi_table_head_doiValue') ?></td>
            <td><?= $this->translate('admin_report_doi_table_head_doiStatus') ?></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->docList as $doc) : ?>
        <tr>
            <td>
                <a href="<?=$this->documentUrl()->adminShow($doc->getDocId()) ?>" title="<?= $this->translate('admin_documents_tooltip_show') ?>"><?= $doc->getDocId() ?></a>
            </td>
            <td>
                <?= $doc->getDoi() ?>
            </td>
            <td class="registrationState">
                <span class="<?= $doc->getDoiStatus() ?>">
                    <?= is_null($doc->getDoiStatus()) ? $this->translate('admin_report_doi_unregistered') : $this->translate('admin_report_doi_' . $doc->getDoiStatus()) ?>
                </span>
            </td>
            <td>
                <?php if ($doc->getDoiStatus() == 'registered') : ?>
                    <form action="<?= $this->url(array('op' => 'verify', 'docId' => $doc->getDocId())) ?>" method="POST">
                        <input type="submit" value="<?= $this->translate('admin_report_doi_verify') ?>" />
                    </form>
                <?php elseif ($doc->getDoiStatus() == 'verified') : ?>
                    <form action="<?= $this->url(array('op' => 'verify', 'docId' => $doc->getDocId())) ?>" method="POST">
                        <input type="submit" value="<?= $this->translate('admin_report_doi_verify_again') ?>" />
                    </form>
                <?php elseif ($doc->isPublished() && is_null($doc->getDoiStatus())) : ?>
                    <form action="<?= $this->url(array('op' => 'register', 'docId' => $doc->getDocId())) ?>" method="POST">
                        <input type="submit" value="<?= $this->translate('admin_report_doi_register') ?>" />
                    </form>
                <?php elseif (!$doc->isPublished() && is_null($doc->getDoiStatus())) :  ?>
                    <i><?= $this->translate('admin_report_doi_unpublished_doc') ?></i>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>