<?php
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @package     Application - Module Review
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<?php if ($this->pageCount > 1): ?>
    <div class="paginationControl">

    <!-- First and previous page link -->
    <?php if (isset($this->previous)): ?>
        <a href="<?PHP echo $this->url(array('page' => $this->first)); ?>">
            &lt;&lt; <?= $this->translate('review_pagination_first') ?></a> |
        <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
            &lt; <?= $this->translate('review_pagination_prev') ?></a> |
      <?php else: ?>
        <span class="disabled">&lt;&lt; <?= $this->translate('review_pagination_first') ?></span> |
        <span class="disabled">&lt; <?= $this->translate('review_pagination_prev') ?></span> |
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <a href="<?php echo $this->url(array('page' => $page)); ?>">
                <?php echo $page; ?></a> |
          <?php else: ?>
            <span class="currentPage"><?php echo $page; ?></span> |
        <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next and last page link -->
    <?php if (isset($this->next)): ?>
        <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
            <?= $this->translate('review_pagination_next') ?> &gt;</a> |
        <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
            <?= $this->translate('review_pagination_last') ?> &gt;&gt;</a>
      <?php else: ?>
        <span class="disabled"><?= $this->translate('review_pagination_next') ?> &gt;</span> |
        <span class="disabled"><?= $this->translate('review_pagination_last') ?> &gt;&gt;</span>
    <?php endif; ?>
    </div>
<?php endif; ?>