<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<!--div class="collection_new Add-data">
    </a>
</div-->

<table class="collections">
    <thead>
        <tr>
            <th class="visible" colspan="2"><?= $this->translate('admin_documents_label_collection') ?>
                <a class="add" href="<?= $this->url(['module' => 'admin', 'controller' => 'collectionroles', 'action' => 'new']) ?>"
                   ><?= $this->translate('admin_button_add') ?></a></th>
            <th colspan="3">&nbsp;</th>
            <th colspan="1"><?= $this->translate('admin_collections_role_show_associated') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>     
    
<?php
    $translator = Application_Translate::getInstance();

foreach ($this->collectionRoles as $i => $collectionRole) :
    $translatelabel = 'default_collection_role_' . $collectionRole->getName();

    $printname = '';

    if ($translator->isTranslated($translatelabel)) {
        $printname = $this->translate($translatelabel);
    } else {
        $printname = $collectionRole->getName();
    }

    $translationInfoText = $this->translate('admin_collectionroles_translation_key') . ' ' . htmlspecialchars($translatelabel);
    ?>
<tr class="<?= $i % 2 === 0 ? 'even' : 'odd' ?>">
<th class="<?= $collectionRole->getVisible() ? 'visible' : 'invisible' ?>">
    <?php if ($collectionRole->getRootCollection() === null) : ?>
        <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collection', 'action' => 'show', 'role' => $collectionRole->getId()], null, true)?>" title="<?= $translationInfoText ?>"><?= htmlspecialchars($printname) ?></a>
    <?php else : ?>
        <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collection', 'action' => 'show', 'id' => $collectionRole->getRootCollection()->getId()], null, true)?>" title="<?= $translationInfoText ?>"><?= htmlspecialchars($printname) ?></a>
    <?php endif ?>
</th>
<td class="edit">
<a href="<?= $this->url(['module' => 'admin', 'controller' => 'collectionroles', 'action' => 'edit', 'roleid' => $collectionRole->getId()], null, true) ?>">
    <?= $this->translate('admin_button_edit') ?>
</a>
</td>
    <?php if ($collectionRole->getVisible()) : ?>
    <td class="hide visible">
        <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collectionroles', 'action' => 'hide', 'roleid' => $collectionRole->getId()], null, true) ?>">
        <?= $this->translate('admin_collections_role_hide') ?>
        </a>
    </td>
    <?php else : ?>
    <td class="hide invisible">
        <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collectionroles', 'action' => 'unhide', 'roleid' => $collectionRole->getId()], null, true) ?>">
        <?= $this->translate('admin_collections_role_unhide') ?>
        </a>
    </td>
    <?php endif ?>
<td class="move-up">
    <?php if ($i > 0) : ?>
            <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collectionroles', 'action' => 'move', 'roleid' => $collectionRole->getId(), 'pos' => $i], null, true) ?>">
            <?= $this->translate('admin_button_move_up') ?>
            </a>
    <?php endif ?>
</td>
<td class="move-down">
    <?php if ($i < count($this->collectionRoles) - 1) : ?>
            <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collectionroles', 'action' => 'move', 'roleid' => $collectionRole->getId(), 'pos' => $i + 2], null, true)?>">
            <?= $this->translate('admin_button_move_down') ?>
            </a>
    <?php endif ?>
</td>
<td class="linked">
    <?php if ($collectionRole->getRootCollection() !== null && count($collectionRole->getRootCollection()->getDocumentIds()) > 0) : ?>
            <a href="<?= $this->url(['module' => 'admin', 'controller' => 'documents', 'action' => 'index', 'collectionid' => $collectionRole->getRootCollection()->getId()], null, true) ?>">
            <?= $this->translate('admin_collections_role_show_associated') ?>
            </a>
    <?php else : ?>
            <span class="unavailable"><?= $this->translate('admin_collections_no_associated') ?></span>
    <?php endif ?>
</td>
<td class="remove">
    <?php
    $confirmKey = $collectionRole->getRootCollection() === null || ! $collectionRole->getRootCollection()->hasChildren() ? 'confirm_deletion_empty' : 'confirm_deletion'
    ?>
<a href="<?= $this->url(['module' => 'admin', 'controller' => 'collectionroles', 'action' => 'delete', 'roleid' => $collectionRole->getId()], null, true) ?>" onclick="return confirm('<?= $this->translate($confirmKey) ?>');">
    <?= $this->translate('admin_collections_role_delete') ?>
    </a>
    </td>
</tr>
<?php endforeach ?>
</table>