<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Julian Heise <heise@zib.de>
 * @author      Thoralf Klein <thoralf.klein@zib.de>
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2010-2011, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */

$config = Zend_Registry::get('Zend_Config');

$this->headMeta()
    ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
    ->appendHttpEquiv('Content-Language', 'de-DE');

$this->headTitle('OPUS 4')
    ->setSeparator(' | ');

if (isset($config->instance_name)) {
    $this->headTitle($config->instance_name);
}

if (isset($this->title)) {
    $this->headTitle($this->translate($this->title));
}

$this->headLink()
    ->appendStylesheet($this->layoutPath() . '/css/opus.css')
    ->appendStylesheet($this->layoutPath() . '/css/admin.css')
    ->headLink(array('rel' => 'shortcut icon', 'href' => $this->layoutPath() . '/img/logo/favicon.ico'));

$this->container = Zend_Registry::get('Opus_Navigation');

if ($this->jQueryEnabled()) {
    $this->headScript()
         ->prependFile($this->baseUrl() . '/' . $config->javascript->jquery->path)
         ->appendFile($this->layoutPath() . '/js/searchutil.js');
}

$languageSelectors = $this->languageSelector();
?>

<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">

    <head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <?= $this->headScript() ?>
        <?= $this->headLink() ?>

        <!--[if IE 6]>
        <link rel="stylesheet" type="text/css" href="<?= $this->layoutPath() ?>/css/opus-ie.css" />
        <![endif]-->
    </head>

    <body>
        <div id="top-header">
            <div class="wrapper">
                <?php if(!is_null($languageSelectors)) : ?>
                    <ul id="lang-switch" class="nav" title="Choose your language">
                        <?php foreach ($languageSelectors as $i => $languageSelector) : ?>
                            <li class="<?= ($i === 0) ? 'first' : '' ?>"><a href="<?= $languageSelector['url'] ?>" title="<?= $languageSelector['name'] ?>"><?= $languageSelector['name'] ?></a></li>
                        <?php endforeach ?>
                    </ul>
                <?php endif ?>
                <ul id="login-bar" class="nav"><?= $this->loginBar() ?></ul>
            </div>
        </div>

        <div id="header">
            <div class="wrapper">
                <h1 id="logo">
                    <a href="<?= $this->url(array('module' => 'home', 'controller' => 'index', 'action' => 'index'), null, true) ?>"><img src="<?= $this->layoutPath() ?>/img/logo/logo.gif" alt="OPUS" title="Home" width="185" height="89" /></a>
                </h1>
                <ul id="primary-nav" class="nav">
                <?php foreach ($this->container as $page) : ?>
                    <?php $pageIsActive = $page->isActive(false); ?>
                    <li id="<?= $page->getId() ?>" class="<?= ($pageIsActive ? 'active ' : '').$page->getClass()?>">
                        <a href="<?= $page->getHref() ?>" title="<?= $page->getTitle() ?>">
                            <?php if($pageIsActive) : ?>
                            <em>
                            <?php endif ?>
                            <span><?= $this->translate($page->getLabel()) ?></span>
                            <?php if($pageIsActive) : ?>
                            </em>
                            <?php endif ?>
                        </a>
                    </li>
                <?php endforeach ?>
                </ul>
            </div>
        </div>

        <div id="content" class="opus <?= $this->moduleName ?><?php if ($this->moduleName === 'publish') : ?>"><?php else : ?><?= ($this->controllerName === 'index' ? '' : '_'.$this->controllerName)?><?= ($this->actionName === 'index' ? '' : '_'.$this->actionName)?><?= ($this->searchType === 'collection' || $this->searchType === 'latest' ? ' '.$this->searchType : '') ?>">


                        <?  endif; ?>
            <?php if (!is_null($this->flashMessenger)) : ?>
            <div class="messages">
                <?php foreach ($this->flashMessenger->getMessages() as $message) : ?>
                    <div class="<?= $message['level'] ?>"><?= htmlspecialchars($message['message']) ?></div>
                <?php endforeach ?>
            </div>
            <?php endif ?>

            <div class="wrapper">
                <?= $this->layout()->content ?>
            </div>
        </div>

        <div id="page-footer">
            <div class="wrapper">
                <p id="logo-wrapper"><img src="<?= $this->layoutPath() ?>/img/logo/logo_small.gif" alt="OPUS" title="" width="69" height="29" /></p>
                <ul id="secondary-nav" class="nav">
                    <li class="first"><a href="<?= $this->url(array('module' => 'home', 'controller' => 'index', 'action' => 'contact'), null, true) ?>"><?= $this->translate('home_index_contact_actionname'); ?></a></li>
                    <li class="last"><a href="<?= $this->url(array('module' => 'home', 'controller' => 'index', 'action' => 'imprint'), null, true) ?>"><?= $this->translate('home_index_imprint_actionname') ?></a></li>
                </ul>
                <p id="copyright">&copy; <abbr xml:lang="de" title="Kooperativer Bibliotheksverbund Berlin-Brandenburg" lang="de">KOBV</abbr> 2010-2011</p>
            </div>
        </div>

        <div class="debug revision">
            <hr/>
            <div class="wrapper">
                <b>$Rev$</b>
            </div>
        </div>

        <?php
            $dbprofiler = Zend_Registry::get('db_adapter')->getProfiler();
            $profiler_show_queries = (bool) $config->db->params->showqueries;
            $profiler_max_queries = (int) $config->db->params->maxqueries;
            if ($dbprofiler->getEnabled() === true) :
        ?>
        <div class="debug dbprofiler">
            <div class="wrapper">
                <h2>Profiling information (execution time <?= microtime(true) - $GLOBALS['start_mtime'] ?>)</h2>
                <b>Total number of queries: </b><?= $dbprofiler->getTotalNumQueries() ?><br />
                <b>Total query time (s): </b><?= $dbprofiler->getTotalElapsedSecs() ?><br />
                <b>Current memory consumption: </b><?= memory_get_usage(true) ?><br />
                <b>Peak memory consumption: </b><?= memory_get_peak_usage(true) ?><br />
                <?php if ($profiler_show_queries === true and $profiler_query_profiles = $dbprofiler->getQueryProfiles()) : ?>
                    <b>Queries:</b><br />
                    <ul>
                    <?php for ($i=1; ($i < $profiler_max_queries) and ($i < count($profiler_query_profiles)); $i++) : ?>
                        <li><pre><?= $profiler_query_profiles[$i]->getQuery() ?></pre></li>
                    <?php endfor ?>
                    <?php if ($i < count($profiler_query_profiles)) { echo "<li>...</li>"; } ?>
                    </ul>
                <?php endif ?>
            </div>
        </div>
        <?php endif ?>

        <?php
            $identity = Zend_Auth::getInstance()->getIdentity();
            if (isset($config->debugSession) and ((bool)$config->debugSession === true) and !empty($identity)) :
        ?>
        <div class="debug session">
            <div class="wrapper">
                <h2>Session</h2>
                <? Zend_Debug::dump($_SESSION, 'Session Data'); ?>
            </div>
        </div>
        <?php endif ?>

    </body>
</html>
