<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Julian Heise <heise@zib.de>
 * @author      Thoralf Klein <thoralf.klein@zib.de>
 * @author      Sascha Szott <szott@zib.de>
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2010-2017, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

$config = Zend_Registry::get('Zend_Config');

$pageLanguage = Zend_Registry::get('Zend_Translate')->getLocale();

$this->headMeta()
    ->prependHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
    ->prependHttpEquiv('Content-Language', $pageLanguage);

$this->headTitle('OPUS 4')
    ->setSeparator(' | ');

if (isset($config->instance_name)) {
    $this->headTitle($config->instance_name);
}

if (isset($this->title)) {
    if ($this->moduleName !== 'frontdoor')
    {
        $this->headTitle($this->translate($this->title));
    }
    else
    { // do not translate for frontdoor, because the document title is used
        $this->headTitle(htmlspecialchars($this->title));
    }
}

$this->headLink()
    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css')
    ->appendStylesheet($this->baseUrl() . '/' . $config->css->jqueryui->path, 'screen')
    ->appendStylesheet($this->layoutPath() . '/css/opus.css', 'screen,print')
    ->appendStylesheet($this->layoutPath() . '/css/admin.css', 'screen,print')
    ->appendStylesheet($this->layoutPath() . '/css/print.css', 'print')
    ->appendStylesheet($this->layoutPath() . '/css/custom.css')
    ->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/x-icon',
        'href' => $this->layoutPath() . '/img/logo/favicon.ico'))
    ->headLink(array(
        'rel' => 'search',
        'title' => 'OPUS 4 Search',
        'type' => 'application/opensearchdescription+xml',
        'href' => $this->serverUrl() . $this->baseUrl() . '/solrsearch/opensearch'));

$this->container = Zend_Registry::get('Opus_Navigation');

$jsFiles = array('searchutil.js', 'frontdoorutil.js', 'submit.js');

if (in_array($this->moduleName, array('admin', 'review', 'setup', 'account'))) {
    $jsFiles[] = 'theme.js';
    $jsFiles[] = 'theme_lic.js';
    $jsFiles[] = 'opus-ui.js';
} else if (in_array($this->moduleName, array('publish'))) {
    $jsFiles[] = 'upload.js';
}

if (in_array($this->moduleName, array('admin'))) {
    $jsFiles[] = 'validation.js';
}

if ($this->jQueryEnabled()) {
    foreach (array_reverse($jsFiles) as $filename) {
         $this->headScript()->prependFile($this->layoutPath() . '/js/' . $filename);
    }

    $this->headScript()->prependFile($this->baseUrl() . '/' . $config->javascript->jqueryui->path);
    $this->headScript()->prependFile($this->baseUrl() . '/' . $config->javascript->jquery->path);
}

$appConfig = new Application_Configuration();

if ($appConfig->isLanguageSelectionEnabled()) {
    $languageSelectors = $this->languageSelector();
}
else {
    $languageSelectors = null;
}

if (isset($config->javascript->latex->mathjax)) {
    $this->headScript()->appendFile($this->baseUrl() . $config->javascript->latex->mathjax, 'text/javascript');
}
?>

<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $pageLanguage ?>" lang="<?= $pageLanguage ?>" dir="ltr" class="no-js">

    <head>
<?= $this->headMeta()->setIndent(8) ?>

<?= $this->headTitle()->setIndent(8) ?>

<?= $this->headLink()->setIndent(8) ?>


        <script type="text/javascript">
        //<![CDATA[
            window.opusBaseUrl = '<?= $this->serverUrl() . $this->baseUrl() ?>';
        //]]>
        </script>

<?= $this->headScript()->setIndent(8) ?>

	<!--[if IE 6]>
        <link rel="stylesheet" type="text/css" href="<?= $this->layoutPath() ?>/css/opus-ie.css" />
        <![endif]-->

        <!--[if lt IE 9]>
        <link rel="stylesheet" type="text/css" href="<?= $this->layoutPath() ?>/css/opus-ie-7.css" />
        <![endif]-->
<?= $this->javascriptMessages()->setIndent(8) ?>
    </head>

    <body>
        <div id="container">
            <div id="top-header">
                <div class="wrapper">
                    <?php if (!is_null($languageSelectors)) : ?>
                        <ul id="lang-switch" class="nav" title="Choose your language">
                            <?php foreach ($languageSelectors as $i => $languageSelector) : ?>
                                <li class="<?= ($i === 0) ? 'first' : '' ?>"><a href="<?= $languageSelector['url'] ?>" title="<?= $languageSelector['name'] ?>"><?= $languageSelector['name'] ?></a></li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif ?>
                    <div id="login-bar" class="nav"><?= $this->loginBar() ?></div>
                </div>
                <?php if (APPLICATION_ENV !== 'production') : ?>
                <div class="<?= APPLICATION_ENV ?>"><?= $this->translate('opus.environment') ?> (<?= APPLICATION_ENV ?>)</div>
                <?php endif ?>
            </div>

            <div id="header">
                <div class="wrapper">
                    <h1 id="logo">
                        <a href="<?= $this->optionUrl('logoLink') ?>" title="<?= $this->translate('logo_title') ?>"></a>
                        <span class="openaccess-logo">Open Access</span>
                    </h1>
                    <ul id="primary-nav" class="nav">
                    <?php foreach ($this->container as $page) : ?>
                        <?php $pageIsActive = $page->isActive(false); ?>
                        <li id="<?= $page->getId() ?>" class="<?= ($pageIsActive ? 'active ' : '').$page->getClass()?>">
                            <a href="<?= $page->getHref() ?>" title="<?= $this->translate($page->getTitle()) ?>">
                                <?php if($pageIsActive) : ?>
                                <em>
                                <?php endif ?>
                                    <span><?= $this->translate($page->getLabel()) ?></span>
                                <?php if($pageIsActive) : ?>
                                </em>
                                <?php endif ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                    </ul>
                </div>
            </div>

            <div id="content" class="opus <?= (in_array($this->moduleName, array('admin', 'review', 'setup', 'account'))) ? 'adminContainer' : ''?> <?= $this->moduleName ?><?php if ($this->moduleName === 'publish') : ?>"><?php else : ?><?= ($this->controllerName === 'index' ? '' : '_'.$this->controllerName)?><?= ($this->actionName === 'index' ? '' : '_'.$this->actionName)?><?= ($this->searchType === 'collection' || $this->searchType === 'latest' ? ' '.$this->searchType : '') ?>"><?php  endif; ?>

                <?PHP if (in_array($this->moduleName, array('admin', 'review', 'setup'))) : ?>
                    <?PHP if ($this->breadcrumbsDisabled !== true) : ?>
                        <?= $this->navigation()->breadcrumbs() ?>
                    <?PHP endif; ?>

                    <?= $this->messages() ?>

                    <?PHP if ($this->contentWrapperDisabled !== true && $this->breadcrumbsDisabled !== true) : ?>
                    <div class="wrapper">
                        <?= $this->layout()->content ?>
                    </div>
                    <?PHP else : ?>
                    <?= $this->layout()->content ?>
                    <?PHP endif; ?>
                <?PHP else : ?>
                    <?PHP if ($this->accessAllowed('documents') && !is_null($this->adminform)) : ?>
                        <?= $this->adminform ?>
                    <?PHP endif ?>

                    <?= $this->messages() ?>

                    <div class="wrapper">
                        <?= $this->layout()->content ?>
                    </div>
                <?PHP endif; ?>
            </div>

            <div id="page-footer">
                <div class="wrapper">
                    <p id="logo-wrapper"><a href="http://www.kobv.de/opus4/" title="Opus4 Website"><img src="<?= $this->layoutPath() ?>/img/logo/logo_small.gif" alt="OPUS4 Logo" title="" width="69" height="29" /></a></p>
                    <ul id="secondary-nav" class="nav">
                        <li class="first"><a href="<?= $this->url(array('module' => 'home', 'controller' => 'index', 'action' => 'contact'), null, true) ?>"><?= $this->translate('home_index_contact_actionname'); ?></a></li>
                        <li><a href="<?= $this->url(array('module' => 'home', 'controller' => 'index', 'action' => 'imprint'), null, true) ?>"><?= $this->translate('home_index_imprint_actionname') ?></a></li>
                        <li class="last"><a href="<?= $this->url(array('module' => 'crawlers', 'controller' => 'sitelinks'), null, true) ?>">Sitelinks</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <?PHP include('debug.phtml') ?>

    </body>
</html>
