<?php
$dbprofiler = \Zend_Registry::get('db_adapter')->getProfiler();
$profiler_show_queries = isset($config->db->params->showqueries) && filter_var($config->db->params->showqueries, FILTER_VALIDATE_BOOLEAN);
$profiler_max_queries = (int) $config->db->params->maxqueries;
if ($dbprofiler->getEnabled() === true) : ?>
    <div class="debug dbprofiler">
        <div class="wrapper">
            <h2>Profiling information
                <?php if (isset($GLOBALS['start_mtime'])) : ?>
                    (execution time <?= microtime(true) - $GLOBALS['start_mtime'] ?>)
                <?php endif ?>
            </h2>
            <b>Total number of queries: </b><?= $dbprofiler->getTotalNumQueries() ?><br/>
            <b>Total query time (s): </b><?= $dbprofiler->getTotalElapsedSecs() ?><br/>
            <b>Current memory consumption: </b><?= memory_get_usage(true) ?><br/>
            <b>Peak memory consumption: </b><?= memory_get_peak_usage(true) ?><br/>
            <?php if ($profiler_show_queries === true and $profiler_query_profiles = $dbprofiler->getQueryProfiles()) : ?>
                <b>Queries:</b><br/>
                <dl>
                    <?php $queryCount = null; ?>
                    <?php foreach ($profiler_query_profiles as $value) : ?>
                        <?php if (is_null($queryCount)) {
                            // erste DB-Anweisung ist immer 'connect' - diese soll nicht ausgegeben werden; daher überspringen
                            $queryCount = 0;
                            continue;
                        }
                        ?>
                        <dd style="margin-inline-start: 0;"><?= ++$queryCount ?>:</dd>
                        <dt style="margin-inline-start: 1em;">
                            <?php if ($queryCount > $profiler_max_queries) {
                                echo '...';
                                break;
                            }
                            ?>
                            <pre><?= htmlspecialchars($value->getQuery()) ?></pre>
                        </dt>
                    <?php endforeach ?>
                </dl>
            <?php endif ?>
        </div>
    </div>
<?php endif ?>

<?php
$identity = Zend_Auth::getInstance()->getIdentity();
if (isset($config->debugSession) and ((bool)$config->debugSession === true) and ! empty($identity)) :
    ?>
    <div class="debug session">
        <div class="wrapper">
            <h2>Session</h2>

            <?php /* do not apply indentation here! */ ?>
<pre>
<?= Zend_Debug::dump($_SESSION, 'Session Data', false); ?>
</pre>

        </div>
    </div>
<?php endif ?>
