<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<table>
    <thead>
        <tr>
            <th class="visible"><?= $this->translate($this->element->getColumnLabel(0)) ?>
                <a class="add" href="<?= $this->url(['action' => 'new']) ?>"><?=
                    $this->translate('admin_button_add') ?></a></th>
            <th colspan="2">&nbsp;</th>
            <th colspan="1"><?= $this->translate('admin_series_link_showdocuments') ?></th>
            <th colspan="1">&nbsp;</th>
        </tr>
    </thead>
    <?PHP foreach ($this->element->getModels() as $model) : ?>
        <tr>
            <td><a href="<?= $this->url(['action' => 'show', 'id' => $model->getId()]) ?>"
                class="displayname<?= $model->getField('Visible') === null || $model->getVisible() ? '' : ' invisible'?>"
                    ><?= htmlspecialchars($model->getDisplayName()) ?></a></td>
            <td>(ID = <?= $model->getId()?>)</td>
            <td class="edit">
                <a href="<?= $this->url(['action' => 'edit', 'id' => $model->getId()]) ?>"
                    ><?= $this->translate('admin_button_edit'); ?></a>
            </td>
            <td class="linked">
                <?PHP $docCount = $model->getNumOfAssociatedDocuments(); ?>
                <?PHP if ($docCount > 0) : ?>
                <a href="<?= $this->url(['module' => 'admin', 'controller' => 'documents', 'action' => 'index', 'seriesid' => $model->getId()]) ?>"><?= $this->translate('admin_series_link_showdocuments') ?>
                    (<?= $model->getNumOfAssociatedDocuments() ?>)</a>
                <?PHP else : ?>
                    <?= $this->translate('admin_series_link_nodocuments') ?>
                <?PHP endif ?>
            </td>
            <td class="remove">
                <a href="<?= $this->url(['action' => 'delete', 'id' => $model->getId()]) ?>"
                    ><?= $this->translate('admin_button_remove'); ?></a>
            </td>
        </tr>
    <?PHP endforeach; ?>
</table>