<?PHP
/*
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    TODO
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
<h1><?php echo $this->title ?></h1>
<h2>
<?= $this->translate('Total_Number_Documents')?>
: <?= $this->totalNumber?>
</h2>
<h2>
<?= $this->translate('Month_Overview_Title')?>
</h2>
<table>
<tr><th><?= $this->translate('Month_Title');?></th><th><?= $this->translate('Count_Title');?></th></tr>
<?php foreach ($this->monthStat as $month => $count):?>
<?= "<tr><td>".$this->translate('Month_'.$month)."</td><td>$count</td></tr>"?>
<?php endforeach;?>
</table>
<br>
<h2>
<?= $this->translate('Type_Overview_Title')?>
</h2>
<table>
<tr><th><?= $this->translate('Doc_Type');?></th><th><?= $this->translate('Count_Title');?></th></tr>
<?php foreach ($this->typeStat as $type => $count):?>
<?= "<tr><td>".$this->translate($type)."</td><td>$count</td></tr>"?>
<?php endforeach;?>
</table>
<br>
<?= "<h2>".$this->translate('Institute_Overview_Title')."</h2>"?>
</h2>
<table>
<tr><th><?= $this->translate('Institute_Title');?></th><th><?= $this->translate('Count_Title');?></th></tr>
<?php foreach ($this->instStat as $instName => $count):?>
<?= "<tr><td>".$instName."</td><td>$count</td></tr>"?>
<?php endforeach;?>
</table>
<?php echo $this->form?>
