<?
echo '<h1>Opus Application - Veröffentlichen</h1>';
echo '<h3>Studienarbeit</h3>';

echo $this->form;

?>
<!--
<form enctype="application/x-www-form-urlencoded" action="/opus4-devel/index.php/publish_2/index/check" method="post">
    <dl class="zend_form">

        <dt id="PersonSubmitterFirstName-label"><label for="PersonSubmitterFirstName" class="required">Einsteller: Vorname</label></dt>
        <dd id="PersonSubmitterFirstName-element">
        <input type="text" name="PersonSubmitterFirstName" id="PersonSubmitterFirstName" value="<?=$this->PersonSubmitterFirstName?>" />
        <? if (isset($this->PersonSubmitterFirstNameError)) echo '<ul class="errors">'. $this->PersonSubmitterFirstNameError .'</ul>'; ?>
        </dd>
        
        <dt id="PersonSubmitterLastName-label"><label for="PersonSubmitterLastName" class="required">Einsteller: Nachname</label></dt>
        <dd id="PersonSubmitterLastName-element">
        <input type="text" name="PersonSubmitterLastName" id="PersonSubmitterLastName" value="<?=$this->PersonSubmitterLastName?>" />
        <? if (isset($this->PersonSubmitterLastNameError)) echo '<ul class="errors">'. $this->PersonSubmitterLastNameError .'</ul>'; ?>
        </dd>
        
        <dt id="PersonAuthorFirstName-label"><label for="PersonAuthorFirstName" class="required">Autor: Vorname</label></dt>
        <dd id="PersonAuthorFirstName-element">
        <input type="text" name="PersonAuthorFirstName" id="PersonAuthorFirstName" value="<?=$this->PersonAuthorFirstName?>" />
        <? if (isset($this->PersonAuthorFirstNameError)) echo '<ul class="errors">'. $this->PersonAuthorFirstNameError .'</ul>'; ?>
        </dd>
        
        <dt id="PersonAuthorLastName-label"><label for="PersonAuthorLastName" class="required">Autor: Nachname</label></dt>
        <dd id="PersonAuthorLastName-element">
        <input type="text" name="PersonAuthorLastName" id="PersonAuthorLastName" value="<?=$this->PersonAuthorLastName?>" />
        <? if (isset($this->PersonAuthorLastNameError)) echo '<ul class="errors">'. $this->PersonAuthorLastNameError .'</ul>'; ?>
        </dd>
        
        <dt id="TitleMain-label"><label for="TitleMain" class="required">Haupttitel</label></dt>
        <dd id="TitleMain-element">
        <textarea name="TitleMain" id="TitleMain" rows="5" cols="80"><?=$this->TitleMain?></textarea>
        <? if (isset($this->TitleMainError)) echo '<ul class="errors">'. $this->TitleMainError .'</ul>'; ?>
        </dd>
        
        <dt id="Language-label"><label for="Language" class="required">Sprache</label></dt>
        <dd id="Language-element">
        <input type="text" name="Language" id="Language" value="<?=$this->Language ?>" />
        <? if (isset($this->LanguageError)) echo '<ul class="errors">'. $this->LanguageError .'</ul>'; ?>
        </dd>
        
        <dt id="PublishedYear-label"><label for="PublishedYear" class="required">Jahr der Veröffentlichung</label></dt>
        <dd id="PublishedYear-element">
        <input type="text" name="PublishedYear" id="PublishedYear" value="<?=$this->PublishedYear?>" />
        <? if (isset($this->PublishedYearError)) echo '<ul class="errors">'. $this->PublishedYearError .'</ul>'; ?>
        </dd>
        
        <dt id="SubjectSwd-label"><label for="SubjectSwd" class="required">SWD-Schlagwort</label></dt>
        <dd id="SubjectSwd-element">
        <input type="text" name="SubjectSwd" id="SubjectSwd" value="<?=$this->SubjectSwd?>" />
        <? if (isset($this->SubjectSwdError)) echo '<ul class="errors">'. $this->SubjectSwdError .'</ul>'; ?>
        </dd>

        <dt id="IdentifierOpus3-label"><label for="IdentifierOpus3" class="optional">Opus3 ID</label></dt>
        <dd id="IdentifierOpus3-element">
        <input type="text" name="IdentifierOpus3" id="IdentifierOpus3" value="<?=$this->IdentifierOpus3?>" />
        <? if (isset($this->IdentifierOpus3Error)) echo '<ul class="errors">'. $this->IdentifierOpus3Error .'</ul>'; ?>
        </dd>

        <dt id="TitleAbstract-label"><label for="TitleAbstract" class="required">Abstract / Kurzfassung</label></dt>
        <dd id="TitleAbstract-element">
        <textarea name="TitleAbstract" id="TitleAbstract" rows="5" cols="80"><?=$this->TitleAbstract?></textarea>
        <? if (isset($this->TitleAbstractError)) echo '<ul class="errors">'. $this->TitleAbstractError .'</ul>'; ?>
        </dd>

       <dt id="Licence-label"><label for="Licence" class="required">Lizenz</label></dt>
        <dd id="Licence-element">
        <input type="text" name="Licence" id="Licence" value="<?=$this->Licence?>" />
        <? if (isset($this->LicenceError)) echo '<ul class="errors">'. $this->LicenceError .'</ul>'; ?>
        </dd>

        <dt id="PersonAdvisorFirstName-label"><label for="PersonAdvisorFirstName" class="optional">Berichter: Vorname</label></dt>
        <dd id="PersonAdvisorFirstName-element">
        <input type="text" name="PersonAdvisorFirstName" id="PersonAdvisorFirstName" value="<?=$this->PersonAdvisorFirstName?>" />
        <? if (isset($this->PersonAdvisorFirstNameError)) echo '<ul class="errors">'. $this->PersonAdvisorFirstNameError .'</ul>'; ?>
        </dd>

        <dt id="PersonAdvisorLastName-label"><label for="PersonAdvisorLastName" class="optional">Berichter: Nachname</label></dt>
        <dd id="PersonAdvisorLastName-element">
        <input type="text" name="PersonAdvisorLastName" id="PersonAdvisorLastName" value="<?=$this->PersonAdvisorLastName?>" />
        <? if (isset($this->PersonAdvisorLastNameError)) echo '<ul class="errors">'. $this->PersonAdvisorLastNameError .'</ul>'; ?>
        </dd>

        <dt id="PersonContributorFirstName-label"><label for="PersonContributorFirstName" class="optional">Beitragender: Vorname</label></dt>
        <dd id="PersonContributorFirstName-element">
        <input type="text" name="PersonContributorFirstName" id="PersonContributorFirstName" value="<?=$this->PersonContributorFirstName?>" />
        <? if (isset($this->PersonContributorFirstNameError)) echo '<ul class="errors">'. $this->PersonContributorFirstNameError .'</ul>'; ?>
        </dd>

        <dt id="PersonContributorLastName-label"><label for="PersonContributorLastName" class="optional">Beitragender: Nachname</label></dt>
        <dd id="PersonContributorLastName-element">
        <input type="text" name="PersonContributorLastName" id="PersonContributorLastName" value="<?=$this->PersonContributorLastName?>" />
        <? if (isset($this->PersonContributorLastNameError)) echo '<ul class="errors">'. $this->PersonContributorLastNameError .'</ul>'; ?>
        </dd>

        <dt id="CreatingCorporation-label"><label for="CreatingCorporation" class="optional">Urhebende Körperschaft</label></dt>
        <dd id="CreatingCorporation-element">
        <input type="text" name="CreatingCorporation" id="CreatingCorporation" value="<?=$this->CreatingCorporation?>" />
        <? if (isset($this->CreatingCorporationError)) echo '<ul class="errors">'. $this->CreatingCorporationError .'</ul>'; ?>
        </dd>

        <dt id="ContributingCorporation-label"><label for="ContributingCorporation" class="optional">Beteiligte Körperschaft</label></dt>
        <dd id="ContributingCorporation-element">
        <input type="text" name="ContributingCorporation" id="ContributingCorporation" value="<?=$this->ContributingCorporation?>" />
        <? if (isset($this->ContributingCorporationError)) echo '<ul class="errors">'. $this->ContributingCorporationError .'</ul>'; ?>
        </dd>

        <dt id="PageNumber-label"><label for="PageNumber" class="optional">Seitenzahl</label></dt>
        <dd id="PageNumber-element">
        <input type="text" name="PageNumber" id="PageNumber" value="<?=$this->PageNumber?>" />
        <? if (isset($this->PageNumberError)) echo '<ul class="errors">'. $this->PageNumberError .'</ul>'; ?>
        </dd>

        <dt id="IdentifierUrn-label"><label for="IdentifierUrn" class="optional">URN</label></dt>
        <dd id="IdentifierUrn-element">
        <input type="text" name="IdentifierUrn" id="IdentifierUrn" value="<?=$this->IdentifierUrn?>" />
        <? if (isset($this->IdentifierUrnError)) echo '<ul class="errors">'. $this->IdentifierUrnError .'</ul>'; ?>
        </dd>

        <dt id="IdentifierOpac-label"><label for="IdentifierOpac" class="optional">Opac Id</label></dt>
        <dd id="IdentifierOpac-element">
        <input type="text" name="IdentifierOpac" id="IdentifierOpac" value="<?=$this->IdentifierOpac?>" />
        <? if (isset($this->IdentifierOpacError)) echo '<ul class="errors">'. $this->IdentifierOpacError .'</ul>'; ?>
        </dd>

       <dt id="Note-label"><label for="Note" class="optional">Bemerkung</label></dt>
        <dd id="Note-element">
        <textarea name="Note" id="Note" rows="5" cols="80"><?=$this->Note?></textarea>
        <? if (isset($this->NoteError)) echo '<ul class="errors">'. $this->NoteError .'</ul>'; ?>
        </dd>

        <dt id="documentType-label">&nbsp;</dt>
        <dd id="documentType-element">
        <input type="hidden" name="documentType" value="studienarbeit" id="documentType" />
        </dd>

        <dt id="documentId-label">&nbsp;</dt>
        <dd id="documentId-element">
        <input type="hidden" name="documentId" value="<?= $this->documentId ?>" id="documentId" />
        </dd>

        <dt id="fulltext-label">&nbsp;</dt>
        <dd id="fulltext-element">
        <input type="hidden" name="fulltext" value="<?= $this->fulltext ?>" id="fulltext" />
        </dd>

        <dt id="send-label">&nbsp;</dt><dd id="send-element">
        <input type="submit" name="send" id="send" value="Senden" />
        </dd>
    </dl>

</form>
-->

