<?
echo '<h1>Opus Application - Veröffentlichen</h1>';
echo '<h3>Studienarbeit</h3>';
?>

<form enctype="application/x-www-form-urlencoded" action="/opus4-devel/index.php/publish/index/check" method="post">

    <fieldset>
        <legend><?=$this->PersonSubmitter?></legend>
        <table>
            <tr>
                <td><label for="PersonSubmitterFirstName" class="required"><?=$this->PersonSubmitterFirstName_label?></label></td>
                <td><input type="text" name="PersonSubmitterFirstName" id="PersonSubmitterFirstName" value="<?=$this->PersonSubmitterFirstName?>" />
                    <? if (isset($this->PersonSubmitterFirstNameError)) echo '<ul class="errors">'. $this->PersonSubmitterFirstNameError .'</ul>'; ?>
                </td>
            </tr>
            <tr>
                <td><label for="PersonSubmitterLastName" class="required"><?=$this->PersonSubmitterLastName_label?></label></td>
                <td>
                    <input type="text" name="PersonSubmitterLastName" id="PersonSubmitterLastName" value="<?=$this->PersonSubmitterLastName?>" />
                    <? if (isset($this->PersonSubmitterLastNameError)) echo '<ul class="errors">'. $this->PersonSubmitterLastNameError .'</ul>'; ?>
                </td>
            </tr>
        </table>
    </fieldset>

    <fieldset>
        <legend><?=$this->PersonAuthor?></legend>
        <table>
             <?php if (isset($this->groupPersonAuthor)) {
                 foreach ($this->groupPersonAuthor["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" /></td>
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupPersonAuthor["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupPersonAuthor["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

   <fieldset>
        <legend><?=$this->TitleMain?></legend>
        <table>
             <?php if (isset($this->groupTitleMain)) {
                 foreach ($this->groupTitleMain["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupTitleMain["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupTitleMain["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <table>
        <tr>
            <td><label for="Language" class="required"><?=$this->Language_label?></label></td>
            <td><input type="text" name="Language" id="Language" value="<?=$this->Language ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->LanguageError)) echo '<ul class="errors">'. $this->LanguageError .'</ul>'; ?></td></tr>

        <tr>
            <td><label for="PublishedYear" class="required"><?=$this->PublishedYear_label?></label></td>
            <td><input type="text" name="PublishedYear" id="Language" value="<?=$this->PublishedYear ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->PublishedYearError)) echo '<ul class="errors">'. $this->PublishedYearError .'</ul>'; ?></td></tr>
    </table>

    <fieldset>
        <legend><?=$this->SubjectSwd?></legend>
        <table>
             <?php if (isset($this->groupSubjectSwd)) {
                 foreach ($this->groupSubjectSwd["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupSubjectSwd["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupSubjectSwd["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <table>
        <tr>
            <td><label for="IdentifierOpus3" class="required"><?=$this->IdentifierOpus3_label?></label></td>
            <td><input type="text" name="Language" id="IdentifierOpus3" value="<?=$this->IdentifierOpus3 ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->IdentifierOpus3Error)) echo '<ul class="errors">'. $this->IdentifierOpus3eError .'</ul>'; ?></td></tr>
    </table>

    <fieldset>
        <legend><?=$this->TitleAbstract?></legend>
        <table>
             <?php if (isset($this->groupTitleAbstract)) : ?>
                 <?php foreach ($this->groupTitleAbstract["Fields"] AS $field) : ?>
                    <tr>
                        <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                        <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
                    </tr>
                    <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
                <?php endforeach ?>
                <?php foreach ($this->groupTitleAbstract["Buttons"] AS $button) : ?>
                    <tr>
                        <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
                    </tr>
                <?php endforeach ?>
                <?php foreach ($this->groupTitleAbstract["Hiddens"] AS $hidden) : ?>
                    <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
                <?php endforeach ?>
            <?php endif ?>
        </table>
    </fieldset>

    <table>
        <tr>
            <td><label for="Licence" class="required"><?=$this->Licence_label?></label></td>
            <td><input type="text" name="Licence" id="Licence" value="<?=$this->Licence ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->LicenceError)) echo '<ul class="errors">'. $this->LicenceError .'</ul>'; ?></td></tr>
    </table>

    <fieldset>
        <legend><?=$this->PersonAdvisor?></legend>
        <table>
             <?php if (isset($this->groupPersonAdvisor)) {
                 foreach ($this->groupPersonAdvisor["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupPersonAdvisor["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupPersonAdvisor["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <fieldset>
        <legend><?=$this->PersonContributor?></legend>
        <table>
             <?php if (isset($this->groupPersonContributor)) {
                 foreach ($this->groupPersonContributor["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupPersonContributor["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupPersonContributor["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <fieldset>
        <legend><?=$this->CreatingCorporation?></legend>
        <table>
             <?php if (isset($this->groupCreatingCorporation)) {
                 foreach ($this->groupCreatingCorporation["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupCreatingCorporation["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupCreatingCorporation["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <fieldset>
        <legend><?=$this->ContributingCorporation?></legend>
        <table>
             <?php if (isset($this->groupContributingCorporation)) {
                 foreach ($this->groupCreatingCorporation["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupContributingCorporation["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupContributingCorporation["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <table>
        <tr>
            <td><label for="PageNumber" class="optional"><?=$this->PageNumber_label?></label></td>
            <td><input type="text" name="PageNumber" id="PageNumber" value="<?=$this->PageNumber ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->PageNumberError)) echo '<ul class="errors">'. $this->PageNumberError .'</ul>'; ?></td></tr>

        <tr>
            <td><label for="IdentifierUrn" class="optional"><?=$this->IdentifierUrn_label?></label></td>
            <td><input type="text" name="IdentifierUrn" id="IdentifierUrn" value="<?=$this->IdentifierUrn ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->IdentifierUrnError)) echo '<ul class="errors">'. $this->IdentifierUrnError .'</ul>'; ?></td></tr>

         <tr>
            <td><label for="IdentifierOpac" class="optional"><?=$this->IdentifierOpac_label?></label></td>
            <td><input type="text" name="IdentifierOpac" id="IdentifierOpac" value="<?=$this->IdentifierOpac ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->IdentifierOpacError)) echo '<ul class="errors">'. $this->IdentifierOpacError .'</ul>'; ?></td></tr>

        <tr>
            <td><label for="Note" class="optional"><?=$this->Note_label?></label></td>
            <td><textarea name="Note" id="Note"><?=$this->Note ?></textarea></td>
        </tr>

        <tr>
            <td><?= $this->label("Note", "note_label"); ?></td>
            <td><?= $this->textarea("Note"); ?></td>
        </tr>
        <tr><td colspan="2"><?= $this->showerror("Note"); ?></td></tr>
    </table>

    <input type="hidden" name="documentType" value="studienarbeit" id="documentType" />
    <input type="hidden" name="documentId" value="<?= $this->documentId ?>" id="documentId" />
    <input type="hidden" name="fulltext" value="<?= $this->fullText ?>" id="fullText" />
    <input type="submit" name="send" id="send" value="Senden" />

    
</form>