<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Licence
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2008-2013, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div>
<a href="<?= $this->url(array('action' => 'new')) ?>"><?= $this->translate('admin_account_action_new')?></a>
</div>

<table id="accounts">
    <tr>
        <th><?= $this->translate('admin_account_column_account') ?></th>
        <th><?= $this->translate('admin_account_column_name') ?></th>
        <th><?= $this->translate('admin_account_column_email') ?></th>
        <th><?= $this->translate('admin_account_column_roles') ?></th>
        <th>&nbsp;</th>
    </tr>
<?PHP $index = -1; foreach($this->accounts as $id => $entry) : ?>
    <?PHP $firstName = $entry->getFirstName() ?>
    <tr class="<?= ($index++ % 2) ? 'odd' : 'even' ?>">
        <td class="accountname"><a href="<?= $this->url(array('action' => 'show', 'id' => $id)) ?>"><?= htmlspecialchars(strtolower($entry->getDisplayName())) ?></a></td>
        <td class="fullname"><?= htmlspecialchars($entry->getLastName()) ?><?PHP if (strlen(trim($firstName)) > 0) : ?>, <?= $firstName ?><?PHP endif; ?></td>
        <td class="email"><?= htmlspecialchars($entry->getEmail()) ?></td>
        <td class="roles"><?PHP foreach ($entry->getRole() as $i => $role) : 
            ?><?= ($i > 0 ) ? '<br>' : '' 
            ?><?= htmlspecialchars($role) 
            ?><?PHP endforeach; ?></td>
        <td>
            <a href="<?= $this->url(array('action' => 'edit', 'id' => $id)) ?>"><?= $this->translate('admin_account_action_edit')?></a>
            <?PHP if ((Zend_Auth::getInstance()->getIdentity() !== strtolower($entry->getLogin())) && ($entry->getLogin() !== 'admin')) : ?>
                <a href="<?= $this->url(array('action' => 'delete', 'id' => $id)) ?>"><?= $this->translate('admin_account_action_delete')?></a>
            <?PHP endif; ?>
        </td>
    </tr>
<?PHP endforeach; ?>
</table>