<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2019, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<table>
    <thead>
        <tr>
            <th><?= $this->translate('admin_account_column_account') ?>
                <a class="add" href="<?= $this->url(['action' => 'new']) ?>"><?=
                    $this->translate('admin_button_add') ?></a></th>
            <th><?= $this->translate('LastName') ?></th>
            <th><?= $this->translate('FirstName') ?></th>
            <th><?= $this->translate('admin_account_column_email') ?></th>
            <th><?= $this->translate('admin_account_column_roles') ?></th>
            <th colspan="2">&nbsp;</th>
        </tr>
    </thead>
    <?PHP foreach ($this->element->getModels() as $model) : ?>
        <tr>
            <td class="accountname"><a href="<?= $this->url(['action' => 'show', 'id' => $model->getId()]) ?>"><?= htmlspecialchars(strtolower($model->getDisplayName())) ?></a></td>
            <td class="lastname"><?= htmlspecialchars($model->getLastName() ?? '') ?></td>
            <td class="firstname"><?= $model->getFirstName() ?></td>
            <td class="email"><?= htmlspecialchars($model->getEmail() ?? '') ?></td>
            <td class="roles"><?PHP foreach ($model->getRole() as $i => $role) :
                ?><?= $i > 0 ? '<br>' : ''
?><?= htmlspecialchars($role)
?><?PHP
                              endforeach; ?>
            </td>
            <td class="edit">
                <a href="<?= $this->url(['action' => 'edit', 'id' => $model->getId()]) ?>"
                    ><?= $this->translate('admin_button_edit'); ?></a>
            </td>
            <td class="remove">
                <?PHP if ($this->element->isDeletable($model)) : ?>
                <a href="<?= $this->url(['action' => 'delete', 'id' => $model->getId()]) ?>"
                    ><?= $this->translate('admin_button_remove'); ?></a>
                <?PHP endif ?>
            </td>
        </tr>
    <?PHP endforeach; ?>
</table>
