<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License 
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51 
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Licence
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div class="adminContainer">

<div class="breadcrumbsContainer">
<?= $this->navigation()->breadcrumbs() ?>
</div>

<table>
    <tr>
        <td class="label"><?= $this->translate('admin_account_label_login') ?></td>
        <td class="value"><?= htmlspecialchars($this->account->getLogin())?></td>
    </tr>
    <tr>
        <td class="label"><?= $this->translate('admin_account_label_firstname') ?></td>
        <td class="value"><?= htmlspecialchars($this->account->getFirstName()) ?></td>
    </tr>
    <tr>
        <td class="label"><?= $this->translate('admin_account_label_lastname') ?></td>
        <td class="value"><?= htmlspecialchars($this->account->getLastName()) ?></td>
    </tr>
    <tr>
        <td class="label"><?= $this->translate('admin_account_label_email') ?></td>
        <td class="value"><?= htmlspecialchars($this->account->getEmail()) ?></td>
    </tr>
    <tr>
        <td class="label"><?= $this->translate('admin_account_label_roles') ?></td>
        <td class="value">
            <?PHP foreach ($this->account->getRole() as $role) : ?>
            <?= htmlspecialchars($role) ?><br>
            <?PHP endforeach; ?>
        </td>
    </tr>
</table>

<h2><?= $this->translate('admin_account_module_access_summary') ?></h2>
<table>
    <tr>
        <th><?= $this->translate('admin_account_label_module') ?></th>
        <th><?= $this->translate('admin_account_label_has_access') ?></th>
        <th><?= $this->translate('admin_account_label_roles') ?></th>
    </tr>

    <?php foreach ($this->allModules AS $module) : ?>
      <tr><td><?= htmlspecialchars($module) ?></td>
      <?php if (count($this->modulesRoles[$module]) > 0) : ?>
        <td><b><?= $this->translate('answer_yes') ?></b></td>
        <td><b><?= htmlspecialchars(implode(", ", $this->modulesRoles[$module])) ?></b></td>
      <?php else : ?>
        <td><?= $this->translate('answer_no') ?></td>
        <td>-</td>
      <?php endif ?>
    <?php endforeach ?>
</table>

</div>

