<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<div class="account-info">
    <div>
        <div class="label"><?= $this->translate('admin_account_label_login') ?></div>
        <div class="value"><?= htmlspecialchars(strtolower($this->account->getLogin()))?></div>
    </div>
    <div>
        <div class="label"><?= $this->translate('admin_account_label_firstname') ?></div>
        <div class="value"><?= htmlspecialchars($this->account->getFirstName() ?? '') ?></div>
    </div>
    <div>
        <div class="label"><?= $this->translate('admin_account_label_lastname') ?></div>
        <div class="value"><?= htmlspecialchars($this->account->getLastName() ?? '') ?></div>
    </div>
    <div>
        <div class="label"><?= $this->translate('admin_account_label_email') ?></div>
        <div class="value"><?= htmlspecialchars($this->account->getEmail() ?? '') ?></div>
    </div>
    <div>
        <div class="label"><?= $this->translate('admin_account_label_roles') ?></div>
        <div class="value">
            <?PHP foreach ($this->account->getRole() as $role) : ?>
                <?= htmlspecialchars($role) ?><br>
            <?PHP endforeach; ?>
        </div>
    </div>
</div>

<fieldset>
<legend><?= $this->translate('admin_account_module_access_summary') ?></legend>
<table class="module-access-table">
    <tr>
        <th><?= $this->translate('admin_account_label_module') ?></th>
        <th><?= $this->translate('admin_account_label_has_access') ?></th>
        <th><?= $this->translate('admin_account_label_roles') ?></th>
    </tr>
    <?php foreach ($this->allModules as $module) : ?>
      <tr class="<?= count($this->modulesRoles[$module]) > 0 ? 'access' : 'noaccess' ?>">
          <td class="column-module"><?= htmlspecialchars($module) ?></td>
        <?php if (count($this->modulesRoles[$module]) > 0) : ?>
        <td><?= $this->translate('answer_yes') ?></td>
        <td><?= htmlspecialchars(implode(", ", $this->modulesRoles[$module])) ?></td>
        <?php else : ?>
        <td><?= $this->translate('answer_no') ?></td>
        <td>-</td>
        <?php endif ?>
    <?php endforeach ?>
</table>
</fieldset>
