<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Julian Heise (heise@zib.de)
 * @copyright   Copyright (c) 2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
    ->appendHttpEquiv('Content-Language', 'de-DE');

// TODO diesen block da unterbringen, wo er hingehört (view / controller class)
    $this->headTitle('OPUS 4')
        ->headTitle($this->title)
        ->setSeparator(' | ');

    $fc = Zend_Controller_Front::getInstance();
    $basePath = $fc->getRequest()->getBasePath();
    $this->headLink()
        ->appendStylesheet($basePath . '/layouts/opus4/css/opus.css');
?>

<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <?= $this->headLink() ?>
    </head>

    <body>
        
        <div id="page">
            
            <div id="header">
                <div id="logo">
                    <img src="#" alt="logo" class="logo"/>
                    <h1>Opus 4</h1>
                </div>

                <div id="navigationMenu">
                        <?= $this->navigation()->menu(); ?>
                </div>
            </div>

            <div id="loginBar" class="login_bar">
                <?= $this->loginBar(); ?>
            </div>

            <div id="content" class="clearfix">
                <?= $this->layout()->content ?>
            </div>

            <div id="footer">
                <div id="footerLinks" class="left">
                    <span class="footer_link">
                        <a href="#"><?= $this->translate('credits_label'); ?></a>
                    </span>

                    <span class="footer_link">
                        <a href="<?= $basePath ?>/home/index/contact"><?= $this->translate('home_index_contact_actionname'); ?></a>
                    </span>
                </div>

                <div id="languageSelection" class="right">
                    <a href="<?= $basePath ?>/home/index/language/language/en">
                        <img src="#" alt="British flag" title="Switch to english version" />
                    </a>
                    <a href="<?= $basePath ?>/home/index/language/language/de">
                        <img src="#" alt="Deutsche Flagge" title="Auf die deutsche Version umschalten" />
                    </a>
                </div>

                <div id="copyright">
                    &copy; KOBV 2010
                </div>

                <?php
                    $dbprofiler = Zend_Registry::get('db_adapter')->getProfiler();
                    $config = Zend_Registry::get('Zend_Config');
                    $profiler_show_queries = (bool) $config->db->params->showqueries;
                    $profiler_max_queries = (int) $config->db->params->maxqueries;
                    if ($dbprofiler->getEnabled() === true) :
                ?>
                <div class="debug dbprofiler">
                    <hr/>
                    <h2>Profiling information (execution time <?= microtime(true) - $GLOBALS['start_mtime'] ?>)</h2>
                    <b>Total number of queries: </b><?= $dbprofiler->getTotalNumQueries() ?><br />
                    <b>Total query time (s): </b><?= $dbprofiler->getTotalElapsedSecs() ?><br />
                    <b>Current memory consumption: </b><?= memory_get_usage(true) ?><br />
                    <b>Peak memory consumption: </b><?= memory_get_peak_usage(true) ?><br />
                    <?php if ($profiler_show_queries === true and $profiler_query_profiles = $dbprofiler->getQueryProfiles()) : ?>
                        <b>Queries:</b><br />
                        <ul>
                        <?php for ($i=1; ($i < $profiler_max_queries) and ($i < count($profiler_query_profiles)); $i++) : ?>
                            <li><pre><?= $profiler_query_profiles[$i]->getQuery() ?></pre></li>
                        <?php endfor ?>
                        <?php if ($i < count($profiler_query_profiles)) { echo "<li>...</li>"; } ?>
                        </ul>
                    <?php endif ?>
                </div>
                <?php endif ?>

            </div>
        </div>

    </body>
</html>
