<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

use Opus\Common\Config;

$config = Config::get();

$pageLanguage = Application_Translate::getInstance()->getLocale();

$this->headMeta()
    ->prependHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
    ->prependHttpEquiv('Content-Language', $pageLanguage);

$this->headTitle('OPUS 4')
    ->setSeparator(' | ');

if (isset($config->instance_name)) {
    $this->headTitle($config->instance_name);
}

if (isset($this->title)) {
    $this->headTitle($this->translate($this->title));
}

$this->headLink()
    ->appendStylesheet($this->baseUrl() . '/' . $config->css->jqueryui->path, 'screen')
    ->appendStylesheet($this->layoutPath() . '/css/opus.css', 'screen,print')
    ->appendStylesheet($this->layoutPath() . '/css/admin.css', 'screen,print')
    ->appendStylesheet($this->layoutPath() . '/css/theme.css', 'screen')
    ->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/x-icon',
        'href' => $this->layoutPath() . '/img/logo/favicon.ico',
    ])
    ->headLink([
        'rel'   => 'search',
        'title' => 'OPUS 4 Search',
        'type'  => 'application/opensearchdescription+xml',
        'href'  => $this->serverUrl() . $this->baseUrl() . '/solrsearch/opensearch',
    ]);

/*
uncomment the following line if you want to enable your own layout changes
$this->headLink()->appendStylesheet($this->layoutPath() . '/css/custom.css');
*/

$this->container = Zend_Registry::get('Opus_Navigation');

$jsFiles = ['searchutil.js', 'frontdoorutil.js', 'submit.js'];

if (in_array($this->moduleName, ['admin', 'review', 'setup', 'account'])) {
    $jsFiles[] = 'theme.js';
    $jsFiles[] = 'theme_lic.js';
} elseif (in_array($this->moduleName, ['publish'])) {
    $jsFiles[] = 'filetypes.js';
}

if ($this->jQueryEnabled()) {
    $this->headScript()->prependFile($this->baseUrl() . '/' . $config->javascript->jqueryui->path);
    $this->headScript()->prependFile($this->baseUrl() . '/' . $config->javascript->jquery->path);

    foreach ($jsFiles as $filename) {
        $this->headScript()->appendFile($this->layoutPath() . '/js/' . $filename);
    }
}

$appConfig = new Application_Configuration();

if ($appConfig->isLanguageSelectionEnabled()) {
    $languageSelectors = $this->languageSelector();
} else {
    $languageSelectors = null;
}

if (isset($config->javascript->latex->mathjax)) {
    $this->headScript()->appendFile($this->baseUrl() . $config->javascript->latex->mathjax, 'text/javascript');
}
?>

<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $pageLanguage ?>" lang="<?= $pageLanguage ?>" dir="ltr"
      class="no-js">

<head>
    <?= $this->headMeta()->setIndent(8) ?>

    <?= $this->headTitle()->setIndent(8) ?>

    <?= $this->headLink()->setIndent(8) ?>


    <script type="text/javascript">
        //<![CDATA[
        window.opusBaseUrl = '<?= $this->serverUrl() . $this->baseUrl() ?>';
        //]]>
    </script>

    <?= $this->headScript()->setIndent(8) ?>

    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="<?= $this->layoutPath() ?>/css/opus-ie.css"/>
    <![endif]-->

    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="<?= $this->layoutPath() ?>/css/opus-ie-7.css"/>
    <![endif]-->
</head>

<body>
<div id="container">
    <div id="top-header">
        <div class="wrapper">
            <?php if ($languageSelectors !== null) : ?>
                <ul id="lang-switch" class="nav" title="Choose your language">
                    <?php foreach ($languageSelectors as $i => $languageSelector) : ?>
                        <li class="<?= $i === 0 ? 'first' : '' ?>"><a href="<?= $languageSelector['url'] ?>"
                                                                        title="<?= $languageSelector['name'] ?>"><?= $languageSelector['name'] ?></a>
                        </li>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>
            <div id="login-bar" class="nav"><?= $this->loginBar() ?></div>
        </div>
        <?php if (APPLICATION_ENV !== 'production') : ?>
            <div class="<?= APPLICATION_ENV ?>"><?= $this->translate('opus.environment') ?> (<?= APPLICATION_ENV ?>)
            </div>
        <?php endif ?>
    </div>

    <div id="header">
        <div class="wrapper">
            <h1 id="logo">
                <a href="<?= $this->url(['module' => 'home', 'controller' => 'index', 'action' => 'index'], null, true) ?>"><img
                            src="<?= $this->layoutPath() ?>/img/logo/logo.gif" alt="OPUS" title="Home" width="185"
                            height="89"/></a>
            </h1>
            <ul id="primary-nav" class="nav">
                <?php foreach ($this->container as $page) : ?>
                    <?php $pageIsActive = $page->isActive(false); ?>
                    <li id="<?= $page->getId() ?>" class="<?= ($pageIsActive ? 'active ' : '') . $page->getClass() ?>">
                        <a href="<?= $page->getHref() ?>" title="<?= $this->translate($page->getTitle()) ?>">
                            <?php if ($pageIsActive) : ?>
                            <em>
                            <?php endif ?>
                                <span><?= $this->translate($page->getLabel()) ?></span>
                            <?php if ($pageIsActive) : ?>
                            </em>
                            <?php endif ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>

    <?PHP // TODO searchType as CSS only for 'collection' and 'latest' used - Can it be refactored? ?>
    <div id="content" class="opus <?= $this->adminCssClass() ?> <?= $this->moduleName ?> <?= $this->actionCssClass() ?> <?= $this->searchType ?>">

        <?PHP $messages = $this->flashMessenger !== null ? $this->flashMessenger->getMessages() : null ?>

        <?PHP if (in_array($this->moduleName, ['admin', 'review', 'setup'])) : ?>
            <?PHP if ($this->breadcrumbsDisabled !== true) : ?>
                <?= $this->navigation()->breadcrumbs() ?>
            <?PHP endif; ?>

            <?php if (! empty($messages)) : ?>
                <div class="messages">
                    <?php foreach ($messages as $message) : ?>
                        <div class="<?= $message['level'] ?>"><?= htmlspecialchars($this->translate($message['message'])) ?></div>
                    <?php endforeach ?>
                </div>
            <?php endif ?>

            <?PHP if ($this->contentWrapperDisabled !== true && $this->breadcrumbsDisabled !== true) : ?>
                <div class="wrapper">
                    <?= $this->layout()->content ?>
                </div>
            <?PHP else : ?>
                <?= $this->layout()->content ?>
            <?PHP endif; ?>
        <?PHP else : ?>
            <?PHP if ($this->accessAllowed('documents') && $this->adminform !== null) : ?>
                <?= $this->adminform ?>
            <?PHP endif ?>

            <?php if (! empty($messages)) : ?>
                <div class="messages">
                    <?php foreach ($this->flashMessenger->getMessages() as $message) : ?>
                        <div class="<?= $message['level'] ?>"><?= htmlspecialchars($this->translate($message['message'])) ?></div>
                    <?php endforeach ?>
                </div>
            <?php endif ?>

            <div class="wrapper">
                <?= $this->layout()->content ?>
            </div>
        <?PHP endif; ?>
    </div>

    <div id="page-footer">
        <div class="wrapper">
            <p id="logo-wrapper"><a href="http://www.kobv.de/opus4/" title="Opus4 Website"><img
                            src="<?= $this->layoutPath() ?>/img/logo/logo_small.gif" alt="OPUS4 Logo" title=""
                            width="69" height="29"/></a></p>
            <ul id="secondary-nav" class="nav">
                <li class="first"><a
                            href="<?= $this->url(['module' => 'home', 'controller' => 'index', 'action' => 'contact'], null, true) ?>"><?= $this->translate('home_index_contact_actionname'); ?></a>
                </li>
                <li>
                    <a href="<?= $this->url(['module' => 'home', 'controller' => 'index', 'action' => 'imprint'], null, true) ?>"><?= $this->translate('home_index_imprint_actionname') ?></a>
                </li>
                <li class="last"><a
                            href="<?= $this->url(['module' => 'crawlers', 'controller' => 'sitelinks'], null, true) ?>">Sitelinks</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div id="appmode-<?= Zend_Controller_Front::getInstance()->getParam('bootstrap')->getEnvironment() ?>"
     class="debug revision">
    <hr/>
    <div class="wrapper">
        <?php /* do not edit: revision number gets updated automatically */ ?>
        <b>$Rev$</b>
    </div>
</div>

<?php
$dbprofiler          = Zend_Db_Table::getDefaultAdapter()->getProfiler();
$profilerShowQueries = isset($config->db->params->showqueries) && filter_var($config->db->params->showqueries, FILTER_VALIDATE_BOOLEAN);
$profilerMaxQueries  = (int) $config->db->params->maxqueries;
if ($dbprofiler->getEnabled() === true) : ?>
    <div class="debug dbprofiler">
        <div class="wrapper">
            <h2>Profiling information
                <?php if (isset($GLOBALS['start_mtime'])) : ?>
                    (execution time <?= microtime(true) - $GLOBALS['start_mtime'] ?>)
                <?php endif ?>
            </h2>
            <b>Total number of queries: </b><?= $dbprofiler->getTotalNumQueries() ?><br/>
            <b>Total query time (s): </b><?= $dbprofiler->getTotalElapsedSecs() ?><br/>
            <b>Current memory consumption: </b><?= memory_get_usage(true) ?><br/>
            <b>Peak memory consumption: </b><?= memory_get_peak_usage(true) ?><br/>
            <?php if ($profilerShowQueries === true && $profilerQueryProfiles = $dbprofiler->getQueryProfiles()) : ?>
                <b>Queries:</b><br/>
                <dl>
                    <?php $queryCount = null; ?>
                    <?php foreach ($profilerQueryProfiles as $value) :
                        if ($queryCount === null) {
                            // erste DB-Anweisung ist immer 'connect' - diese soll nicht ausgegeben werden; daher überspringen
                            $queryCount = 0;
                            continue;
                        } ?>
                        <dd style="margin-inline-start: 0;"><?= ++$queryCount ?>:</dd>
                        <dt style="margin-inline-start: 1em;">
                            <?php if ($queryCount > $profilerMaxQueries) :
                                echo '...';
                                break;
                            endif ?>
                            <pre><?= htmlspecialchars($value->getQuery()) ?></pre>
                        </dt>
                    <?php endforeach ?>
                </dl>
            <?php endif ?>
        </div>
    </div>
<?php endif ?>

<?php
$identity = Zend_Auth::getInstance()->getIdentity();
if (isset($config->debugSession) && ((bool) $config->debugSession === true) && ! empty($identity)) :
    ?>
    <div class="debug session">
        <div class="wrapper">
            <h2>Session</h2>

            <?php /* do not apply indentation here! */ ?>
<pre>
    <?= Zend_Debug::dump($_SESSION, 'Session Data', false); ?>
</pre>

        </div>
    </div>
<?php endif ?>

</body>
</html>
