<?php
/**
 * Index View for BrowsingController including links to several browsing lists and search functions
 *
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Solrsearch
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<h2><?= $this->translate('search_index_browsing') ?></h2>

<ul>
    <li>
        <a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'latest'), null, true) ?>"><?= $this->translate('latest_documents_title') ?></a>&nbsp;
        <a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'latest', 'output' => 'rss'), null, true) ?>" class="rss">
        <img src="<?= $this->layoutPath() ?>/img/feed.png" width="16" height="16" alt="<?= $this->translate('rss_icon') ?>" title="<?= $this->translate('rss_title') ?>" /></a>
    </li>
    <li>
        <a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'browse', 'action' => 'doctypes'), null, true) ?>"><?= $this->translate('search_index_doctype_browsing') ?></a>
    </li>

    <?php foreach ($this->collectionRoles as $collectionRole) :
        $translatelabel = 'search_index_custom_browsing_' . $collectionRole->getName();
        $printname = '';
        if ($translatelabel === $this->translate($translatelabel))
            $printname = $collectionRole->getName();
        else
            $printname = $this->translate($translatelabel);        
    ?>
    <li>
        <?php if (is_null($collectionRole->getRootCollection())) : ?>
            <?= htmlspecialchars($printname) ?>
        <?php else : ?>
            <a href="<?= $this->url(array('module' => 'solrsearch', 'controller' => 'index', 'action' => 'search', 'searchtype' => 'collection', 'id' => $collectionRole->getRootCollection()->getId()), null, true)?>"><?= htmlspecialchars($printname) ?></a>
        <?php endif ?>
    </li>
    <?php endforeach ?>
</ul>