<?
echo '<h1>'.$this->title.'</h1>';
echo '<h3>'.$this->subtitle.'</h3>';
?>        
    
<form enctype="application/x-www-form-urlencoded" action="<?php echo $this->action_url; ?>" method="post">

<?= $this->field("Element", null, $this->PersonSubmitterFirstName_); ?>
<?= $this->field("Element", null, $this->PersonSubmitterLastName_); ?>
<?= $this->field("Group", null, $this->groupPersonAuthor); ?>
<?= $this->field("Element", null, $this->Language_); ?>
<?= $this->field("Group", null, $this->groupTitleMain); ?>
<?= $this->field("Group", null, $this->groupTitleAbstract); ?>
<?= $this->field("Element", null, $this->TitleAdditional_); ?>
<?= $this->field("Element", null, $this->TitleParent_); ?>
<?= $this->field("Element", null, $this->PageNumber_); ?>
<?= $this->field("Element", null, $this->PageFirst_); ?>
<?= $this->field("Element", null, $this->PageLast_); ?>
<?= $this->field("Element", null, $this->Volume_); ?>
<?= $this->field("Element", null, $this->Issue_); ?>
<?= $this->field("Element", null, $this->Journal_); ?>
<?= $this->field("Element", null, $this->Institute_); ?>
<?= $this->field("Element", null, $this->Collection_); ?>
<?= $this->field("Element", null, $this->Publisher_); ?>
<?= $this->field("Element", null, $this->PublishedYear_); ?>
<?= $this->field("Element", null, $this->PublishedDate_); ?>
<?= $this->field("Element", null, $this->PublisherName_); ?>
<?= $this->field("Element", null, $this->PublisherPlace_); ?>
<?= $this->field("Element", null, $this->CompletedYear_); ?>
<?= $this->field("Element", null, $this->CompletedDate_); ?>
<?= $this->field("Element", null, $this->ThesisDateAccepted_); ?>
<?= $this->field("Element", null, $this->PublisherUniversity_); ?>
<?= $this->field("Element", null, $this->IdentifierOpus3_); ?>
<?= $this->field("Element", null, $this->IdentifierUrn_); ?>
<?= $this->field("Element", null, $this->IdentifierIsbn_); ?>
<?= $this->field("Element", null, $this->IdentifierIssn_); ?>
<?= $this->field("Element", null, $this->IdentifierOpac_); ?>
<?= $this->field("Element", null, $this->Grantor_); ?>
<?= $this->field("Group", null, $this->groupPersonReferee); ?>
<?= $this->field("Group", null, $this->groupPersonEditor); ?>
<?= $this->field("Group", null, $this->groupPersonAdvisor); ?>
<?= $this->field("Group", null, $this->groupPersonTranslator); ?>
<?= $this->field("Group", null, $this->groupPersonContributor); ?>
<?= $this->field("Group", null, $this->groupCreatingCorporation); ?>
<?= $this->field("Group", null, $this->groupContributingCorporation); ?>
<?= $this->field("Group", null, $this->groupSubjectSwd); ?>
<?= $this->field("Group", null, $this->groupSubjectUncontrolled); ?>
<?= $this->field("Element", null, $this->ServerDateValid_); ?>
<?= $this->field("Element", null, $this->Note_); ?>

<?= $this->field("Hidden", "fullText", $this->fullText); ?>
<?= $this->field("Hidden", "documentType", "all"); ?>
<?= $this->field("Hidden", "documentId", $this->documentId); ?>
<?= $this->field("Submit", "send", "Formular abschicken"); ?>

</form>

