<?
echo '<h1>'.$this->title.'</h1>';
echo '<h3>'.$this->subtitle.'</h3>';
echo $this->form;
?>


<form enctype="application/x-www-form-urlencoded" action="/opus4-devel/index.php/publish/index/check" method="post">

<?= $this->field("Group", null, $this->groupPersonSubmitter); ?>
<?= $this->field("Element", null, $this->Language_); ?>
<?= $this->field("Element", null, $this->IdentifierOpus3_); ?>
<?= $this->field("Element", null, $this->Licence_); ?>
<?= $this->field("Group", null, $this->groupPersonAuthor); ?>
<?= $this->field("Group", null, $this->groupTitleMain); ?>
<?= $this->field("Group", null, $this->groupTitleAbstract); ?>
<?= $this->field("Group", null, $this->groupTitleParent); ?>
<?= $this->field("Group", null, $this->groupPersonEditor); ?>
<?= $this->field("Group", null, $this->groupPersonTranslator); ?>
<?= $this->field("Group", null, $this->groupPersonContributor); ?>
<?= $this->field("Group", null, $this->groupCreatingCorporation); ?>    
<?= $this->field("Group", null, $this->groupContributingCorporation); ?>
<?= $this->field("Element", null, $this->PageFirst_); ?>
<?= $this->field("Element", null, $this->PageLast_); ?>    
<?= $this->field("Element", null, $this->PublishedYear_); ?>
<?= $this->field("Group", null, $this->groupSubjectSwd); ?>
<?= $this->field("Group", null, $this->groupSubjectUncontrolled); ?>
<?= $this->field("Element", null, $this->IdentifierUrn_); ?>
<?= $this->field("Element", null, $this->IdentifierOpac_); ?>
<?= $this->field("Group", null, $this->groupNote); ?>
    
<?= $this->field("Hidden", "fullText", $this->fullText); ?>
<?= $this->field("Hidden", "documentType", "article"); ?>
<?= $this->field("Hidden", "documentId", $this->documentId); ?>
<?= $this->field("Submit", "send", "Formular abschicken"); ?>

</form>

