<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @author      Susanne Gottwald <gottwald@zib.de>
 * @author      Doreen Thiede <thiede@zib.de>
 * @author      Maximilian Salomon <salomon@zib.de>
 * @copyright   Copyright (c) 2008-2018, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */
?>

<?PHP if ($this->jQueryEnabled() && !empty($this->extensions)) : ?>
<script>
    $(function() {
        var extensions = '<?= $this->extensions ?>';
        var fileElem = $("input:file")[0];
        fileElem.validFileExtensions = extensions.split(',');
    });
</script>
<?PHP endif ?>

<h2><?= $this->translate($this->title) ?></h2>
<div class="content">
    <h3 class="document-type"><?= $this->translate($this->subtitle) ?></h3>

    <?php if (isset($this->errorCaseMessage)) : ?>
        <div class="form-hint form-errors"><p><?= $this->errorCaseMessage; ?></p></div>
    <?php endif; ?>

        <form enctype="multipart/form-data" action="<?= $this->action_url; ?>" method="post">
            <div class="form-items-wrapper">
                <?= $this->element($this->documentType); ?>

                <?php if ($this->enableUpload) : ?>
                    <?= $this->element($this->MAX_FILE_SIZE, null, 'hidden', 'MAX_FILE_SIZE'); ?>
                    <?= $this->element($this->filenameMaxLength, null, 'hidden', 'filenameMaxLength'); ?>
                    <?= $this->element($this->filenameFormat, null, 'hidden', 'filenameFormat'); ?>
                    <?= $this->group($this->documentUpload); ?>
                    <?= $this->fileOverview(); ?>
                <?php endif; ?>

                <?php if ($this->showBib == 1) : ?>
                    <?= $this->element($this->bibliographie); ?>
                <?php endif; ?>

                <?php if ($this->showRights == 1) : ?>
                    <?= $this->element($this->rights); ?>
                <?php endif; ?>

            <div class="button-wrapper">
                <?= $this->element('button_label_send', "class='form-button submit-button'", "Submit", "send"); ?>
            </div>
        </div>            
    </form>
</div>