<?
echo '<h1>Opus Application - Veröffentlichen</h1>';
echo '<h3>Studienarbeit</h3>';
//echo $this->form;
?>

<form enctype="application/x-www-form-urlencoded" action="/opus4-devel/index.php/publish/index/check" method="post">
    <fieldset>
        <legend><?=$this->PersonSubmitter?></legend>
        <table>
            <tr>
                <td><label for="PersonSubmitterFirstName" class="required"><?=$this->PersonSubmitterFirstName_label?></label></td>
                <td><input type="text" name="PersonSubmitterFirstName" id="PersonSubmitterFirstName" value="<?=$this->PersonSubmitterFirstName?>" />
                    <? if (isset($this->PersonSubmitterFirstNameError)) echo '<ul class="errors">'. $this->PersonSubmitterFirstNameError .'</ul>'; ?>
                </td>
            </tr>
            <tr>
                <td><label for="PersonSubmitterLastName" class="required"><?=$this->PersonSubmitterLastName_label?></label></td>
                <td>
                    <input type="text" name="PersonSubmitterLastName" id="PersonSubmitterLastName" value="<?=$this->PersonSubmitterLastName?>" />
                    <? if (isset($this->PersonSubmitterLastNameError)) echo '<ul class="errors">'. $this->PersonSubmitterLastNameError .'</ul>'; ?>
                </td>
            </tr>
        </table>
    </fieldset>

    <fieldset>
        <legend><?=$this->PersonAuthor?></legend>
        <table>
             <?php if (isset($this->groupPersonAuthor)) {
                 foreach ($this->groupPersonAuthor["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" /></td>
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupPersonAuthor["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupPersonAuthor["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

   <fieldset>
        <legend><?=$this->TitleMain?></legend>
        <table>
             <?php if (isset($this->groupTitleMain)) {
                 foreach ($this->groupTitleMain["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupTitleMain["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupTitleMain["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>
    
    <table>
        <tr>
            <td><label for="Language" class="required"><?=$this->Language_label?></label></td>
            <td><input type="text" name="Language" id="Language" value="<?=$this->Language ?>" /></td>    
        </tr>
        <tr><td colspan="2"><? if (isset($this->LanguageError)) echo '<ul class="errors">'. $this->LanguageError .'</ul>'; ?></td></tr>

        <tr>
            <td><label for="PublishedYear" class="required"><?=$this->PublishedYear_label?></label></td>
            <td><input type="text" name="PublishedYear" id="Language" value="<?=$this->PublishedYear ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->PublishedYearError)) echo '<ul class="errors">'. $this->PublishedYearError .'</ul>'; ?></td></tr>
    </table>

    <fieldset>
        <legend><?=$this->SubjectSwd?></legend>
        <table>
             <?php if (isset($this->groupSubjectSwd)) {
                 foreach ($this->groupSubjectSwd["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupSubjectSwd["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupSubjectSwd["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <table>
        <tr>
            <td><label for="IdentifierOpus3" class="required"><?=$this->IdentifierOpus3_label?></label></td>
            <td><input type="text" name="Language" id="IdentifierOpus3" value="<?=$this->IdentifierOpus3 ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->IdentifierOpus3Error)) echo '<ul class="errors">'. $this->IdentifierOpus3eError .'</ul>'; ?></td></tr>
    </table>

    <fieldset>
        <legend><?=$this->TitleAbstract?></legend>
        <table>
             <?php if (isset($this->groupTitleAbstract)) {
                 foreach ($this->groupTitleAbstract["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupTitleAbstract["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupTitleAbstract["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>

    <table>
        <tr>
            <td><label for="Licence" class="required"><?=$this->Licence_label?></label></td>
            <td><input type="text" name="Licence" id="Licence" value="<?=$this->Licence ?>" /></td>
        </tr>
        <tr><td colspan="2"><? if (isset($this->LicenceError)) echo '<ul class="errors">'. $this->LicenceError .'</ul>'; ?></td></tr>
    </table>

    <fieldset>
        <legend><?=$this->PersonAdvisor?></legend>
        <table>
             <?php if (isset($this->groupPersonAdvisor)) {
                 foreach ($this->groupPersonAdvisor["Fields"] AS $field) { ?>
            <tr>
                <td><label for="<?=$field["id"]?>" class="<?=$field["req"]?>"><?=$field["label"]?></label></td>
                <td><input type="text" name="<?=$field["id"]?>" id="<?=$field["id"]?>" value="<?=$field["value"]?>" />
            </tr>
            <tr><td colspan="2"><?php if ($field["error"]!=null) {echo '<ul class="errors">';foreach($field["error"] AS $err)echo $err;echo '</ul>';} ?></td></tr>
           <?php }
            foreach ($this->groupPersonAdvisor["Buttons"] AS $button) { ?>
            <tr>
                <td><input type="submit" name="<?=$button["id"]?>" id="<?=$button["id"]?>" value="<?=$button["label"]?>" /></td>
            </tr>
        <?php }
            foreach ($this->groupPersonAdvisor["Hiddens"] AS $hidden) { ?>
             <input type="hidden" name="<?=$hidden["id"]?>" id="<?=$hidden["id"]?>" value="<?=$hidden["value"]?>" />
        <?php }} ?>
        </table>
    </fieldset>
                      


        <dt id="PersonContributorFirstName-label"><label for="PersonContributorFirstName" class="optional">Beitragender: Vorname</label></dt>
        <dd id="PersonContributorFirstName-element">
        <input type="text" name="PersonContributorFirstName" id="PersonContributorFirstName" value="<?=$this->PersonContributorFirstName?>" />
        <? if (isset($this->PersonContributorFirstNameError)) echo '<ul class="errors">'. $this->PersonContributorFirstNameError .'</ul>'; ?>
        </dd>

        <dt id="PersonContributorLastName-label"><label for="PersonContributorLastName" class="optional">Beitragender: Nachname</label></dt>
        <dd id="PersonContributorLastName-element">
        <input type="text" name="PersonContributorLastName" id="PersonContributorLastName" value="<?=$this->PersonContributorLastName?>" />
        <? if (isset($this->PersonContributorLastNameError)) echo '<ul class="errors">'. $this->PersonContributorLastNameError .'</ul>'; ?>
        </dd>

        <dt id="CreatingCorporation-label"><label for="CreatingCorporation" class="optional">Urhebende Körperschaft</label></dt>
        <dd id="CreatingCorporation-element">
        <input type="text" name="CreatingCorporation" id="CreatingCorporation" value="<?=$this->CreatingCorporation?>" />
        <? if (isset($this->CreatingCorporationError)) echo '<ul class="errors">'. $this->CreatingCorporationError .'</ul>'; ?>
        </dd>

        <dt id="ContributingCorporation-label"><label for="ContributingCorporation" class="optional">Beteiligte Körperschaft</label></dt>
        <dd id="ContributingCorporation-element">
        <input type="text" name="ContributingCorporation" id="ContributingCorporation" value="<?=$this->ContributingCorporation?>" />
        <? if (isset($this->ContributingCorporationError)) echo '<ul class="errors">'. $this->ContributingCorporationError .'</ul>'; ?>
        </dd>

        <dt id="PageNumber-label"><label for="PageNumber" class="optional">Seitenzahl</label></dt>
        <dd id="PageNumber-element">
        <input type="text" name="PageNumber" id="PageNumber" value="<?=$this->PageNumber?>" />
        <? if (isset($this->PageNumberError)) echo '<ul class="errors">'. $this->PageNumberError .'</ul>'; ?>
        </dd>

        <dt id="IdentifierUrn-label"><label for="IdentifierUrn" class="optional">URN</label></dt>
        <dd id="IdentifierUrn-element">
        <input type="text" name="IdentifierUrn" id="IdentifierUrn" value="<?=$this->IdentifierUrn?>" />
        <? if (isset($this->IdentifierUrnError)) echo '<ul class="errors">'. $this->IdentifierUrnError .'</ul>'; ?>
        </dd>

        <dt id="IdentifierOpac-label"><label for="IdentifierOpac" class="optional">Opac Id</label></dt>
        <dd id="IdentifierOpac-element">
        <input type="text" name="IdentifierOpac" id="IdentifierOpac" value="<?=$this->IdentifierOpac?>" />
        <? if (isset($this->IdentifierOpacError)) echo '<ul class="errors">'. $this->IdentifierOpacError .'</ul>'; ?>
        </dd>

       <dt id="Note-label"><label for="Note" class="optional">Bemerkung</label></dt>
        <dd id="Note-element">
        <textarea name="Note" id="Note" rows="5" cols="80"><?=$this->Note?></textarea>
        <? if (isset($this->NoteError)) echo '<ul class="errors">'. $this->NoteError .'</ul>'; ?>
        </dd>

        <dt id="documentType-label">&nbsp;</dt>
        <dd id="documentType-element">
        <input type="hidden" name="documentType" value="studienarbeit" id="documentType" />
        </dd>

        <dt id="documentId-label">&nbsp;</dt>
        <dd id="documentId-element">
        <input type="hidden" name="documentId" value="<?= $this->documentId ?>" id="documentId" />
        </dd>

        <dt id="fulltext-label">&nbsp;</dt>
        <dd id="fulltext-element">
        <input type="hidden" name="fulltext" value="<?= $this->fullText ?>" id="fullText" />
        </dd>

        <dt id="send-label">&nbsp;</dt><dd id="send-element">
        <input type="submit" name="send" id="send" value="Senden" />
        </dd>
</form>
