<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>


<h1><?=$this->translate('admin_title_collections') ?></h1>

<div class="adminContainer">

<?php if (!empty($this->breadcrumb)) : ?>
<div class="collection_breadcrumbs">
    <?= $this->translate('breadcrumb_title') ?>
    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'document' => $this->documentId), null, true)?>">Collections</a>
    <?php foreach($this->breadcrumb as $i => $parent) : ?>
        &raquo;
        <?php if ($i === 0) : ?>
            <?php if (count($this->breadcrumb) > 1) : ?>
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $parent->getId(), 'document' => $this->documentId), null, true) ?>"><?= htmlspecialchars($this->role_name) ?></a>
            <?php else : ?>
                <?= htmlspecialchars($this->role_name) ?>
            <?php endif ?>
        <?php elseif ($i === count($this->breadcrumb) - 1) : ?>            
            <?= htmlspecialchars($parent->getDisplayName()) ?>
        <?php else : ?>            
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $parent->getId(), 'document' => $this->documentId), null, true) ?>"><?= htmlspecialchars($parent->getDisplayName()) ?></a>
        <?php endif ?>
    <?php endforeach; ?>
</div>
<?php endif ?>

<div>
<a class="add" href="<?=$this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'edit', 'id' => $this->documentId), null, true)?>"><?=$this->translate('admin_collections_collection_assign_abort')?></a>
</div>

<table class="collections">
    <?php foreach($this->collections as $i => $collection) : ?>
    <tr class="<?= ($i %2 == 0) ? 'even' : 'odd'?>">
        <td>
            <?php if ($collection['hasChildren']) : ?>
                <a href="<?=$this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $collection['id'], 'document' => $this->documentId), null, true)?>"><?= htmlspecialchars($collection['name']) ?></a>
            <?php else : ?>
                <?= htmlspecialchars($collection['name']) ?>
            <?php endif ?>            
        </td>
        <td>
            <form method="post" action="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $collection['id'], 'document' => $this->documentId), null, true)?>">
                <input type="submit" value="<?=$this->translate('admin_collections_collection_assign_here')?>" />
            </form>
        </td>
    </tr>
    <? endforeach; ?>
</table>

</div>