<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<h1><?=$this->translate('admin_title_collections') ?></h1>

<?= $this->partial('docinfo.phtml', ['document' => $this->documentAdapter]) ?>

<?php if (! empty($this->breadcrumb)) : ?>
<div class="collection_breadcrumbs">
    <?= $this->translate('breadcrumb_title') ?>
    <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'document' => $this->documentId], null, true)?>">Collections</a>
    <?php foreach ($this->breadcrumb as $i => $parent) : ?>
        &raquo;
        <?php if ($i === 0) : ?>
            <?php if (count($this->breadcrumb) > 1) : ?>
                <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $parent->getId(), 'document' => $this->documentId], null, true) ?>"><?=
                    htmlspecialchars($this->translate('default_collection_role_' . $this->role_name)) ?></a>
            <?php else : ?>
                <?= htmlspecialchars($this->translate('default_collection_role_' . $this->role_name)) ?>
            <?php endif ?>
        <?php elseif ($i === count($this->breadcrumb) - 1) : ?>
            <?= htmlspecialchars($parent->getNumberAndName()) ?>
        <?php else : ?>
            <a href="<?= $this->url(['module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $parent->getId(), 'document' => $this->documentId], null, true) ?>"><?=
                htmlspecialchars($parent->getNumberAndName()) ?></a>
        <?php endif ?>
    <?php endforeach; ?>
</div>
<?php endif ?>

<div>
<a class="add" href="<?=$this->url(['module' => 'admin', 'controller' => 'document', 'action' => 'edit', 'id' => $this->documentId, 'section' => 'collections'], null, true)?>"><?=
    $this->translate('admin_collections_collection_assign_abort')?></a>
</div>

<table class="collections">
    <?php foreach ($this->collections as $i => $collection) : ?>
    <tr class="<?= $i % 2 === 0 ? 'even' : 'odd'?>">
        <td class="<?= $collection['visible'] ? 'visible' : 'invisible' ?><?=$collection['assigned'] ? ' assigned' : '' ?>">
            <?php if ($collection['hasChildren']) : ?>
                <a href="<?=$this->url(['module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $collection['id'], 'document' => $this->documentId], null, true)?>"><?=
                    htmlspecialchars($collection['name']) ?></a>
            <?php else : ?>
                <?= htmlspecialchars($collection['name']) ?>
            <?php endif ?>
        </td>
        <td>
            <?PHP if ($this->assignCollectionAllowed($collection, $this->documentId)) : ?>
            <form method="post" action="<?= $this->url(['module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'id' => $collection['id'], 'document' => $this->documentId], null, true)?>">
                <input type="submit" value="<?=$this->translate('admin_collections_collection_assign_here')?>" />
            </form>
            <?PHP endif ?>
        </td>
    </tr>
    <?PHP endforeach; ?>
</table>
