<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Ralf Claussnitzer (ralf.claussnitzer@slub-dresden.de)
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @author      Sascha Szott <szott@zib.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<div class="adminContainer">
    <div class="breadcrumbsContainer">
        <?= $this->navigation()->breadcrumbs() ?>
    </div>

    <div class="collection_new">
        <a class="add" href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'newrole')) ?>">
        <?= $this->translate('admin_collections_role_new') ?>
        </a>
    </div>

    <table class="collections">
    <?php foreach ($this->collectionRoles as $i => $collectionRole) :
        $translatelabel = 'search_index_custom_browsing_' . $collectionRole->getName();
        $printname = '';
        if ($translatelabel === $this->translate($translatelabel))
            $printname = $collectionRole->getName();
        else
            $printname = $this->translate($translatelabel);
    ?>
    <tr class="<?= ($i % 2 === 0) ? 'even' : 'odd' ?>">
        <td class="<?= ($collectionRole->getVisible() === '1') ? 'visible' : 'unvisible' ?>">
        <?php if (is_null($collectionRole->getRootCollection())) : ?>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'show', 'role' => $collectionRole->getId()), null, true)?>"><?= htmlspecialchars($printname) ?></a>
        <?php else : ?>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'show', 'id' => $collectionRole->getRootCollection()->getId()), null, true)?>"><?= htmlspecialchars($printname) ?></a>
        <?php endif ?>            
        </td>
        <td>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'editrole', 'roleid' => $collectionRole->getId()), null, true) ?>">
            <?= $this->translate('admin_collections_role_edit') ?>
            </a>
        </td>
        <?php if ($collectionRole->getVisible() === '1') : ?>
        <td>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'hiderole', 'roleid' => $collectionRole->getId()), null, true) ?>">
            <?= $this->translate('admin_collections_role_hide') ?>
            </a>
        </td>
        <?php else : ?>
        <td>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'unhiderole', 'roleid' => $collectionRole->getId()), null, true) ?>">
            <?= $this->translate('admin_collections_role_unhide') ?>
            </a>
        </td>
        <?php endif ?>
        <td>
            <?php if ($i > 0) : ?>
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'moverole', 'roleid' => $collectionRole->getId(), 'pos' => $this->collectionRoles[$i - 1]->getPosition()), null, true) ?>">
                <?= $this->translate('admin_collections_role_move_up') ?>
                </a>
            <?php endif ?>
        </td>
        <td>
            <?php if ($i < count($this->collectionRoles) - 1) : ?>
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'moverole', 'roleid' => $collectionRole->getId(), 'pos' => $this->collectionRoles[$i + 1]->getPosition()), null, true)?>">
                <?= $this->translate('admin_collections_role_move_down') ?>
                </a>
            <?php endif ?>
        </td>
        <td>
            <?php
            if (is_null($collectionRole->getRootCollection()) || count($collectionRole->getRootCollection()->getChildren()) === 0) {
                $confirmKey = 'confirm_deletion_empty';
            }
            else {
                $confirmKey = 'confirm_deletion';
            }
            ?>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'deleterole', 'roleid' => $collectionRole->getId()), null, true) ?>" onclick="return confirm('<?= $this->translate($confirmKey) ?>');">
            <?= $this->translate('admin_collections_role_delete') ?>
            </a>
        </td>
    </tr>
    <?php endforeach ?>
    </table>
</div>