<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Ralf Claussnitzer (ralf.claussnitzer@slub-dresden.de)
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
<h1>Opus Application - <?=$this->translate('admin_title_collections') ?></h1>
<table>
<? foreach($this->entries as $i=>$entry) : ?>
<tr>
<td><a href="<?= $this->url(array('action' => 'show', 'role' => $entry['id'])) ?>"><?= $entry['name'] ?></a>
</td>
<td><a href="<?= $this->url(array('action' => 'edit', 'role' => $entry['id'])) ?>">
<img src = "<?= $this->layoutPath . '/img/edit_collections_properties.gif';?>"
align='middle' border = '0' title = '<?=$this->translate('admin_collections_role_edit')?>'>
</a>
</td>
<td>
<a href="<?= $this->url(array('action' => 'manage', 'role' => $entry['id'], 'deleteall' => 'Delete'))?>">
<img src = "<?= $this->layoutPath . '/img/delete_collection_tree.gif';?>"
align='middle' border = '0' title = '<?=$this->translate('admin_collections_role_delete')?>'>
</a>
</td>
<td>
<? if ($i > 0) {?>
&nbsp;
<a href="<?= $this->url(array('action' => 'manage', 'role' => $entry['id'], 'move_up' => 'Up'))?>">
<img src = "<?= $this->layoutPath . '/img/move_up_collection_tree.gif';?>"
align='middle' border = '0' title = '<?=$this->translate('admin_collections_role_move_up')?>'>
</a>
<? }?>
</td>
<td>
<? if ($i < (count($this->entries) - 1)) {?>
&nbsp;
<a href="<?= $this->url(array('action' => 'manage', 'role' => $entry['id'], 'move_down' => 'Down'))?>">
<img src = "<?= $this->layoutPath . '/img/move_down_collection_tree.gif';?>"
align='middle' border = '0' title = '<?=$this->translate('admin_collections_role_move_down')?>'>
</a>
</td>
<? }?>
</tr>
<? endforeach; ?>
</table>
<a href="<?= $this->url(array('action' => 'new')) ?>"><img src = "<?= $this->layoutPath . '/img/new_collection_tree.gif';?>"
align='middle' border = '0' title = '<?=$this->translate('admin_collections_role_new') ?>'></a>
