<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
<h1>Opus Application - <?=$this->translate('admin_title_collections') ?></h1>

<p>
<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'index'), null,
    true)?>">Collections</a>
&gt;&nbsp;<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
    'role'=>$this->role_id, 'copy'=>$this->copy), null, true)?>"><?=$this->role_name?></a>
<? foreach($this->breadcrumb as $parent) : ?>
&gt;&nbsp;<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
    'node'=>$parent->getId(), 'copy'=>$this->copy), null, true)?>"><?= $parent->getCollection()->getDisplayName() ?></a>
<? endforeach; ?>
</p>
        <? if (isset($this->copy)) { ?>
<p>
            <? if (isset($this->breadcrumb)) {
                $node_ids = array_keys($this->breadcrumb);
                $node_id = array_pop($node_ids);?>
        <a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
        'node'=>$node_id), null, true)?>"><img src = "<?= $this->layoutPath . '/img/abort_copy_collection.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_copy_abort')?>'></a>
            <? } else {?>
        <a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
        'role'=>$this->role_id), null, true)?>"><?=$this->translate('admin_collections_collection_copy_abort')?></a>
            <? } ?>
</p>
        <? } ?>

<!-- ul -->
<table>
    <? foreach($this->subcollections as $node_id => $name) : ?>
    <tr class="<?=$this->visibility[$node_id]?>" <?=('hidden' === $this->visibility[$node_id])?'style="text-decoration:line-through"':''?>>
        <td width="400">
        <? if ((true === isset($this->copy)) AND (('allowed' === $this->copypaste[$node_id])) OR (false === isset($this->copy))) { ?>
            <a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
                'node'=>$node_id, 'copy'=>$this->copy), null, true)?>"><?=$name?></a>
        <? } else {       ?>
            <?=$name?>
        <? }  ?>
</td><td>
        <? if (true === isset($this->copy)) { ?>
        <? if (false === in_array('forbidden', $this->copypaste)) { ?>

            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'create',
                'below' => $node_id, 'copy'=>$this->copy), null, true)?>"><img src = "<?= $this->layoutPath . '/img/add_collection_below.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_paste_below')?>'></a>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'create',
                'above' => $node_id, 'copy'=>$this->copy), null, true)?>"><img src = "<?= $this->layoutPath . '/img/add_collection_above.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_paste_above')?>'></a>
        <? }  ?>

        <? } else { ?>

            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'edit',
                'role'=>$this->role_id, 'node'=>$node_id), null, true) ?>"><img src = "<?= $this->layoutPath . '/img/edit_collection.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_edit')?>'></a>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'new',
                'role'=>$this->role_id, 'below' => $node_id), null, true)?>"><img src = "<?= $this->layoutPath . '/img/add_collection_below.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_add_below')?>'></a>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'new',
                'role'=>$this->role_id, 'above' => $node_id), null, true)?>"><img src = "<?= $this->layoutPath . '/img/add_collection_above.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_add_above')?>'></a>
            <?
        if ('several' === $this->severalAppearances[$node_id]) {
            ?>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'node' => $node_id, 'deleteall' => 'Delete'), null, true) ?>"><img src = "<?= $this->layoutPath . '/img/delete_collection_everywhere.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_delete_everywhere')?>'></a>
            <?
        } else if ('visible' === $this->visibility[$node_id]) {
            ?>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'node' => $node_id, 'deleteall' => 'Delete'), null, true) ?>"><img src = "<?= $this->layoutPath . '/img/delete_collection.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_delete')?>'></a>
            <?
        }
        if ('several' === $this->severalAppearances[$node_id]) {
            ?>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'node' => $node_id, 'undeleteall' => 'UnDelete'), null, true) ?>"><img src = "<?= $this->layoutPath . '/img/undelete_collection_everywhere.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_undelete_everywhere')?>'></a>
            <?
        } else if ('hidden' === $this->visibility[$node_id]) {
            ?>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'node' => $node_id, 'undeleteall' => 'UnDelete'), null, true) ?>"><img src = "<?= $this->layoutPath . '/img/undelete_collection.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_undelete')?>'></a>
            <?
        }
        if ('several' === $this->severalAppearances[$node_id]) {
            ?>
            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'node' => $node_id, 'delete' => 'Delete'), null, true) ?>"><img src = "<?= $this->layoutPath . '/img/delete_collection.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_delete_here')?>'></a>
            <?
        }
     ?>
     </td><td>

            &nbsp;&nbsp;&nbsp; <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'show',
                'copy' => $node_id), null, true)?>"><img src = "<?= $this->layoutPath . '/img/copy_collection.png';?>" align='middle' border = '0' title = '<?=$this->translate('admin_collections_collection_copy')?>'></a>
        <? }
        ?>
</td>
    </tr>
    <? endforeach; ?>

    <? if (0 === count($this->subcollections)) : ?>
    <tr class="visible" >
        <td width="400">
    <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'new',
                'node' => $node_id), null, true)?>">
                <img src = "<?= $this->layoutPath . '/img/add_collection_below.png';?>" align='middle' border = '0'
                    title = '<?=$this->translate('admin_collections_collection_add_below')?>'></a>
</td>
    </tr>
    <? endif; ?>

</table>
