<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
<h1>Opus Application - <?= $this->title ?></h1>
<p>
<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'index'), null,
    true)?>">Collections</a>
&gt;&nbsp;<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
    'role'=>$this->role_id), null, true)?>"><?=$this->role_name?></a>
<? foreach($this->breadcrumb as $path => $name) : ?>
&gt;&nbsp;<a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
    'role'=>$this->role_id, 'path'=>$path), null, true)?>"><?=$name?></a>
<? endforeach; ?>
</p>
<ul>
    <? foreach($this->subcollections as $path => $name) : ?>
    <li class="<?=$this->visibility[$path]?>" <?=('hidden' === $this->visibility[$path])?'style="text-decoration:line-through"':''?>>
        <form action="<?= $this->url(array('action' => 'manage', 'role'=>$this->role_id, 'path'=>$path)) ?>" method="post">
            <a href="<?=$this->url(array('module'=>'admin', 'controller'=>'collection', 'action'=>'show',
                'role'=>$this->role_id, 'path'=>$path), null, true)?>"><?=$name?></a>
            <a href="<?= $this->url(array('action' => 'edit', 'role' => $this->role_id, 'path'=>$path)) ?>">Edit</a>
            <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'new',
                'role' => $this->role_id, 'below' => $path), null, true)?>">Add Below</a>
            <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'new',
                'role' => $this->role_id, 'above' => $path), null, true)?>">Add Above</a>





     <?
        if ('several' === $this->severalAppearances[$path]) {
            ?>
            <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'role' => $this->role_id, 'path' => $path, 'deleteall' => 'Delete')) ?>">Delete everywhere</a>
            <?
        } else {
     ?>
            <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'role' => $this->role_id, 'path' => $path, 'deleteall' => 'Delete')) ?>">Delete</a>
            <?
        }
     ?>

     <?
        if ('several' === $this->severalAppearances[$path]) {
            ?>
            <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'role' => $this->role_id, 'path' => $path, 'undeleteall' => 'UnDelete')) ?>">Undelete everywhere</a>
            <?
        } else {
     ?>
            <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'role' => $this->role_id, 'path' => $path, 'undeleteall' => 'UnDelete')) ?>">Undelete</a>
            <?
        }
     ?>



     <?
        if ('several' === $this->severalAppearances[$path]) {
            ?>
            <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'manage',
                'role' => $this->role_id, 'path' => $path, 'delete' => 'Delete')) ?>">Delete here</a>
            <?
        }
     ?>




        </form>
    </li>
    <? endforeach; ?>
</ul>
<a href="<?= $this->url(array('action' => 'new')) ?>">New</a>
