<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Sascha Szott <szott@zib.de>
 * @author      Felix Ostrowski <ostrowski@hbz-nrw.de>
 * @copyright   Copyright (c) 2008-2010, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<h1><?= $this->translate('admin_title_collections') ?></h1>

<div class="adminContainer">

    <div class="collection_breadcrumbs">
        <?= $this->translate('breadcrumb_title') ?>
        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collectionroles', 'action' => 'index'), null, true) ?>"><?= $this->translate('admin_title_collections') ?></a>
        <?php foreach($this->breadcrumb as $i => $parent) : ?>
            &raquo;
            <?php if ($i === 0) : ?>
                <?php if (count($this->breadcrumb) > 1) : ?>
                    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'show', 'id' => $parent->getId()), null, true) ?>"><?= htmlspecialchars($this->role_name) ?></a>
                <?php else : ?>
                    <?= htmlspecialchars($this->role_name) ?>
                <?php endif ?>
            <?php elseif ($i === count($this->breadcrumb) - 1) : ?>
                <?= htmlspecialchars($parent->getDisplayName()) ?>
            <?php else : ?>
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'show', 'id' => $parent->getId()), null, true) ?>"><?= htmlspecialchars($parent->getDisplayName()) ?></a>
            <?php endif ?>
        <?php endforeach; ?>
    </div>

    <table class="collections">
    <?php if (0 === count($this->collections)) : ?>
        <tr>
            <td>
                <a class="add" href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'new', 'id' => $this->collection_id, 'type' => 'child'), null, true)?>">
                <?= $this->translate('admin_collections_collection_add') ?>
                </a>
            </td>
        </tr>
    <?php else : ?>
        <tr>
            <td colspan="0">
                <a class="add" href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'new', 'id' => $this->collection_id, 'type' => 'child'), null, true) ?>"><?=$this->translate('admin_collections_collection_add')?></a>
            </td>
        </tr>
        <?php foreach ($this->collections as $i => $collection) : ?>
        <tr class="<?= ($i % 2 == 0) ? 'even' : 'odd'?>">
            <td class="<?= ($collection->getVisible() === '1') ? 'visible' : 'unvisible' ?>">
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'show', 'id' => $collection->getId()), null, true) ?>">
                <?= htmlspecialchars($collection->getDisplayName()) ?>
                </a>
            </td>

            <td>
                <a href="<?= $this->url(array('module'=>'admin', 'controller'=>'collection', 'action' => 'edit', 'id' => $collection->getId()), null, true) ?>"><?=$this->translate('admin_collections_collection_edit')?></a>
            </td>

            <td>
                <?php if ($collection->getVisible() === '1') : ?>
                    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'hide', 'id' => $collection->getId()), null, true) ?>"><?=$this->translate('admin_collections_collection_hide')?></a>
                <?php else : ?>
                    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'unhide', 'id' => $collection->getId()), null, true) ?>"><?=$this->translate('admin_collections_collection_unhide')?></a>
                <?php endif ?>
            </td>

            <td>
                <?php if ($i > 0) : ?>
                    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'move', 'id' => $collection->getId(), 'pos' => $i), null, true) ?>">
                    <?= $this->translate('admin_collections_role_move_up') ?>
                    </a>
                <?php endif ?>
            </td>

            <td>
                <?php if ($i < count($this->collections) - 1) : ?>
                    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'move', 'id' => $collection->getId(), 'pos' => $i + 2), null, true)?>">
                    <?= $this->translate('admin_collections_role_move_down') ?>
                    </a>
                <?php endif ?>
            </td>

            <td>
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'index', 'collectionid' => $collection->getId()), null, true) ?>">
                <?= $this->translate('admin_collections_show_associated') ?>
                </a>
            </td>
            
            <td>
                <?php $confirmKey = count($collection->getChildren()) > 0 ? 'confirm_deletion' : 'confirm_deletion_empty'; ?>
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'delete', 'id' => $collection->getId()), null, true) ?>" onclick="return confirm('<?= $this->translate($confirmKey) ?>');"><?=$this->translate('admin_collections_collection_delete')?></a>
            </td>
        </tr>
        <tr>
            <td colspan="0">
                <a class="add" href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'new', 'id' => $collection->getId(), 'type' => 'sibling'), null, true) ?>"><?=$this->translate('admin_collections_collection_add')?></a>
            </td>
        </tr>
        <?php endforeach ?>
    <?php endif ?>
    </table>
</div>