<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category   Application
 * @package    Module_Webapi
 * @author     Henning Gerhardt (henning.gerhardt@slub-dresden.de)
 * @copyright  Copyright (c) 2009, OPUS 4 development team
 * @license    http://www.gnu.org/licenses/gpl.html General Public License
 * @version    $Id$
 */
?>

<h1><?php echo $this->title ?></h1>

<h2>General informations</h2>

<ul>
    <li>The webapi module works on HTTP requests like GET, POST, UPDATE or DELETE (there are some more).</li>
    <li>The GET request could be handled by web browsers over links. All other kinds of requests could only performed with a REST client.</li>
</ul>

<p/>

<h2>Document:</h2>

<h3>get usage (works with web browsers and rest clients):</h3>
<ul>
    <li><a href="<?php echo $this->url(array('controller' => 'document', 'module' => 'webapi'), null, true) ?>">GET <?php echo $this->url(array('controller' => 'document', 'module' => 'webapi'), null, true) ?></a><br />get all documents in this repository</li>
    <li><a href="<?php echo $this->url(array('controller' => 'document', 'module' => 'webapi'), null, true) ?>/37">GET <?php echo $this->url(array('controller' => 'document', 'module' => 'webapi'), null, true) ?>/37</a><br />get a specific document <br /><strong>works only with test data</strong></li>
</ul>

<p/>

<h3>post usage (only with rest client):</h3>
<ul>
    <li>TODO</li>
</ul>

<p/>

<h3>put usage (only with rest client):</h3>
<ul>
    <li>TODO</li>
</ul>

<p/>

<h3>delete usage (only with rest client):</h3>
<ul>
    <li>DELETE <?php echo $this->url(array('controller' => 'document', 'module' => 'webapi'), null, true) ?>/37 <br />delete a specific document<br /><strong>works only with test data</strong></li>
</ul>

<p/>

<h2>Searching:</h2>

<h3>get usage:</h3>

<p>
Supported parameters:
<ul>
    <li>field&lt;number&gt;</li>
    <li>query&lt;number&gt;</li>
    <li>boolean&lt;number&gt;</li>
    <li>language</li>
    <li>searchtype</li>
</ul>
</p>

<p>
Valid values for parameter <strong>field&lt;number&gt;</strong>:
<ul>
    <li>author</li>
    <li>title</li>
    <li>... supported values for lucence searching ...</li>
</ul>
</p>

<p />

<p>
Valid values for parameter <strong>query&lt;number&gt;</strong>:
<ul>
    <li>any utf-8 encoded input value</li>
</ul>
</p>

<p />

<p>
Valid values for paraemter <strong>boolean&lt;number&gt;</strong>:
<ul>
    <li>AND</li>
    <li>OR</li>
    <li>NOT ( &lt;expression&gt; and not &lt;expression&gt;)</li>
</ul>
</p>

<p/><p>&lt;number&gt; are numbers from 0 to infinity</p>


<p />

<p>
Valid values for parameter <strong>language</strong>strong:
<ul>
    <li>Zend_Language values or what ever lucence searching used ;)</li>
</ul>

<p />

<p>
Valid values for parameter <strong>searchtype</strong>:
<ul>
    <li>empty</li>
    <li>truncated - added to every search query a asteriks in front and end of term</li>
</ul>
</p>

<p />
<p>Examples:
<ul>
    <li><?php echo $this->url(array('controller' => 'search', 'module' => 'webapi'), null, true) ?>?field0=title&query0=gegen&searchtype=truncated</li>
    <li><?php echo $this->url(array('controller' => 'search', 'module' => 'webapi'), null, true) ?>?field0=author&query0=oliver</li>
</ul>
</p>

<p />

<h3>post, put und delete usage:</h3>

<h4 style="color: red;">Will never be supported.</h4>

<p />

<h2>Document types:</h2>

<h3>get usage:</h3>

<ul>
    <li><a href="<?php echo $this->url(array('controller' => 'doctypes', 'module' => 'webapi'), null, true) ?>"><?php echo $this->url(array('controller' => 'doctypes', 'module' => 'webapi'), null, true) ?></a><br />Get a list of available document types</li>
    <li><a href="<?php echo $this->url(array('controller' => 'doctypes', 'module' => 'webapi'), null, true) ?>/doctoral_thesis"><?php echo $this->url(array('controller' => 'doctypes', 'module' => 'webapi'), null, true) ?>/doctoral_thesis</a><br />Get a document type: doctoral thesis</li>
</ul>

<p />

<h3>post, put und delete usage:</h3>

<h4 style="color: red;">Not supported, yet. Needs write permission on system!</h4>

<p />