<p>
<?php
if ($this->current === 1) {
    if ($this->totalItemCount > 1) {
        printf($this->translate("browsing_titles_resultlist") . "<br/>", $this->totalItemCount);
    } else {
        printf($this->translate("browsing_titles_resultlist_one_entry") . "<br/>", $this->totalItemCount);
    }
}
if ($this->pageCount > 1) {
    printf($this->translate("search_results_from_to"), $this->firstItemNumber, ($this->firstItemNumber+$this->currentItemCount-1));
}
?>
</p>
