<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Wolfgang Filter (wolfgang.filter@ub.uni-stuttgart.de)
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id: index.phtml 659 2008-09-01 11:03:28Z claussnitzer $
 *
 *
 *
 * This view checks for existing keys in the commited array
 * If existing, keys and values are dumped
 *
 *
 *
 */

?>
<h1>Opus Application - <?echo $this->pagetitle; ?></h1><hr>
<?echo $this->header; ?><br>


<?
foreach ($this->mydummydata as $key => $value)
{

    if ($key === 'url')
    {
       ?><b><?echo $this->text_url;?>: </b>
         <a href="<?echo $this->value = $value;?>"><?echo $this->value = $value;?>
         </a><br><hr><br><br><?
    }?>

    <?
    if ($key === 'urn')
    {
       ?><b><?echo $this->text_urn;?>: </b>
         <a href="<?echo $this->value = 'http://nbn-resolving.de/urn/resolver.pl?' . $value;?>"><?echo $this->value = $value;?>
         </a><br><?
    }?>

    <?
    if ($key === 'title')
    {
        ?><b><?echo $this->value = $value;?>
          </b><br><br><?
    }?>

    <?
    if ($key === 'author')
    {
        ?><b><?echo $this->value = $value;?>
          </b><br><br><br><br><?
    }?>

    <?
    if ($key === 'swd')
    {
       ?><b><?echo $this->text_swd;?>: </b>
       <?echo $this->value = $value;?>
        <br><br><?
    }?>

    <?
    if ($key === 'ddc')
    {
       ?><b><?echo $this->text_ddc;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'publisher_name')
    {
       ?><b><?echo $this->text_publisher_name;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'publisher_place')
    {
       ?><b><?echo $this->text_publisher_place;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'completed_year')
    {
       ?><b><?echo $this->text_completed_year;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'published_date')
    {
       ?><b><?echo $this->text_published_date;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'reviewed')
    {
        if ($value === 'peer')
        {
          ?><b><?echo $this->text_reviewed;?>: </b>
          <?echo $this->text_peer;?>
          <br><br><?
        }
    }?>

    <?
    if ($key === 'published_year')
    {
       ?><b><?echo $this->text_published_year;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'language')
    {
       ?><b><?echo $this->text_language;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'document_type')
    {
       ?><b><?echo $this->text_document_type;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }?>

    <?
    if ($key === 'abstract')
    {
       ?><b><?echo $this->text_abstract;?>: </b>
       <?echo $this->value = $value;?>
       <br><br><?
    }
}?>
