<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Frontdoor
 * @author      Wolfgang Filter (wolfgang.filter@ub.uni-stuttgart.de)
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 *
 *
 *
 * This view gets a filtered one-dimensional associative array ($mydoc_data) from
 * the Frontdoor-Controller and displays it. The order of elements is fixed here.
 * Abstracts and keywords were combined with language information and displayed directly.
 *
 *
 */
?>
<h1><?= $this-> translate('frontdoor_pagetitle') ?></h1><hr />
<? if (is_array($this->mydoc_data) === true)
   {?>
      <div id="summary">
       <?  for ($i = 0; $i < 10; $i++)
           {
              if (array_key_exists ('IdentifierUrn_' .$i. '_Value', $this->mydoc_data) === true)
              {
                 $value = $this->mydoc_data['IdentifierUrn_' .$i. '_Value'];?>
                 <?= $this-> translate('frontdoor_entry'); ?><br />
                 <b><?= $this-> translate ('IdentifierUrn');?>: </b>
                 <a href="<?= $this->value = 'http://nbn-resolving.de/urn/resolver.pl?' .$value;?>">
                 <?= $this->value = $value;?></a><br /><br /><hr />
                 <?
              }
            }?>
              <? for ($i = 0; $i < 10; $i++)
                 {
                    if (array_key_exists ('TitleMain_'.$i.'_Value', $this->mydoc_data) === true)
                    {
                       $value = $this->mydoc_data['TitleMain_'.$i.'_Value'];?>
                       <p><h2><?= $this->value = $value;?></h2></p><?
                    }
                 }?>
               <?for ($i = 0; $i < 10; $i++)
                 {
                    if (array_key_exists ('PersonAuthor_'.$i.'_Name', $this->mydoc_data) === true)
                    {
                        $value = $this->mydoc_data['PersonAuthor_'.$i.'_Name'];?>
                        <p><b><a href="<?= $this->value =
                            $this->url(array(
                                'module' => 'search',
                                'controller' => 'search',
                                'action' => 'metadatasearch',
                                'author' => $value,
                            ), null, true);
                        ?>">
                        <?= $this->value = $value;?></a></b></p><?
                    }
                 }


                 if ($this->fileNumber !== 0)
                 {?>
                    <p><b><?= $this-> translate('File(s): ')?>&nbsp;&nbsp;</b><?

                    for ($i = 0; $i < $this->fileNumber; $i++)
                    {
                       if (array_key_exists ('File_'.$i. '_PathName', $this->mydoc_data) === true)
                       {
                          $path_name = $this ->mydoc_data['File_' .$i. '_PathName'];
                          //echo ($path_name);

                          if (array_key_exists ('File_' .$i. '_FileType', $this->mydoc_data) === true)
                          {
                             $file_type = $this->mydoc_data['File_' .$i. '_FileType'];
                             //echo ($file_type);
                             if (array_key_exists ('File_'.$i. '_FileSize', $this->mydoc_data) === true)
                             {
                                $file_size = $this ->mydoc_data['File_' .$i. '_FileSize'];
                                //echo ($file_size);?>
                                <a href="<?= $this->value = '/files/'.$this->docId.'/'.$this->path_name = $path_name;?>">
                                <img src = "<?= $this->value = $this->layoutPath . '/img/filetypelogo_' .$file_type. '.png';?>"
                                title = 'Download <?= $this->value = '-' .$path_name?>'>
                                (<?$this->file_type = $file_type. ', ' .$file_size?>)</a>&nbsp;&nbsp;<?
                             }
                             else
                             {?>
                                <a href="<?= $this->value = '/files/'.$this->docId.'/'.$this->path_name = $path_name;?>">
                                <img src = "<?= $this->value = $this->layoutPath . '/img/filetypelogo_' .$file_type. '.png';?>"
                                title = 'Download<?= $this->value = '-' .$path_name?>'>
                                (<?= $this->file_type = $file_type?>)</a>&nbsp;&nbsp;<?
                             }
                         }
                         else
                         {?>
                             <a href="<?= $this->value = '/files/'.$this->docId.'/'.$this->path_name = $path_name;?>">
                             <img src = "<?= $this->value = $this->layoutPath . '/img/filetypelogo_' .$file_type. '.png';?>"
                             title = 'Download<?= $this->value = '-' .$path_name?>'></a>&nbsp;&nbsp;<?
                         }
                      }
                    }
                 }?></p>

                     <p><a href="<?= $this->value =
                        $this->url(array(
                            'module' => 'frontdoor',
                            'controller' => 'hash',
                            'docId' => $this->docId,
                        ), null, true);

                     ?>">
                     <img src = "<?= $this->value = $this->layoutPath . '/img/unversehrt.jpg';?>" border = '0' title = 'Unversehrtheit'></a>

                    <a href="<?= $this->value = '';?>">
                    <img src = "<?= $this->value = $this->layoutPath . '/img/hand.jpg';?>" border = '0' title = 'Empfehlung'></a>

                    <a href="<?= $this->value =
                        $this->url(array(
                            'module' => 'statistic',
                            'controller' => 'index',
                            'action' => 'index',
                            'docId' => $this->docId,
                        ), null, true);
                    ;?>">
                    <img src = "<?= $this->value =
                        $this->url(array(
                            'module' => 'statistic',
                            'controller' => 'graph',
                            'action' => 'thumb',
                            'id' => $this->docId,
                        ));
                    ?>" border = '0' title = 'Statistik'></a>

                    <a href="<?= $this->value =
                        $this->url(array(
                            'module' => 'socialBookmarking',
                            'controller' => 'connotea',
                            'docId' => $this->docId,
                        ), null, true);
                      ?>">
                    <img src = "<?= $this->value =  $this->layoutPath .'/img/connotea_icon.jpg';?>" border = '0' title = 'Bookmark bei Connotea'></a>

                    <a href="<?= $this->value =
                        $this->url(array(
                            'module' => 'socialBookmarking',
                            'controller' => 'delicious',
                            'docId' => $this->docId,
                        ), null, true);
                      ?>">
                    <img src = "<?= $this->value = $this->layoutPath . '/img/delicious.jpg';?>" border = '0' title = 'Bookmark bei del.icio.us'></a>

                    <a href="<?= $this->value = '';?>">
                    <img src = "<?= $this->value = $this->layoutPath . '/img/google_scholar.jpg';?>" border = '0' title = 'Dokument in Google Scholar suchen'></a>

                    <a href="<?= $this->value = '';?>">
                    <img src = "<?= $this->value = $this->layoutPath . '/img/bibtex.jpg';?>" border = '0' title = 'BibTex-Export'></a>

                    <a href="<?= $this->value = '';?>">
                    <img src = "<?= $this->value = $this->layoutPath . '/img/ris.jpg';?>" border = '0' title = 'RIS-Export'></a>
                </p>

                 <br />
                 <?if (array_key_exists('Type', $this->mydoc_data))
                   {
                       $value = $this->mydoc_data['Type'];?>
                       <p><b><?= $this-> translate('Type')?>: </b>
                       <?= $this->value = $value;?></p><?
                   }
                   for ($i = 0; $i < 10; $i++)
                   {
                      if (array_key_exists('Language_' .$i, $this->mydoc_data) === true)
                      {
                         $this->value = $value = $this->mydoc_data['Language_' .$i];?>
                         <p><b><?= $this-> translate('Language')?>: </b>
                         <?= $this->translate($value);?></p><?
                      }
                   }?>

                   <?for ($i = 0; $i < 10; $i++)
                   {
                      if (array_key_exists ('SubjectSwd_'.$i.'_Value', $this->mydoc_data) === true)
                      {
                         if (array_key_exists ('SubjectSwd_'.$i.'_Language', $this->mydoc_data) === true)
                         {
                            $this->value = $value = $this->mydoc_data['SubjectSwd_'.$i.'_Value'];
                            $this->lang = $lang = $this->mydoc_data['SubjectSwd_'.$i.'_Language'];
                         }?>
                         <p><b><?= $this-> translate('SubjectSwdValue') .' ('. $this->translate($lang). ')';?>: </b>
                         <?= $this->value = $value;?></p><?                      }
                   }?>

                   <?for ($i = 0; $i < 10; $i++)
                   {
                      if (array_key_exists ('SubjectUncontrolled_'.$i.'_Value', $this->mydoc_data) === true)
                      {
                          if (array_key_exists ('SubjectUncontrolled_'.$i.'_Language', $this->mydoc_data) === true)
                          {
                              $this->value = $value = $this->mydoc_data['SubjectUncontrolled_'.$i.'_Value'];
                              $this->lang = $lang = $this->mydoc_data['SubjectUncontrolled_'.$i.'_Language'];
                          }?>
                           <p><b><?= $this-> translate('SubjectUncontrolledValue') .' ('. $this->translate($lang). ')';?>: </b>
                           <?= $this->value = $value;?></p><?
                      }
                   }?>

                   <?for ($i = 0; $i < 10; $i++)
                   {
                      if (array_key_exists ('Psyindex_'.$i.'_Value', $this->mydoc_data) === true)
                      {
                          if (array_key_exists ('SubjectPsyndex_'.$i.'_Language', $this->mydoc_data) === true)
                          {
                              $this->value = $value = $this->mydoc_data['SubjectPsyndex_'.$i.'_Value'];
                              $this->lang = $lang = $this->mydoc_data['SubjectPsyndex_'.$i.'_Language'];
                          }?>
                          <p><b><?= $this-> translate('SubjectPsyndexValue') .' ('. $this->translate($lang). ')';?>: </b>
                          <?= $this->value = $value;?></p><?
                      }
                  }?>

                  <?if (array_key_exists ('PublishedYear', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['PublishedYear'];?>
                     <p><b><?= $this-> translate('PublishedYear')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  if (array_key_exists ('PublishedDate', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['PublishedDate'];?>
                     <p><b><?= $this-> translate('PublishedDate')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  if (array_key_exists ('CompletedDate', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['CompletedDate'];?>
                     <p><b><?= $this-> translate('CompletedDate')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  if (array_key_exists ('CompletedYear', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['CompletedYear'];?>
                     <p><b><?= $this-> translate('CompletedYear')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  if (array_key_exists ('DateAccepted', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['DateAccepted'];?>
                     <p><b><?= $this-> translate('DateAccepted')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  for ($i=0; $i<10; $i++)
                  {
                     if (array_key_exists ('IdentifierIsbn_' .$i. '_Value', $this->mydoc_data) === true)
                     {
                       $value = $this->mydoc_data['IdentifierIsbn_' .$i. '_Value'];?>
                       <p><b><?= $this-> translate('IdentifierIsbn')?>: </b>
                       <?= $this->value = $value;?></p><?
                      }
                  }
                  if (array_key_exists ('PageNumber', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['PageNumber'];?>
                     <p><b><?= $this-> translate('PageNumber')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  if (array_key_exists ('CreatingCorporation', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['CreatingCorporation'];?>
                     <p><b><?= $this-> translate('CreatingCorporation')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  if (array_key_exists ('ContributingCorporation', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['ContributingCorporation'];?>
                     <p><b><?= $this-> translate('ContributingCorporation')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  if (array_key_exists ('NonInstituteAffiliation', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['NonInstituteAffiliation'];?>
                     <p><b><?= $this-> translate('NonInstituteAffiliation')?>: </b>
                     <?= $this->value = $value;?></p><?
                  }
                  for ($i = 0; $i < 10; $i++)
                  {
                    if (array_key_exists ('PersonContributor_'.$i.'_Name', $this->mydoc_data) === true)
                    {
                        $value = $this->mydoc_data['PersonContributor_'.$i.'_Name'];?>
                        <p><b><?= $this-> translate('PersonContributor')?>: </b>
                        <?= $this->value = $value;?></p><?
                    }
                  }
                  for ($i = 0; $i < 10; $i++)
                  {
                    if (array_key_exists ('PersonAdvisor_'.$i.'_Name', $this->mydoc_data) === true)
                    {
                        $value = $this->mydoc_data['PersonAdvisor_'.$i.'_Name'];?>
                        <p><b><?= $this-> translate('PersonAdvisor')?>: </b>
                        <?= $this->value = $value;?></p><?
                    }
                  }
                  for ($i = 0; $i < 10; $i++)
                  {
                    if (array_key_exists ('PersonReferee_'.$i.'_Name', $this->mydoc_data) === true)
                    {
                        $value = $this->mydoc_data['PersonReferee_'.$i.'_Name'];?>
                        <p><b><?= $this-> translate('PersonReferee')?>: </b>
                        <?= $this->value = $value;?></p><?
                    }
                  }
                  for ($i = 0; $i < 10; $i++)
                  {
                    if (array_key_exists ('PersonEditor_'.$i.'_Name', $this->mydoc_data) === true)
                    {
                        $value = $this->mydoc_data['PersonEditor_'.$i.'_Name'];?>
                        <p><b><?= $this-> translate('PersonEditor')?>: </b>
                        <?= $this->value = $value;?></p><?
                    }
                  }

                    if (array_key_exists ('PersonTranslator_Name', $this->mydoc_data) === true)
                    {
                        $value = $this->mydoc_data['PersonTranslator_Name'];?>
                        <p><b><?= $this-> translate('PersonTranslator')?>: </b>
                        <?= $this->value = $value;?></p><?
                    }

                  for ($i = 0; $i < 10; $i++)
                  {
                    if (array_key_exists ('PersonOther_'.$i.'_Name', $this->mydoc_data) === true)
                    {
                        $value = $this->mydoc_data['PersonOther_'.$i.'_Name'];?>
                        <p><b><?= $this-> translate('PersonOther')?>: </b>
                        <?= $this->value = $value;?></p><?
                    }
                  }
                  for ($i = 0; $i < 10; $i++)
                  {
                      if (array_key_exists ('TitleAbstract_'.$i.'_Value', $this->mydoc_data) === true)
                      {
                          if (array_key_exists ('TitleAbstract_'.$i.'_Language', $this->mydoc_data) === true)
                          {
                              $this->value = $value = $this->mydoc_data['TitleAbstract_'.$i.'_Value'];
                              $this->lang = $lang = $this->mydoc_data['TitleAbstract_'.$i.'_Language'];
                          }?>
                           <p><b><?= $this-> translate('TitleAbstractValue') .' ('. $this->translate($lang). ')';?>: </b>
                           <?= $this->value = $value;?></p><?
                      }
                  }
                  if (array_key_exists ('Licence_NameLong', $this->mydoc_data) === true)
                  {
                     $value = $this->mydoc_data['Licence_NameLong'];?>
                     <p><b><?= $this-> translate('Licence_NameLong')?>: </b>
                   <?if (substr($this->value = $value,0,16) === 'Creative Commons')
                     {?>
                       <img src = "<?= $this->value = '/layouts/default/img/somerights20.gif';?>" title = 'Creative Commons'>
                       <a href="<?= $this->value = 'http://creativecommons.org/licenses/by-nc-nd/2.0/de/deed.de';?>">
                       <?= $this->value = $value;?></a></p><?
                     }
                     else
                     {?>
                     <img src = "<?= $this->value = '/layouts/default/img/unilogo.gif';?>" title = 'University of Stuttgart'>
                      <a href="<?= $this->value = '';?>">
                       <?= $this->value = $value;?></a></p><?
                     }
                  }?>
                  <p><b><?= $this-> translate('POD')?>: </b>
                  <img src = "<?= $this->value = '/layouts/default/img/proprint_logo.png';?>" border = '0' title = 'Print-on-Demand'>
                  <a href="<?= $this->value = '';?>">Print-on-Demand</a></p>
       </div>
  <?}


