<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2015, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<div class="messages">
    <?php if (isset($this->messages)) : ?>
        <?php foreach ($this->messages as $messageType => $message) : ?>
            <div class="<?= $messageType ?>">
                <?= $message ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>


<div class="frontdoor_pagination">
    <div>

        <ul class="paginationControl">
            <li>
                <?= $this->translate('results_title_single') ?> <span id="pagination-current-hit"><?= $this->searchPosition + 1 ?></span> <?= $this->translate('pagination_of') ?> <span id="pagination-num-hits"><?= $this->numOfHits ?></span>
            </li>
            <li id="pagination-previous">
                <?php if ($this->searchPosition === $this->firstEntry) : ?>
                    <div title="<?= $this->translate('pagination_previous_entry') ?>"></div>
                <?php else : ?>
                    <a id="frontdoor-link-prev" title="<?= $this->translate('pagination_previous_entry') ?>" href="<?= $this->url(['start' => $this->previousEntry, 'nav' => 'prev', 'docId' => null]); ?>"></a>
                <?php endif ?>
            </li>

            <li id="pagination-next">
                <?php if ($this->searchPosition === $this->lastEntry) : ?>
                    <div title="<?= $this->translate('pagination_next_entry') ?>"></div>
                <?php else : ?>
                    <a id="frontdoor-link-next" title="<?= $this->translate('pagination_next_entry') ?>" href="<?= $this->url(['start' => $this->nextEntry, 'nav' => 'next', 'docId' => null]); ?>"></a>
                <?php endif ?>
            </li>
        </ul>
    </div>

    <a id="pagination-link-hitlist" href="<?=
       $this->url([
           'module'     => 'solrsearch',
           'controller' => 'index',
           'action'     => 'search',
           'rows'       => $this->listRows,
           'start'      => floor(($this->searchPosition) / $this->listRows) * $this->listRows,
           'nav'        => null,
           'docId'      => null,
       ])
        ?>"><?= $this->translate('back_to_result_list') ?></a>

</div>
