<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2021, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<h1><?= $this->translate('admin_import_bibtex')?></h1>

<?= $this->form ?>

<?php if ($this->importResult !== null) : ?>
<p>
    <?= $this->translate('admin_import_bibtex_label_output')?>
</p>

<p>
<pre class="pre-wrapped">
    <?=$this->importResult?>
</pre>
</p>

    <table>
    <tr>
        <td><?= $this->translate('admin_import_bibtex_label_num_docs_processed')?></td>
        <td><?= $this->numDocsProcessed ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('admin_import_bibtex_label_num_docs_imported')?></td>
        <td><?= $this->numDocsImported ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('admin_import_bibtex_label_num_skipped')?></td>
        <td><?= $this->numSkipped ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('admin_import_bibtex_label_num_errors')?></td>
        <td><?= $this->numErrors ?></td>
    </tr>
</table>
<p>
    <a href="<?= $this->bibtexImportLink ?>" title="<?= $this->translate('admin_bibtex_import_tooltip') ?>"
       class="link-button"><?= $this->translate('admin_import_bibtex_label_button') ?></a>
</p>
<?php endif; ?>

