<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<dl class="table">
  <dt><?= $this->translate('admin_doctype_numDocs')?>:</dt>
  <dd><?= $this->numDocs ?></dd>
  <dt><?=$this->translate('admin_doctype_numActiveDocs')?>:</dt>
  <dd><?= $this->numActiveDocs ?></dd>
</dl>

<?PHP if (in_array(0, $this->content)) : ?>
<div><?= $this->translate('admin_doctype_errors') ?></div>
<?PHP endif; ?>

<table>
    <thead>
        <tr>
            <th><?= $this->translate('Opus_Document_Type') ?></th>
            <th><?= $this->translate('admin_doctype_filename') ?> </th>
            <th><?= $this->translate('admin_doctype_status') ?></th>
            <th></th>
        </tr>
    </thead>

    <?PHP foreach ($this->content as $doctype => $validation) : ?>
        <tr id="<?= $doctype ?>" class="<?= $validation ? 'admin_doctype' : 'admin_doctype_fail' ?>" >
            <th class="<?= array_key_exists($doctype, $this->activeDoctypes) ? '' : 'invisible' ?>"><?= $this->translate($doctype) ?></th>
            <td class="<?= array_key_exists($doctype, $this->activeDoctypes) ? '' : 'invisible' ?>"><?= $doctype ?></td>
            <td class="<?= array_key_exists($doctype, $this->activeDoctypes) ? '' : 'invisible' ?>"
                ><?= array_key_exists($doctype, $this->activeDoctypes) ? $this->translate('admin_doctype_active') :
                    $this->translate('admin_doctype_inactive') ?></td>
            <td><a href="<?= 'doctype/show/doctype/' . $doctype?>"><?= $validation ? '' :
                        $this->translate('admin_doctype_errorMsg')?></a></td>
        </tr>
    <?PHP endforeach ?>
</table>
