<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the North Rhine-Westphalian Library Service Center,
 * the Cooperative Library Network Berlin-Brandenburg, the Saarland University
 * and State Library, the Saxon State Library - Dresden State and University
 * Library, the Bielefeld University Library and the University Library of
 * Hamburg University of Technology with funding from the German Research
 * Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Admin
 * @author      Jens Schwidder <schwidder@zib.de>
 * @copyright   Copyright (c) 2009, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id: edit.phtml 7528 2011-02-10 15:49:13Z schwidder $
 */
?>

<div class="adminContainer">

    <div class="breadcrumbsContainer">
        <?= $this->navigation()->breadcrumbs()
                 ->setMaxDepth(1)
                 ->setLinkLast(true) ?>
        &gt;
        <a href="<?=$this->url(array(
            'module' => 'admin',
            'controller' => 'document',
            'action' => 'index',
            'id' => $this->docHelper->getDocId()
        ));?>"><?= $this->translate('admin_document_breadcrumb_document', $this->docHelper->getDocId()) ?></a>
        &gt;
        <?= $this->translate('admin_document_breadcrumb_edit') ?>
    </div>

        <fieldset>

        <legend><a name="collections"><?= $this->translate('admin_documents_label_collections') ?></a></legend>

    <div>
        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'collection', 'action' => 'assign', 'document' => $this->docHelper->getDocId()), null, true); ?>"><?= $this->translate('admin_documents_collectionassign'); ?></a><br/>
    </div>

    <?PHP if (0 < count($this->assignedCollections)) : ?>
        <?= $this->translate('admin_documents_collectionsassigned') ?>
    <?PHP else : ?>
        <?= $this->translate('admin_documents_nocollectionsassigned') ?>
    <?PHP endif; ?>

    <ul>
        <?PHP foreach ($this->assignedCollections as $collection) : ?>
        <li>
            <?= htmlspecialchars($collection['roleName'])?>: <?= htmlspecialchars($collection['collectionName']) ?>
            <form method="post" action="<?= $this->url(array('module' => 'admin', 'controller' => 'documents', 'action' => 'unlinkcollection', 'role' => $collection['roleId'], 'collection' => $collection['collectionId'])) ?>">
                <input type="submit" value="<?= $this->translate('admin_documents_unlinkcollection') ?>" />
            </form>
        </li>
        <?PHP endforeach; ?>
    </ul>

    </fieldset>

</div>
