<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>
<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Expires" CONTENT="-1">
<h1><?= $this->translate('statistic_index_title') ?></h1>
<h2><?= $this->authors?></h2>
<h3><?= $this->title?></h3>
<p><?= $this->translate('total_views')?>
    <?= $this->translate('graph_legend_frontdoor')?>:
<?= $this->totalAbstractPage?>,
<?= $this->translate('graph_legend_files')?>:
<?= $this->totalFiles?> </p>
<p><img src="<?= $this->url([
    'module'     => 'statistic',
    'controller' => 'graph',
    'action'     => 'year',
    'id'         => $this->docId,
]); ?>"
alt="<?=$this->translate('graph_year_title') . ' (' . $this->translate('graph_legend_frontdoor') . ', ' . $this->translate('graph_legend_files') . '): ' . $this->altTextStat?>"
/>
</p>

<p><img src="<?= $this->url([
    'module'     => 'statistic',
    'controller' => 'graph',
    'action'     => 'month',
    'id'         => $this->docId,
]); ?>"
alt ="<?=$this->translate('graph_month_title')?>"
/>
</p>
<p><a href="<?= $this->url([
    'module'     => 'frontdoor',
    'controller' => 'index',
    'action'     => 'index',
    'docId'      => $this->docId,
]); ?>"
    >
    <?= $this->translate('back_to_frontdoor'); ?>
   </a>
</p>