<?php
/**
 * Indexview for actions with public keys and signature verification
 * 
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Pkm
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>
<h1><?= $this->title ?></h1>
<?= $this->form ?><br/>
<?= $this->actionresult ?><br/>
<?php
    if ($this->masterkey !== false)
    {
    	$masterkey_id = $this->masterkey->getPrimaryKey()->getId();
   	?>
        <?= $this->translate('pkm_masterkey') ?><br/>
        <ol>
        <li><?= $this->masterkey->getPrimaryKey()->getId() ?> Fingerprint: <?= $this->masterkey->getPrimaryKey()->getFingerprint() ?><br/>
        <?php
	    if ($this->masterkey->getPrimaryKey()->canSign() === false) 
        {
	    ?>
	        <?= $this->translate('pkm_key_nosign') ?><br/>
	    <?php
	    }
	    // This should not happen with autodetection
	    if ($this->masterkey->getPrimaryKey()->hasPrivate() === false) 
        {
	    ?>
	        <?= $this->translate('pkm_key_noprivate') ?><br/>
	    <?php
	    }
	    // This should not happen with autodetection
	    if (0 < $this->masterkey->getPrimaryKey()->getExpirationDate() && $this->masterkey->getPrimaryKey()->getExpirationDate() < time()) 
        {
        ?>
	        <?= $this->translate('pkm_key_expired') ?><br/>
	    <?php
	    }
	    foreach ($this->masterkey->getUserIds() as $user)
	    {
	    ?>
	        <?= $user->getName() ?> <?= $user->getEmail() ?><br/>
	    <?php
	    }
	    ?>
        <a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'showkey', 'fingerprint' => $this->masterkey->getPrimaryKey()->getFingerprint())) ?>"><?= $this->translate('pkm_show_key') ?></a><br/>
    	<a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'disablekey', 'fingerprint' => $this->masterkey->getPrimaryKey()->getFingerprint())) ?>"><?= $this->translate('pkm_disable_masterkey') ?></a><br/>
	    </li>
	    </ol>
	    <?php
    }
    else 
    {
    	$masterkey_id = 0;
    	?>
    	<?= $this->translate('pkm_no_masterkey') ?><br/>
    	<?php
    }
?>
<br/>
<?php
    if (count($this->keys) > 0) { 
    ?>
    <ul>
    <?php
        foreach ($this->keys as $key) 
        {
    	    if ($key->getPrimaryKey()->getId() !== $masterkey_id)
    	    {
    	    ?>
    	        <li><?= $key->getPrimaryKey()->getId() ?> Fingerprint: <?= $key->getPrimaryKey()->getFingerprint() ?><br/>
    	        <?php
    	        if (0 < $key->getPrimaryKey()->getExpirationDate() && $key->getPrimaryKey()->getExpirationDate() < time()) 
    	        {
    	        ?>
    		        <?= $this->translate('pkm_key_expired') ?><br/>
    		    <?php
    	        }
    	        foreach ($key->getUserIds() as $user)
    	        {
    	        ?>
    		        <?= $user->getName() ?> <?= $user->getEmail() ?><br/>
    		    <?php
    	        }
    	        ?>
    	        <a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'showkey', 'fingerprint' => $key->getPrimaryKey()->getFingerprint())) ?>"><?= $this->translate('pkm_show_key') ?></a><br/>
    	        <!--<a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'signkey', 'fingerprint' => $key->getPrimaryKey()->getFingerprint())) ?>"><?= $this->translate('pkm_sign_key') ?></a><br/>-->
    	        <a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'deletekey', 'fingerprint' => $key->getPrimaryKey()->getFingerprint())) ?>"><?= $this->translate('pkm_delete_key') ?></a><br/>
    	        </li>
    	    <?php
    	    }
        }
    ?>
    </ul>
    <?php
    }
    else
    {
        ?>
        <?= $this->translate('pkm_no_keys') ?>
        <?php
    }
?>