<?php
/**
 * Indexview for actions with public keys and signature verification
 * 
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Pkm
 * @author      Oliver Marahrens <o.marahrens@tu-harburg.de>
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id: index.phtml 2159 2009-03-12 13:36:06Z claussnitzer $
 */
?>
<h1><?= $this->title ?></h1>
<?php
    if ($this->noFileSelected === true)
    {
    	echo $this->translate('pkm_no_publication_selected');
    }
    else {
        foreach ($this->verifyResult as $file => $verification)
        {
        ?>
    	    <?= $file ?>
    	    <?php
    	    if (count($verification) === 0)
    	    {
    	    ?>
    	    	<div class="invalid">
    		    <?= $this->translate('pkm_no_signature') ?>
    		    </div>
    		<?php
    	    }
    	    foreach($verification as $verifiedArray)
    	    {
    		    foreach($verifiedArray as $verified)
    		    {
    		        if ($verified->isValid() === true)
    		        {
    		        ?>
    		        	<div class="valid">
    		            <?php 
    		                printf($this->translate('pkm_sigcheck_valid'), $verified->getUserId()->getName()); 
    		            ?>
    		            </div>
    		        <?php
    		        }
    		        else
    		        {
    		        ?>
    		        	<div class="invalid">
    		        	<?php 
    		        	    printf($this->translate('pkm_sigcheck_invalid'), $verified->getUserId()->getName()); 
    		        	?>
        		        </div>
        		    <?php
        		    }
        		    // Show key used for signature
        		    ?>
        		    <a href="<?= $this->url(array('module' => 'pkm', 'controller' => 'index', 'action' => 'showkey', 'fingerprint' => $verified->getKeyFingerprint())) ?>"><?= $this->translate('pkm_show_key') ?></a>
        		<?php
    	    	}
    	    }
    	}
    }
?>