	<form action="<?= $this->url(array('module' => 'import', "controller"=>"opus3", "action"=>"import")) ?>" method="POST" enctype="multipart/form-data">
	XML-Dump des Opus3-Repositories: 
	<input type="file" name="xmldump" />
	<br/>Format: 
	<input type="radio" name="xmlformat" value="mysqldump" checked="true" />MySQLDump
	<!--<input type="radio" name="xmlformat" value="phpmyadmin" />PhpMyAdmin-->
	<br/>
	<input type="submit" value="Importieren" />
	</form>
<!--
	<form action="<?= $this->url(array("controller"=>"import", "action"=>"importOpus3Repository")) ?>" method="POST">
	Geben Sie die OAI-Adresse des zu importierenden Opus3-Repositories ein (mit &Uuml;bernahme der vorhandenen IDs): 
	<input type="text" name="oaiUrl" value="http://doku.b.tu-harburg.de/oai/oai2.php" />
	<input type="submit" value="Importieren" />
	</form>
	<form action="<?= $this->url(array("controller"=>"import", "action"=>"importRepository")) ?>" method="POST">
	Geben Sie die OAI-Adresse des zu importierenden Repositories ein (IDs neu vergeben): 
	<input type="text" name="oaiUrl" value="http://doku.b.tu-harburg.de/oai/oai2.php" />
	<input type="submit" value="Importieren" />
	</form>
	<form action="<?= $this->url(array("controller"=>"import", "action"=>"importEntry")) ?>" method="POST">
	Geben Sie die OAI-Adresse des zu importierenden Eintrags ein: 
	<input type="text" name="oaiUrl" value="http://doku.b.tu-harburg.de/oai/oai2.php?verb=GetRecord&metadataPrefix=XMetaDissPlus&identifier=oai:oai.tubdok.tu-harburg.de:82" />
	<select name="metadataFormat">
	<option value="OAIXMetaDissPlus">XMetaDissPlus &uuml;ber OAI</otion>
	</select>
	<input type="submit" value="Importieren" />
	</form>
-->