<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Matheon
 * @author      Thoralf Klein <thoralf.klein@zib.de>
 * @copyright   Copyright (c) 2011, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 */
?>

<p>
<?php foreach ($this->years as $year) : ?>
        <!-- <a title="documents published in year <?= $year ?>" href="<?= $this->url(array('module' => 'matheon', 'controller' => 'check-data', 'action' => 'list', 'year' => $year)) ?>"><?= $year ?></a> -->
<?php endforeach; ?>
</p>

<p>
<?php if (count($this->stats) > 0) : ?>
    <table style="empty-cells: show;">
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>authors</th>
            <th>#errors</th>
            <th>-</th>

            <th>Project?</th>
            <th>MSC?</th>
            <th>Referee?</th>
        <tr>

        <?php $count = 0; ?>
        <?php foreach ($this->stats AS $docStats) : ?>
        <?php
            if ($docStats['errors'] == 0) {
                continue;
            } ?>
        <tr style="background-color: <?= (++$count%2 == 0) ? '#ededed' : '#f8f8f8' ?>;">
            <td>#<?= $count ?></td>
            <td>
                <a title="view document" href="<?= $this->url(array('module' => 'frontdoor', 'controller' => 'index', 'action' => 'index', 'docId' => $docStats['id'])) ?>"><?= $docStats['id'] ?></a>
            </td>
            <td>
                <?php foreach ($docStats['authorEmails'] AS $author) : ?>
                <?php if (empty($author['email'])) : ?>
                    <span style="color:red"><?= $author['name'] ?></span>
                <?php else : ?>
                    <a href="mailto:<?= $author['email'] ?>"><?= $author['name'] ?></a>
                <?php endif; ?>

                <?php endforeach; ?>
            </td>
            <td><?= $docStats['errors'] ?></td>
            <td>&nbsp;</td>

            <td><?= $docStats['missingProject'] ? 'MISSING' : 'ok' ?></td>
            <td><?= $docStats['missingMsc'] ? 'MISSING' : 'ok' ?></td>
            <td><?= $docStats['missingReferee'] ? 'MISSING' : 'ok' ?></td>
        </tr>
        <?php endforeach; ?>

    </table>
<?php endif; ?>
</p>

<p>
<?php if (count($this->email2docid) > 0) : ?>
    <table style="empty-cells: show;">
        <tr>
            <th>#</th>
            <th>-</th>
            <th>email</th>
            <th>name</th>
            <th>documents</th>
        <tr>

        <?php $count = 0; ?>
        <?php foreach ($this->email2docid AS $key => $entry) : ?>
        <tr style="background-color: <?= (++$count%2 == 0) ? '#ededed' : '#f8f8f8' ?>;">
            <td>#<?= $count ?></td>
            <td><?= htmlspecialchars($key) ?></td>
            <td><?= $entry['email'] ?></td>
            <td><?= $entry['name'] ?></td>
            <td>
            <?php foreach ($entry['ids'] AS $id) : ?>
                <a title="view document" href="<?= $this->url(array('module' => 'frontdoor', 'controller' => 'index', 'action' => 'index', 'docId' => $id)) ?>"><?= $id ?></a>
            <?php endforeach; ?>
            </td>
        </tr>
        <?php endforeach; ?>

    </table>
<?php endif; ?>
</p>
