<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

?>

<h1><?= $this->translate('admin_title_indexmaintenance') ?></h1>

<?php if (isset($this->featureDisabled) && $this->featureDisabled) : ?>

<div class="featuredisabled"><?= $this->translate('admin_indexmaintenance_disabled') ?></div>

<?php else : ?>

<div class="operation">
    <div class="opname"><?= $this->translate('admin_indexmaintenance_consistencycheck_name') ?></div>
    <div class="opdescription"><?= $this->translate('admin_indexmaintenance_consistencycheck_description') ?></div>
    <?php if ($this->allowConsistencyCheck) : ?>
        <div class="oprun">
            <form method="post" action="<?= $this->url(['module' => 'admin', 'controller' => 'indexmaintenance', 'action' => 'checkconsistency'], null, true) ?>">
                <input type="submit" value="<?= $this->translate('admin_indexmaintenance_runjob') ?>">
            </form>
        </div>
    <?php else : ?>
        <?php if (isset($this->error) && array_key_exists('consistencycheck', $this->error)) : ?>
            <div class="opprogress"><?= $this->translate('admin_indexmaintenance_error') ?></div>
        <?php else : ?>
            <div class="opprogress"><?= $this->translate('admin_indexmaintenance_' . $this->state['consistencycheck']) ?></div>
        <?php endif ?>
    <?php endif ?>

    <?php if (isset($this->content) && array_key_exists('consistencycheck', $this->content)) : ?>
        <div>
        <?= $this->translate('admin_indexmaintenance_joboutput') ?> (<?= $this->translate('admin_indexmaintenance_jobcompletiontime') ?>: <?= $this->contentLastModTime['consistencycheck'] ?>):

        <?PHP /* DO NOT INDENT pre ELEMENT */ ?>
<pre class="opoutput">
        <?= $this->content['consistencycheck'] ?>
</pre>
        
        </div>
    <?php endif ?>
</div>

<!-- TODO feature will be implemented in a later version OPUSVIER-2955 -->
    <?php if (! $this->disabledFeatureFulltextExtractionCheck) : ?>
<div class="operation">
    <div class="opname"><?= $this->translate('admin_indexmaintenance_fulltextextractioncheck_name') ?></div>    
    <div class="opdescription"><?= $this->translate('admin_indexmaintenance_fulltextextractioncheck_description') ?></div>
        <?php if ($this->allowFulltextExtractionCheck) : ?>
        <div class="oprun">
            <form method="post" action="<?= $this->url(['module' => 'admin', 'controller' => 'indexmaintenance', 'action' => 'checkfulltexts'], null, true) ?>">
                <input type="submit" value="<?= $this->translate('admin_indexmaintenance_runjob') ?>">
            </form>
        </div>
        <?php else : ?>
        <div class="opprogress"><?= $this->translate('admin_indexmaintenance_' . $this->state['fulltextextractioncheck']) ?></div>
        <?php endif ?>
        
        <?php if (isset($this->content) && array_key_exists('fulltextextractioncheck', $this->content)) : ?>
        <div>
            <?= $this->translate('admin_indexmaintenance_joboutput') ?> (<?= $this->translate('admin_indexmaintenance_jobcompletiontime') ?>: <?= $this->contentLastModTime['fulltextextractioncheck'] ?>):

            <?PHP /* DO NOT INDENT pre ELEMENT */ ?>
<pre class="opoutput">
            <?= $this->content['fulltextextractioncheck'] ?>
</pre>
        
        </div>
        <?php endif ?>        
</div>
    <?php endif ?>

<!-- TODO feature will be implemented in a later version OPUSVIER-2956 -->
    <?php if (! $this->disabledFeatureIndexOptimization) : ?>
<div class="operation">    
    <div class="opname"><?= $this->translate('admin_indexmaintenance_indexoptimize_name') ?></div>        
    <div class="opdescription"><?= $this->translate('admin_indexmaintenance_indexoptimize_description') ?></div>
        <?php if ($this->allowIndexOptimization) : ?>
        <div class="oprun">
            <form method="post" action="<?= $this->url(['module' => 'admin', 'controller' => 'indexmaintenance', 'action' => 'optimizeindex'], null, true) ?>">
                <input type="submit" value="<?= $this->translate('admin_indexmaintenance_runjob') ?>">
            </form>
        </div>
        <?php else : ?>
        <div class="opprogress"><?= $this->translate('admin_indexmaintenance_' . $this->state['indexoptimize']) ?></div>
        <?php endif ?>
        
        <?php if (isset($this->content) && array_key_exists('indexoptimize', $this->content)) : ?>
        <div>
            <?= $this->translate('admin_indexmaintenance_joboutput') ?> (<?= $this->translate('admin_indexmaintenance_jobcompletiontime') ?>: <?= $this->contentLastModTime['indexoptimize'] ?>):

            <?PHP /* DO NOT INDENT pre ELEMENT */ ?>
<pre class="opoutput">
            <?= $this->content['indexoptimize'] ?>
</pre>
        
        </div>
        <?php endif ?>        
</div>
    <?php endif ?>

<?php endif ?>