#!/bin/bash
set -e

BASEDIR='/var/local/opus4'

sudo a2enmod rewrite proxy proxy_http php5
sudo ln -si "$BASEDIR/apacheconf/opus4" /etc/apache2/sites-available
sudo a2ensite opus4

if [ "$1" = upgrade ]
then 
    sudo chmod +x "$BASEDIR/install/update.sh"
    sudo "$BASEDIR/install/update.sh"
else
    sudo chmod +x "$BASEDIR/install/install.sh"
    sudo "$BASEDIR/install/install.sh" ubuntu
fi

sudo /etc/init.d/apache2 reload

