#!/bin/bash

BASEDIR='/var/local/opus4'

sudo a2enmod rewrite proxy proxy_http php5
sudo ln -si $BASEDIR/apacheconf/opus4 /etc/apache2/sites-available
sudo a2ensite opus4
sudo /etc/init.d/apache2 reload

if [ "$1" == "upgrade" ]
then 
    sudo chmod +x $BASEDIR/install/update.sh
    sudo sh $BASEDIR/install/update.sh
else
    sudo chmod +x $BASEDIR/install/install_ubuntu.sh
    sudo sh $BASEDIR/install/install_ubuntu.sh
