#!/bin/bash

BASEDIR='/var/local/opus4'

read -p "Do you want to upgrade your OPUS software to the newest version? [y/n] : " ANSWER
if [ $ANSWER == 'y' -o $ANSWER == 'Y' ]
then
    sudo chmod +x $BASEDIR/install/update.sh
    sudo $BASEDIR/install/update.sh
else
    exit 1;