<?php
/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @category    Application
 * @package     Module_Frontdoor
 * @author      Wolfgang Filter (wolfgang.filter@ub.uni-stuttgart.de)
 * @copyright   Copyright (c) 2008, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 * @version     $Id$
 *
 *
 *
 * This view gets the filtered result-array from the Frontdoor-Controller
 * and displays it.
 *
 *
 */
?>
<h1><?= $this-> translate('frontdoor_pagetitle') ?></h1><hr />



<? if (is_array($this->mydoc_data) === true)
   {?>
    <div id="summary">
       <? foreach ($this->mydoc_data as $key => $value)
          {
              if ($key === 'IdentifierUrn_Value')
              {?>
                 <?= $this-> translate('frontdoor_entry'); ?><br />
                 <b><?= $this-> translate ('IdentifierUrn');?>: </b>
                 <a href="<?= $this->value = 'http://nbn-resolving.de/urn/resolver.pl?' .$value;?>">
                 <?= $this->value = $value;?></a><br /><hr /><br />
                 <?
              }
              for ($i = 0; $i < 10; $i++)
              {
                 if ($key === 'TitleMain_'.$i.'_Value')
                 {?>
                 <p><h2><?= $this->value = $value;?></h2></p><?
                 }
              }
              for ($i = 0; $i < 10; $i++)
              {
                 if ($key === 'PersonAuthor_'.$i.'_Name')
                 {?>
                    <p><b><?= $this->value = $value;?></b></p><?
                 }?><p></p><p></p><?
              }
              if ($key === 'Swd_ger')
              {?>
                 <p><b><?= $this-> translate('SwdGer')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'Swd_eng')
              {?>
                 <p><b><?= $this-> translate('SwdEng')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'Uncontrolled_ger')
              {?>
                 <p><b><?= $this-> translate('UncontrolledGer')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'Uncontrolled_eng')
              {?>
                 <p><b><?= $this-> translate('UncontrolledEng')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'Language')
              {?>
                 <p><b><?= $this-> translate('Language')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'Type')
              {?>
                 <p><b><?= $this-> translate('Type')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'PublishedYear')
              {?>
                 <p><b><?= $this-> translate('PublishedYear')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'CompletedYear')
              {?>
                 <p><b><?= $this-> translate('CompletedYear')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'IdentifierIsbn')
              {?>
                 <p><b><?= $this-> translate('IdentifierIsbn')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              if ($key === 'CreatingCorporation')
              {?>
                 <p><b><?= $this-> translate('CreatingCorporation')?>: </b>
                 <?= $this->value = $value;?></p><?
              }
              for ($i = 0; $i < 10; $i++)
              {
                 if ($key === 'TitleAbstract_'.$i.'_Value')
                 {
                    $val = prev($this->mydoc_data);


                    if (($val === 'en') || ($val === 'eng'))
                       {?>
                         <p><b><?= $this-> translate('AbstractEng')?>: </b>
                         <?= $this->value = $value;?><?
                       }?><?
                       if (($val === 'de') || ($val === 'ger'))
                       {?>
                          <p><b><?= $this-> translate('AbstractGer')?>: </b>
                           <?= $this->value = $value;?><?
                       }

                 }
              }
          }?>
    </div><?
   }?>


